### ISSUE TITLE
Unified FE constructor

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#100]
We want to create a unified FE Space constructor, namely function `FESpace`. I will allow to chose from a set of pre-defined FE spaces. 

The predefined FE space is chosen via the `fetype` key-word argument. Possible values would be `:CLagrangian`, `:DLagrangian`, `:PDisc`, and `:RaviartThomas`.

The other keyword arguments will be the ones needed for the particular fe type chosen: e.g.:
```julia
FESpace(
  fetype=:CLagrangian,
  valuetype=Float64, 
  model=mymodel,
  order=k,
  diritags=mytags,
  dirimasks=mymasks)
```

**EDIT: I think that this version is not needed, if we have the constructor described below**

**Comment by fverdugo** [comment]
```julia
FESpace(reffe=reffe,conformity=true,model=mymodel,diritags=mytags)
conformity = :HDiv, conformity=:H1, conformity=:L2, conformity=true, conformity=false , conformity=:HCurl, conformity=:default
```

**Comment by santiagobadia** [comment]
We want to create a` FESpace` that enforces zero mean value.
We will internally fix one DOF, e.g., the first one.
Then, when returning FE functions, it will compute the mean value and extract the constant from the vector of free DOFs.

**Comment by fverdugo** [comment]
@santiagobadia I have enhanced a bit the interfaces we have discussed before. Please take a look at the posts above this one (which have been edited).

I think that the first version we have think of ( in which we pass `fetype = CLagrangian`, `DLagrangian`, etc )is not needed.

**Comment by santiagobadia** [comment]
I think these interfaces are OK

**Comment by fverdugo** [comment]
Done!

I have only implemented the version of `reffe` + `conformity` (not the version on `fetype`). I think, this is enough for the moment.

I have also implemented the `constraint = :zeromean` option. To do so-I have slightly changed the interface of `solve!` in the `FESolvers`, see   `NEWS.md` for further details.

Don via PR #102 

closing issue
