### ISSUE TITLE
non-deterministic matrix assembly for multiple domains

### ISSUE THREAD

**Issue by stevengj** [gridap/Gridap.jl#1002]
@mochen4 pointed out via email that Gridap's matrix assembly yields non-deterministic roundoff errors, e.g. the matrices from [this tutorial](https://gridap.github.io/Tutorials/dev/pages/t018_TopOptEMFocus/) change on the order of machine precision from run to run.   This makes debugging harder, and is especially inconvenient if the Gridap outputs are fed into some calculation exhibiting chaos or instability (e.g. we noticed it in optimization problems exhibiting spontaneous symmetry breaking, which converge to a local optimum that is sensitively affected by tiny discrepancies).

@fverdugo wrote to explain:

> we use a `Dict` to store the contributions of several domains to an integral. This can definitely be a cause of operations being done in non deterministic order.

and indeed the issue arises in problems involving multiple domains.   Essentially, `Dict` iteration depends on the hashing algorithm, and Julia's [default hashing algorithm](https://github.com/JuliaLang/julia/blob/8423426213f58c786de33b10ab41d90fe89afe04/base/hashing.jl#L38) for a `struct` uses the pointer address (`objectid`), which is effectively non-deterministic.   Changing iteration order can change the floating-point roundoff errors of a sum.

The solution is, in principle, simple — just implement a custom `hash` function (and `==`) that is deterministic for any object that is used as a `Dict` key.     Question: which data structures in Gridap need this?

**Comment by JordiManyer** [comment]
This would only affect the `DomainContribution` structure, which stores a dictionary of `Triangulation` objects. So the hash would be on the triangulations.

**Comment by fverdugo** [comment]
Another option is to use another dict type that preserves insertion order, e.g.:

https://juliacollections.github.io/DataStructures.jl/stable/ordered_containers/#OrderedDicts-and-OrderedSets-1

@mochen4 can you try to use an OrderedDict here?

https://github.com/gridap/Gridap.jl/blob/532e8def1435ee0d0fac6eb846df178d5393ec5b/src/CellData/DomainContributions.jl#L5

**Comment by stevengj** [comment]
Using an `OrderedDict` makes a lot of sense here.  

Otherwise, you'd have to switch to an ordinary `Dict` (not `IdDict`, which *always* hashes based on the pointer), and implement a `hash` for the triangulation, which would make lookup more expensive (because it would have to look at the whole triangulation to hash it).  Does performance matter here?   Of course, a simple workaround would be to store a hash of the `Triangulation` object in the object itself, so that you'd only pay the hash cost once when the object is constructed.

**Comment by mochen4** [comment]
> @mochen4 can you try to use an OrderedDict here?
> 
> https://github.com/gridap/Gridap.jl/blob/532e8def1435ee0d0fac6eb846df178d5393ec5b/src/CellData/DomainContributions.jl#L5

Using ``OrderedDict`` fixes the issue for me.

**Comment by stevengj** [comment]
@mochen4, can you make a pull request that makes this 1-line change (also changing the Project.toml to add the DataStructures dependency)?

**Comment by mochen4** [comment]
> @mochen4, can you make a pull request that makes this 1-line change (also changing the Project.toml to add the DataStructures dependency)?

The DataStructures dependency is already specified in Project.toml
https://github.com/gridap/Gridap.jl/blob/632d695774ca81b77c8855e6fed63eb88a96aa6e/Project.toml#L11

So I simply added ``using dataStrutures`` in DomainContributions.jl
