### ISSUE TITLE
BLAS/LAPACK not loading in Gridap

### ISSUE THREAD

**Issue by vikramsondergaard** [gridap/Gridap.jl#1019]
Hi all,

I'm new to Gridap, and I'm trying to familiarise myself with the software by going through the tutorials. I'm currently working through [Tutorial 2: Code validation](https://gridap.github.io/Tutorials/dev/pages/t002_validation/). I'm up to the part of the tutorial where we generate an approximation of the Poisson problem ("[FE Approximation](https://gridap.github.io/Tutorials/dev/pages/t002_validation/#FE-approximation-1)"), but I'm running into an error at the line

```julia
uh = solve(op)
```

## The error

The error I get is the following:

```
Error: no BLAS/LAPACK library loaded!
Error: no BLAS/LAPACK library loaded!
Error: no BLAS/LAPACK library loaded!
Error: no BLAS/LAPACK library loaded!
Error: no BLAS/LAPACK library loaded!
Error: no BLAS/LAPACK library loaded!
Error: no BLAS/LAPACK library loaded!
Error: no BLAS/LAPACK library loaded!
Error: no BLAS/LAPACK library loaded!
Error: no BLAS/LAPACK library loaded!
Error: no BLAS/LAPACK library loaded!
Error: no BLAS/LAPACK library loaded!
Error: no BLAS/LAPACK library loaded!
Error: no BLAS/LAPACK library loaded!
Error: no BLAS/LAPACK library loaded!
SingleFieldFEFunction():
 num_cells: 16
 DomainStyle: ReferenceDomain()
 Triangulation: BodyFittedTriangulation()
 Triangulation id: 10499208658425072622
```

There is also some output at the end which seems promising, but the errors don't. The error doesn't provide any stack trace, but I've used my debugger to get a stack trace:

```
Gridap/src/FESpaces/FESolvers.jl:121
└ Gridap/src/Algebra/LinearSolvers.jl:206
   └ Gridap/src/Algebra/LinearSolvers.jl:262
    └ SparseArrays.jl/solvers/umfpack.jl:378
       └ SparseArrays.jl/solvers/umfpack.jl:622
```

So, from what I can see, the error arises when Gridap uses `umfpack.jl` to handle a call to `lu()` in line 262 of `LinearSolvers.jl` in Gridap.

## My configuration

I am running a 2017 Macbook Air (Intel) with MacOS Monterey 12.6.5. My Julia version is 1.10.4. Here is the output when I run `BLAS.get_config()` after running my Julia code:

```
LinearAlgebra.BLAS.LBTConfig
Libraries: 
├ [ LP64] libopenblasp-r0.3.27.dylib
├ [ LP64] libopenblas.0.3.24.dylib
└ [ LP64] libmkl_rt.2.dylib
```

I'm aware that there have recently been issues with MKL 2024 for Intel Macs, so I've followed the steps in the [MKL.jl readme](https://github.com/JuliaLinearAlgebra/MKL.jl?tab=readme-ov-file#note-mkl-on-intel-macs). I also have no problems calling `lu()` on the Julia REPL after running my tutorial code.

## The code (all of it)

If it helps, here is my entire file:

```julia
using Gridap

# Configure BLAS/LAPACK setup 
using LinearAlgebra, MKL_jll, OpenBLAS32_jll
BLAS.set_num_threads(1)
BLAS.lbt_forward(OpenBLAS32_jll.libopenblas_path; verbose = true)
BLAS.lbt_forward(MKL_jll.libmkl_rt_path; verbose = true)
BLAS.get_config()

# Define the manufactured solution, u(x) = x₁ + x₂ and
# the source term f associated with it, namely
# f ≐ -∆(x₁ + x₂) = 0.
u(x) = x[1] + x[2]
f(x) = 0

# We also need to define the gradient of u since we will
# compute the H¹ error norm later. In that case, the
# gradient is defined as
∇u(x) = VectorValue(1, 1)

# Note that we have used the constructor `VectorValue`
# to build the vector that represents the gradient.
# However, we still need a final trick. We need to tell
# the Gridap library that the gradient function `u` is
# available in the function `∇u`. At the moment `u` and
# `∇u` are two standard Julia functions without any
# connection between them. This is done by adding an
# extra method to the function `gradient` (aka `∇`)
# defined in Gridap:
import Gridap: ∇
∇(::typeof(u)) = ∇u

# Now, it is possible to recover the function `∇u` from
# the function `u` as `∇(u)`. You can check that the
# following expression evaluates to true:
∇(u) == ∇u

# In order to discretise the geometry of the unit
# square, we use the Cartesian mesh generator available
# in Gridap: 
domain = (0, 1, 0, 1)
partition = (4, 4)
model = CartesianDiscreteModel(domain, partition)

# The type `CartesianDiscreteModel` is a concrete type
# inherited from `DiscreteModel`, which is specifically
# designed for building Cartesian meshes. The
# `CartesianDiscreteModel` constructor takes a tuple
# containing limits of the box we want to discretise,
# plus a tuple with the number of cells to create in
# each direction (here 4 by 4 cells). Note that the
# `CartesianDiscreteModel` is implemented for arbitrary
# dimensions. For instance, the following builds a
# `CartesianDiscreteModel` for the unit cube (0, 1)³
# with 4 cells per direction:
domain3d = (0, 1, 0, 1, 0, 1)
partition3d = (4, 4, 4)
model3d = CartesianDiscreteModel(domain3d, partition3d)

# Let's return to the 2D `CartesianDiscreteModel` that
# we've already constructed. We can inspect it by
# writing it into vtk format. Note that you can also
# print a 3D model, but not a 4D one.
writevtk(model, "model")

# We compute a FE approximation of the Poisson problem
# above by following the steps detailed in the previous
# tutorial:
order = 1
reffe = ReferenceFE(lagrangian, Float64, order)
V0 = TestFESpace(model, reffe, conformity = :H1,
    dirichlet_tags = "boundary")
U = TrialFESpace(V0, u)

degree = 2
Ω = Triangulation(model)
dΩ = Measure(Ω, degree)

a(u, v) = ∫(∇(v) ⊙ ∇(u)) * dΩ
b(v)    = ∫(v * f) * dΩ

op = AffineFEOperator(a, b, U, V0)

uh = solve(op)
```

**Comment by JordiManyer** [comment]
This doesn't seem a Gridap issue, rather a Julia+Mac issue. I don't think this is the place to ask.

**Comment by vikramsondergaard** [comment]
No worries, sorry to bother!

**Comment by JordiManyer** [comment]
Yeah I'm with @amartinhuertas on this. I would say you should try getting support from the SparseArrays.jl people.

**Comment by vikramsondergaard** [comment]
Thanks @amartinhuertas and @JordiManyer for all your help. Yes, `lu()` works fine for a `SparseMatrixCSC` instances. For example, the following Julia code worked after running the tutorial code shown above:
```
julia> A = Matrix(1.0I, 3, 3)
3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

julia> sparseA = sparse(A)
3×3 SparseMatrixCSC{Float64, Int64} with 3 stored entries:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0

julia> lu(sparseA)
SparseArrays.UMFPACK.UmfpackLU{Float64, Int64}
L factor:
3×3 SparseMatrixCSC{Float64, Int64} with 3 stored entries:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0
U factor:
3×3 SparseMatrixCSC{Float64, Int64} with 3 stored entries:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0
```
I also did this with MKL disabled. Here is the result of calling `BLAS.get_config()`:
```
LinearAlgebra.BLAS.LBTConfig
Libraries: 
└ [ LP64] libopenblasp-r0.3.27.dylib
```
(I'm aware that this isn't the right place to talk about this, so maybe I'll take this discussion over to the `SparseArrays.jl` folks after this, as you suggested @JordiManyer .)

**Comment by amartinhuertas** [comment]
> Yes, lu() works fine for a SparseMatrixCSC instances.

Can you try to solve a system with the LU factors returned from `lu(sparseA)` ? That is:

```
fact=lu(sparseA)
fact\rand(3)
```

**Comment by vikramsondergaard** [comment]
Yep, this works too.
```
julia> fact = lu(sparseA)
SparseArrays.UMFPACK.UmfpackLU{Float64, Int64}
L factor:
3×3 SparseMatrixCSC{Float64, Int64} with 3 stored entries:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0
U factor:
3×3 SparseMatrixCSC{Float64, Int64} with 3 stored entries:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0

julia> fact\rand(3)
3-element Vector{Float64}:
 0.7380533443485572
 0.4067661038585547
 0.08964093533105355
```

**Comment by amartinhuertas** [comment]
Ok. 

Why are we assuming that a diagonal (sparse) matrix is going to trigger the same BLAS/LAPACK calls from umfpack than the actual matrix you are trying to factorize when doing Gridap's `solve(op)` ? 

I would try to extract the sparse matrix out of `op`, and then call `lu` and `\`. To extract the sparse matrix, you can write `op.op.matrix`. If this reproduces the problem, then you may extract the matrix in a file, and read it from a mwe to be submitted to SparseArrays.jl developers.

**Comment by vikramsondergaard** [comment]
This reproduces the problem! Thank you so much @amartinhuertas . Sending off a mwe to SparseArrays.jl now.

**Comment by vikramsondergaard** [comment]
Fwiw, this has been closed now. I had installed `julia` via Homebrew instead of via `juliaup`, causing the issues.
