### ISSUE TITLE
MINI Elements

### ISSUE THREAD

**Issue by hgpeterson** [gridap/Gridap.jl#1022]
Hello,

I'm wondering if there is a way to use [MINI elements](https://doi.org/10.1007/BF02576171) in Gridap to solve Stokes problems? If not, how difficult would it be to add them to the codebase?

Thank you.

**Comment by amartinhuertas** [comment]
Hi @hgpeterson. 

MINI elements are not currently implemented in Gridap, neither for triangles nor quadrilaterals. However, Gridap has an extensible, mathematically-supported software architecture.  Thus, while it may take some effort to add them to the current suite of FEs, I think it should be doable.  If you are interested to add them, I could provide some support. 

Let me know your thoughts. 

@amartinhuertas

**Comment by hgpeterson** [comment]
Hi @amartinhuertas,

Thanks for the quick reply! Depending on how things go with the scalability of my research problem with P2-P1 elements, I may want to work on this with you. I will let you know if it gets to that point!

Henry
