### ISSUE TITLE
quadrature order keyword preferibly degree, exactness, or precission

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#106]
quadrature order keyword preferibly degree, exactness, or precision

**Comment by fverdugo** [comment]
degree!

**Comment by fverdugo** [comment]
Renamed `order` to `degree` in `CellQuadrature` constructor.

BTW, I have also renamed `JuliaNLSolver` to `NLSolver`.

The old variants are still usable, but one gets a deprecation warning.

closing issue
