### ISSUE TITLE
Mssing div term for functions

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#107]
```
u1(x) = VectorValue(x[1], -1*x[2])

∇u1(x) = TensorValue(1.0,0.0,0.0,1.0)

∇(::typeof(u1)) = ∇u1

inner(q,div(u1))
```
returns an error, not implement yet

**Comment by fverdugo** [comment]
Implementing this is simple, with something like
```julia
using Gridap
import Base: div
using LinearAlgebra: tr # not sure if needed

function div(u::Function)
∇u = ∇(u)
(x) -> tr(∇u(x))
end
```

**Comment by fverdugo** [comment]
The adopted solution is to add a new method to the `divergence` function. See this example:
https://github.com/gridap/Gridap.jl/blob/master/test/GridapTests/DarcyTests.jl

Closing issue.
