### ISSUE TITLE
Operations between CellField and CellBasis

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#116]
I have implemented the Piola Map, which is a `CellField` that given an array of cell points provides a `CellArray` with its cellwise evaluation on these points.
Now, the `CellBasis` for this problem is at every point the multiplication of the Piola `map` and the `FEBasis`.
We must develop operations between `CellMap` and `CellBasis` in order to easily implement such operation.

**Comment by fverdugo** [comment]
I am aware of this problem.

Now operations between `CellBasis` and `CellField` objects are fixed at the `FEBasis` level using the `cellnewaxis` function. See, e.g., 

https://github.com/gridap/Gridap.jl/blob/01cf074df49eee0a6f161bf13eb8cd8326b3365d/src/FESpaces/FEBases.jl#L43

However, it would be nicer to fix them at the `CellBasis` level. Moreover, It would be nice to fix them without using the `cellnewaxis` function (which introduces a new node in the operation tree).

**Comment by fverdugo** [comment]
These problems are fixed in v0.7.0. Closing issue.
