### ISSUE TITLE
Add travis jobs to test gridap plugins

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#124]
In gridap, it would be nice to add some extra Travis jobs to test plugin that are downstream from Gridap (e.g. GridapGmsh)

This will be useful to check if we introduce changes in Gridap that break the plugins. If the plugins only use the public API of Gridap, Braking changes should be close to zero, but it is better to check them.

Some requirements:

- these jobs only need to be run in master (for the moment in new_master)

- the external dependencies of the plugin (e.g. gmsh) should only be installed in the corresponding job, not in all jobs in Gridap)

For the moment, we can start with GridapGmsh that already has a branch new_master that is based on the branch new_master of Gridap

**Comment by victorsndvg** [comment]
Here in this comment I'm going to gather some useful links. This message will probably be affected for further edits.

I think the right way to go is to notify new changes from Gridap project to trigger some actions (CI process) to plugins.

As far as I know right now, we can take advantage of:
  - Github actions
  - Travis triggers
To solve this problem.

Some links:
  - [github actions](https://help.github.com/en/actions)
  - [Travis triggers](https://docs.travis-ci.com/user/triggering-builds)
  - [Travis triggers (shell script)](https://github.com/mernst/plume-lib/blob/master/bin/trigger-travis.sh), [Travis triggers (shell script project)](https://github.com/plume-lib/trigger-travis/)

**Comment by fverdugo** [comment]
> I think the right way to go is to notify new changes from Gridap project to trigger some actions (CI process) to plugins.

Triggering the CI pipeline of the plugins sounds like a good idea. However, remember that we want to run the plugins for a specific version of Gridap. Now, the plugins run for the newest registered version of Gridap compatible with the plugin as stated in the Project.toml of the pluging.

**Comment by fverdugo** [comment]
Perhaps, triggering the CI pipline of the plugin is not be best approach...

We want to open a PR in Gridap against master, see if all checks pass, and if so, accept the PR. If we trigger the CI of the plugin and some tests fail, will the failure be visible from the PR in Gridap?

**Comment by fverdugo** [comment]
Dear @victorsndvg 

In the process of factorizing the travis CI scripts, could you configure the tests with julia 1.3.x instead of 1.2.x ?

Thanks!

**Comment by victorsndvg** [comment]
:+1:

**Comment by fverdugo** [comment]
I closed via #141
