### ISSUE TITLE
Add SparseMatricesCSR code into Gridap

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#126]
At this point, we can already add all the code of SparseMatricesCSR into Gridap.

The code should be included in the sub-module `Gridap.Algebra`

Note that I have already added some of these functions in the file
https://github.com/gridap/Gridap.jl/blob/new_master/src/new/Algebra/SparseMatrices.jl

It's fair that @victorsndvg adds this code so that his contribution on this part gets reflected in the commit history.

**Comment by victorsndvg** [comment]
I copy the current state of SparseMatricesCSR plugin into Gridap with minor modifications. It include also the tests.

This was was done in commit f1bf963 resulting in this PR  https://github.com/gridap/Gridap.jl/pull/127

It's ok for you? is this what you was expecting?

**Comment by fverdugo** [comment]
Before closing this issue, we need 3 more things:

1. A function that fills with a given value `v` an existing sparse matrix A: `fill_entries!(A,v)` It will rewrite the data array with the given value `v`

2. Please, remove the `function` key-word in the files you have recently introduced in the Algebra module

3. Delete all branches that can be deleted

**Comment by victorsndvg** [comment]
PR #131  (commit 435ad85) solves your latest comment to close the issue.

After merging I will delete the pending branch

**Comment by victorsndvg** [comment]
Again, i did the pull request against the wrong branch. Now, PR #132 contains the correct PR from `update/SparseMatricesCSR` to `new_master`

**Comment by fverdugo** [comment]
Closed via PR #132
