### ISSUE TITLE
Manufactured solutions for Neumann boundaries

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#135]
I would like to know whether we are now ready for creating tests with manufactured solutions with Neumann boundaries. The problem I foresee is the definition of the fluxes on the boundary given the exact solution analytical expression, which must be combined with the outwards normal on that boundary. Please note that we do not have an expression of the fluxes but the solution itself since fluxes are geometry dependent. @fverdugo have you created any test doing that? Do you think is that possible?

**Comment by fverdugo** [comment]
When I was implementing integration on boundaries, I had in mind the particular case you are commenting. Thus, it should work (except for a bug, of course).

For the test function in DG computations it is working, see 
https://github.com/gridap/Gridap.jl/blob/ab94dbbd1a0904395c969eaf473ee5ff5feadfe6/test/FESpacesTests/DGFEOperatorsTests.jl#L44

Could you provide a small reproducer?

**Comment by santiagobadia** [comment]
You want to implement a term like
```julia
u(x) = VectorValue(x[1], -x[2])
∇u(x) = TensorValue(1.0,0.0,0.0,-1.0)
ud(x) = u(x)
∇ud(x) = ∇u(x)
# Here the creation of geometry, FE spaces, etc, e.g.
n = 4
model = CartesianDiscreteModel(domain=(0.0,1.0,0.0,1.0), partition=(n,n))
btrian = BoundaryTriangulation(model)
bquad = CellQuadrature(btrian,degree=2*order)
nb = NormalVector(btrian)
fespace = FESpace( reffe=:Lagrangian, conformity=:H1, valuetype=VectorValue{2,Float64},
  model=model, order=order)
Vh = TestFESpace(fespace)
function B_∂Ω(v)
inner(v,∇ud*nb)
end
t_∂Ω = FESource(B_∂Ω,btrian,bquad)
```

**Comment by santiagobadia** [comment]
The point is that you want to operate with the normal vector and exact solution, not normal vector with test function, which is what is being used now in tutorials, etc

In some cases, you can re-write it with external product of v and normal vector, etc, but I don't think it is acceptable.

**Comment by fverdugo** [comment]
Yes, your example does not work since you need some previous steps:

```julia
using Gridap

u(x) = VectorValue(x[1], -x[2])
∇u(x) = TensorValue(1.0,0.0,0.0,-1.0)
ud(x) = u(x)
∇ud(x) = ∇u(x)
# Here the creation of geometry, FE spaces, etc, e.g.
n = 4
model = CartesianDiscreteModel(domain=(0.0,1.0,0.0,1.0), partition=(n,n))
btrian = BoundaryTriangulation(model)
order = 1
bquad = CellQuadrature(btrian,degree=2*order)
nb = NormalVector(btrian)
fespace = FESpace( reffe=:Lagrangian, conformity=:H1, valuetype=VectorValue{2,Float64},
  model=model, order=order)
Vh = TestFESpace(fespace)

# Create a cell field aligned with the volume mesh
trian = Triangulation(model)
∇ud_cell_field = compose(∇ud,CellGeomap(trian))

# Restrict to the boundary triangulation
# The result is a cell field aligned with the boundary triangulation
∇ud_b = restrict(∇ud_cell_field,btrian)

# Now, we can compute the flux since ∇ud_b and nb are aligned
flux = ∇ud_b*nb

# You can visualize the flux
writevtk(btrian,"btrian",cellfields=["flux"=>flux])

# Now this should work
function B_∂Ω(v)
inner(v,flux)
end
t_∂Ω = FESource(B_∂Ω,btrian,bquad)

```

We can introduce some syntax sugar in order to hide all these steps, but I would do this only in `new_master`.

**Comment by santiagobadia** [comment]
I think it is all about cell values vs expressions (conceptually in the physical space), which cannot be mixed and introduce some rigidity.

The missing part that I didn't remember is 
```julia
∇ud_cell_field = compose(∇ud,CellGeomap(trian))
```

**Comment by fverdugo** [comment]
Yes, in `new_master` I am trying to handle this more consistently

In your example, you could also create the restriction to the boundary directly, by using the boundary mesh :

```julia
∇ud_b = compose(∇ud,CellGeomap(btrian))
```
