### ISSUE TITLE
GridapTypes not printed correclty

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#142]
We still have the default verbose printing for `GridapType` objects

There is a `Base.` missing before `show` on line. This yould be the problem
https://github.com/gridap/Gridap.jl/blob/2a5681883d86a8a917b9d62f849db1631cfc1064/src/new/Helpers/Helpers.jl#L91

@victorsndvg 

Can you fix this and add a small test that checks that objects are printed as we expect?

**Comment by victorsndvg** [comment]
Solved in commit 9fcceac. PR #145

**Comment by fverdugo** [comment]
Closed via #145
