### ISSUE TITLE
Triggering Plugin tests only on demand?

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#143]
The plugin tests is a nice feature that we want to have "for safety reasons", but it adds some extra time to the all CI pipeline.

@victorsndvg do you think it is possible to trigger these tests only on demand? For example, when writing `[extra-ci]` in the commit message.

With this, we could trigger the tests only before releases in order to check that everything is ok, and save some CI for changes in a more experimental state of the project.

**Comment by victorsndvg** [comment]
Is possible to filter commits by commit message (https://docs.travis-ci.com/user/conditions-v1) and also to apply this filter to conditionally run a particular stage (https://docs.travis-ci.com/user/conditional-builds-stages-jobs). Regular expressions are parsed using Ruby regex (https://ruby-doc.org/core-2.6/Regexp.html).

Finally, as we agreed on gitter, the word to activate the PluginsTest CI stage is  `[full-ci]`. This must be at the beginning of the commit message, with no blanks before.

This work was done in commit d4afd22. Acepting PR #144 should close this issue

**Comment by fverdugo** [comment]
Closed via PR #144
