### ISSUE TITLE
Order test and trial functions in bilinear forms inconsistent for linear and nonlinear problems

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#146]
I find that is not natural and prone to errors to switch the order of the trial and test functions when one writes the [bilinear form of a linear problem](https://github.com/gridap/Tutorials/blob/8bac646e9a00b908df1705c4afd8660967fc6d5e/src/t003_elasticity.jl#L95) and when defining the [residual of a nonlinear problem](https://github.com/gridap/Tutorials/blob/8bac646e9a00b908df1705c4afd8660967fc6d5e/src/t004_hyperelasticity.jl#L55).

We should make it consistent. Similar comment for Jacobian.

**Comment by fverdugo** [comment]
@santiagobadia, now it is a good moment to make a decision. I am about to implement this is the new version.

I would take the test function always in the first argument:

```julia
# v: test function
# u: trial function
# du: linearization direction
a(v,u)
r(v,u)
j(v,du,u) # Option A
j(v,u,du) # Option B
```
For the residual what do you prefer? A or B? Visually, I like more B. Conceptually, perhaps A.

By the way, with the new version it will be possible to write `a(v,u)=v*u` instead of `a(v,u)=inner(v,u)`, when `*` returns a scalar (i.e., for scalar and vectors). Moreover, these products will be truly commutative: `a(v,u)=v*u` and `a(v,u)=u*v` will be equivalent (which is what one would expect). Now, if one swaps the operands, one gets the matrix transposed which is prone to errors.

**Comment by santiagobadia** [comment]
For `a` and `r` it is OK as you propose. For the Jacobian, I like A more than B because `u` has a different nature than `du` and `v`. If I could I would write (but not possible in Julia)
```julia
j(u;v,du) # u is the linearisation point
``` 
or at least
```julia
j(u,v,du)
```

**Comment by fverdugo** [comment]
Do you not find confusing `r(v,u)` vs `j(u,v,du)` ?

In fact, we write now `r(u,v)` in order to emulate `r(u;v)` as you have said for the jacobian

**Comment by fverdugo** [comment]
From a aesthetic point of view I would prefer:

```julia
a(v,u)
r(v,u)
j(v,u,du)
```
more than:


```julia
a(v,u)
r(v,u)
j(u,v,du)
```
I also find the current solution acceptable:

```julia
a(v,u)
r(u,v)
j(u,v,du)
```

**Comment by fverdugo** [comment]
I also find acceptable:

```julia
a(v,u)
r(v,u)
j(v,du,u)
```

**Comment by fverdugo** [comment]
> If I could I would write (but not possible in Julia)
> 
> ```julia
> j(u;v,du) # u is the linearisation point
> ```

In fact, this is possible in julia.

we could adopt

```julia
l(v)
a(v,u)
r(u;v)
j(u;v,du)
```

If you like

**Comment by santiagobadia** [comment]
The standard way to write all these terms in the finite element community are
```julia
a(u,v)
j(w,u,v) or j(u,du,v)
r(u,v)
```
I understand why you want to swap `u` and `v`, i.e., it is more natural when writing the problem in matrix form, first entry column index second row index. But we can agree that this is not the standard usage. I don't have an strong opinion about it. It is OK for the to put the test function first.

But using exactly the same reasoning, I consider that the jacobian must have the first entry the nonlinear one, whereas the second and third the linear ones. So, I consider that the two options should be
```julia
a(u,v)
j(w,du,v)
r(u,v)
```
or
```julia
a(v,u)
j(w,v,du)
r(v,u)
```
and in general, I would not use `u` for the nonlinear term to avoid confusion with the linear case. They are very different things. In one case a linearisation point and in the other case the trial space.

**Comment by fverdugo** [comment]
Consider the affine problem defined by the bilinear and linear forms `a(v,u)`, `l(v)`

What about this way to define the associated residual and jacobian?

```julia
r(u) = (v) -> a(v,u) - l(v)
j(u) = (v,du) -> a(v,du)
```

`r` is a function that when evaluated at `u`, returns a function that can be evaluated at the test function `v`, that is, one can call `r(u)(v)`

`j` is a function that when evaluated at `u` returns a function that can be evaluated at `v,du`. That is, one can call `j(u)(v,du)`

This is a little bit more lengthy that our current approach, but it is almost identical to the math definition of residual and jacobian. 

Do you think it is worth considering?  Perhaps yes...

**Comment by fverdugo** [comment]
For the Navier Stokes tutorial (https://github.com/gridap/Tutorials/blob/master/src/t008_inc_navier_stokes.jl), the residual and jacobian, would be defined as

```julia
function res(x)
  (y) ->
    u, p = x
    v, q = y
    a(y,x) + c(v,u)
end

function jac(x)
  (y,dx) ->
    u, p = x
    v, q = y
    du, dp = dx
    a(y,dx)+ dc(v,du,u)
end
```

**Comment by santiagobadia** [comment]
I think it is mathematically sound but it probably complicates things a little bit.

I am not even sure about the order of the test and trial functions. The use of `a(u,v)` is overwhelmingly more common than `a(v,u)` and taking into account that the matrix part is not something the user has to deal with, I would stick to the most common notation. And it is just about notation, there is not one better than the other. On the other hand, when you write a weak form you state it as: find `u : a(u,v) = l(v) for all v` which is probavly nicer than `u : a(v,u) = l(v) for all v`. I guess this is the reason for such ordering. So, I would do the most standard thing, i.e.,
```julia
a(u,v)
j(w,u,v) or j(u,du,v) # always nonlinear input first, and linear ones at the end
r(u,v)
```
Is there any problem with this one?

**Comment by santiagobadia** [comment]
Hi @fverdugo 

Can we consider my suggestion to put the order of the test functions as 99.99% of the people in the FEM community? I can be in charge of that... I would create a branch and see whether I survive or not. Conceptually, it shouldn't be that difficult. 

I have been presenting Gridap to many people these days, and many people complain about this.

**Comment by fverdugo** [comment]
We can introduce this in the next release Gridap v0.8. 

At the end which will be the order? this one?

```julia
a(u,v) # bilinear form
l(v) # linear form
j(u,v,du) # jacobian
r(u,v) # residual
```

We also will need to change the order in functions taking test and trial spaces as arguments to be consistent, right?. E.g. from `AffineFEOperator(V,U,...)` to `AffineFEOperator(U,V,...)`

If you can do the work in a separate branch would be perfect (make sure that you start from the latest master version). Then, I can take a look before merging.

**Comment by santiagobadia** [comment]
It would be

```
a(u,v) # bilinear form
l(v) # linear form
j(u,du,v) # jacobian
r(u,v) # residual
```

**Comment by santiagobadia** [comment]
This work has been done in ec743031532d3d0b5e3a4d0ebfe2b72eddbbb571 and 6f1b329d49858e06e2dce6000fc2a2b3cbe8f881

I close the issue
