### ISSUE TITLE
Documentation stage at travis-CI is missing.

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#152]
Last builds do not include the Documentation stage, see for instance
https://travis-ci.com/gridap/Gridap.jl/builds/145108581

@victorsndvg can you investigate, why?

**Comment by victorsndvg** [comment]
it seems that `matrix` and `jobs` keywords/sections in `.travis.yml` are exclusive, only one can be used. I don't know why it was working before ...

This is already solved in commit bb06f82  and PR #156

**Comment by fverdugo** [comment]
Perfect!

closed via PR #156
