### ISSUE TITLE
Mesh by restriction

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#158]
Hi @fverdugo 

We need for the MRI project a mesh defined as a structured mesh (pixel mesh) plus a filter that tells whether a cell is active or inactive. The resulting mesh will be the restriction of the original mesh to active cells. I would define a function like `ModelByRestriction(model,filter)` where `filter` is a `CellArray` of `Boolean`. I will need methods that extract the boundary mesh, etc.

For our problems of interest, no Dirichlet data will be needed, thus no boundary flags will be needed.

I would like to know if you have any suggestion/concern about how to proceed with this development. Conceptually, it should not be that difficult.

**Comment by santiagobadia** [comment]
I see there is a `GridPortion` that generates the restriction with an array of active cells. It is what we need. However, I do need a model not a grid for the `FESpace`.

Now I have to decide how to define the model restriction.

**Comment by fverdugo** [comment]
Actually, I want to change `GridPortion` a little bit, but yes, it's related with what you want.

The key here is that there are several sets that need to be restricted. My plan is to introduce the following types:

-  `TriangulationPortion`:  It should create a new numbering for the active cells. It's natural: a Triangulation only has a global numeration for the cells.

- `GridPortion`: It should create a new numbering for the active cells and for the active nodes.  It's natural: since a Grid has a global numeration both for the cells and nodes. Remark: at the moment `GridPortion` only restricts the cells, which is not very natural. This is what I want to change.

- `DiscreteModelPortion`:  It should create a new numbering for the active cells, for the active nodes, and for the active VEFs. This is because the model handles a global numeration for all these objects.

Implementing `TriangulationPortion` and `GridPortion` is straight forward. With the model, I have to think how to proceed.

**Comment by santiagobadia** [comment]
Taking into account that we do not need labels for the application we have in mind, do you think we can create a temporary `DiscreteModelPortion` somehow easily with the `GridPortion`? I would need something (not definite) in a short time. We can talk on Thursday.

**Comment by fverdugo** [comment]
With the new version:

1. Restrict your grid (once the new GridPortion implementation is available).
2. from the restricted grid, extract the corresponding grid topology (this is already implemented)
3. From the grid topology, create an empty FaceLabeling (straight forward)
4. from the restricted grid, its grid topology and the face labeling, create a model (this is already implemented)

Once the new GridPortion implementation is available, it should be straight forward to do all these steps.

**Comment by santiagobadia** [comment]
Hi Francesc,

Just to check, it seems that GridPortion is implemented in the new version of Gridap and that you have tests for it.

With regard to step 2, I am not sure how to do it. I have tried
`labels = FaceLabeling([0,0,0])`
but then I have some errors related to problems with void collections. Let me know if you have a better idea how to do it.

**Comment by fverdugo** [comment]
Solved in  PR #172. I think we can close the issue.

Now, you can do:

```julia
using Test
using Gridap
import Gridap: ∇
using Gridap.Arrays
using Gridap.Geometry

# Create a model with the cells whose center is in a sphere

domain = (-1,1,-1,1,-1,1)
partition = (20,20,20)
background_grid = CartesianGrid(domain,partition)

const R = 0.7

function is_in(coords)
  n = length(coords)
  x = (1/n)*sum(coords)
  d = x[1]^2 + x[2]^2 + x[3]^2 - R^2
  d < 0
end

oldcell_to_coods = get_cell_coordinates(background_grid)
cell_to_oldcell = findall(collect1d(apply(is_in,oldcell_to_coods)))

grid = GridPortion(background_grid,cell_to_oldcell)
topo = GridTopology(grid)
labels = FaceLabeling(topo)
model = DiscreteModel(grid,topo,labels)

# Poisson solver as always

u(x) = x[1]^2 + x[2]
∇u(x) = VectorValue( 2*x[1], one(x[2]), zero(x[1]) )
Δu(x) = 2
f(x) = - Δu(x)
∇(::typeof(u)) = ∇u

order = 2

V = TestFESpace(
 model=model,
 order=order,
 reffe=:Lagrangian,
 labels=labels,
 valuetype=Float64,
 dirichlet_tags="boundary")

U = TrialFESpace(V,u)

trian = get_triangulation(model)
degree = order
quad = CellQuadrature(trian,degree)

a(v,u) = inner(∇(v),∇(u))
l(v) = v*f
t_Ω = AffineFETerm(a,l,trian,quad)

op = AffineFEOperator(V,U,t_Ω)

uh = solve(op)
  
e = u - uh

l2(v) = v*v
h1(v) = v*v + inner(∇(v),∇(v))

el2 = sqrt(sum( integrate(l2(e),trian,quad) ))
eh1 = sqrt(sum( integrate(h1(e),trian,quad) ))

tol = 1.0e-9
@test el2 < tol
@test eh1 < tol

writevtk(trian,"trian",order=order,cellfields=["uh"=>uh])

```

![sol](https://user-images.githubusercontent.com/48508177/73525983-87fea700-4410-11ea-94da-33604c387372.png)

**Comment by fverdugo** [comment]
I have implemented a new concrete FESpace , named `CLagrangianFESpace` (it was already in the old version).

This space is for the particular case of Lagrangian reffes with the same interpolation order as the underlying grid. The cell dof ids are generated by using the cell node ids of the grid (for scalar-valued interpolations both coincide).

The nice thing about this space is that it provides the relation between nodes/components/dofs, which can be useful in some scenarios (like for the problem of MRI images)

This is the public type signature:
```julia
struct CLagrangianFESpace{S} <: SingleFieldFESpace
  grid::Grid
  dof_to_node::Vector{Int}
  dof_to_comp::Vector{Int8}
  node_and_comp_to_dof::Vector{S}
end
```

Usage in the FE computation above:

```julia
using Test
using Gridap
import Gridap: ∇
using Gridap.Arrays
using Gridap.Geometry
using Gridap.FESpaces

# Create a model with the cells whose center is in a sphere

domain = (-1,1,-1,1,-1,1)
partition = (20,20,20)
background_grid = CartesianGrid(domain,partition)

const R = 0.7

function is_in(coords)
  n = length(coords)
  x = (1/n)*sum(coords)
  d = x[1]^2 + x[2]^2 + x[3]^2 - R^2
  d < 0
end

oldcell_to_coods = get_cell_coordinates(background_grid)
cell_to_oldcell = findall(collect1d(apply(is_in,oldcell_to_coods)))

grid = GridPortion(background_grid,cell_to_oldcell)
topo = GridTopology(grid)
labels = FaceLabeling(topo)
model = DiscreteModel(grid,topo,labels)

# Poisson solver with Nitsche BCs

const h = (domain[2]-domain[1]) / partition[1]
const γ = 10

u(x) = x[1] + x[2]
∇u(x) = VectorValue( one(x[1]), one(x[2]), zero(x[1]) )
Δu(x) = 0
f(x) = - Δu(x)
∇(::typeof(u)) = ∇u

V = CLagrangianFESpace(Float64,grid)

U = TrialFESpace(V)

trian = get_triangulation(model)
degree = 1
quad = CellQuadrature(trian,degree)

btrian = BoundaryTriangulation(model)
bdegree = 2
bquad = CellQuadrature(btrian,bdegree)
bn = get_normal_vector(btrian)

a(v,u) = inner(∇(v),∇(u))
l(v) = v*f
t_Ω = AffineFETerm(a,l,trian,quad)

a_Γd(v,u) = (γ/h)*v*u  - v*(bn*∇(u)) - (bn*∇(v))*u
l_Γd(v) = (γ/h)*v*u - (bn*∇(v))*u
t_Γd = AffineFETerm(a_Γd,l_Γd,btrian,bquad)

op = AffineFEOperator(V,U,t_Ω,t_Γd)

uh = solve(op)
  
e = u - uh

l2(v) = v*v
h1(v) = v*v + inner(∇(v),∇(v))

el2 = sqrt(sum( integrate(l2(e),trian,quad) ))
eh1 = sqrt(sum( integrate(h1(e),trian,quad) ))

tol = 1.0e-9
@test el2 < tol
@test eh1 < tol

writevtk(trian,"trian",cellfields=["uh"=>uh])

```

**Comment by santiagobadia** [comment]
Great, I think that I have it now for vectors...

```julia

using Test
using Gridap
import Gridap: ∇
using Gridap.Arrays
using Gridap.Geometry
using Gridap.FESpaces

# Create a model with the cells whose center is in a sphere

# domain = (-1,1,-1,1,-1,1)
# partition = (4,4,4)
##
domain = (-1,1,-1,1)
partition = (4,4)
background_model = CartesianDiscreteModel(domain,partition)
background_grid = get_grid(background_model)

const R = 0.7

function is_in(coords)
  n = length(coords)
  x = (1/n)*sum(coords)
  # d = x[1]^2 + x[2]^2 + x[3]^2 - R^2
  d = x[1]^2 + x[2]^2 - R^2
  d < 0
end

oldcell_to_coods = get_cell_coordinates(background_grid)
cell_to_oldcell = findall(collect1d(apply(is_in,oldcell_to_coods)))
grid = GridPortion(background_grid,cell_to_oldcell)

grid.node_to_oldnode

topo = GridTopology(grid)
labels = FaceLabeling(topo)
model = DiscreteModel(grid,topo,labels)

# Poisson solver as always

order = 1

V_background = CLagrangianFESpace(Float64,background_grid)
V = CLagrangianFESpace(VectorValue{2,Float64},grid)

fx(x) = 1.0 + x[1]
fy(x) = 1.0 + x[2]
# fz(x) = 1.0 + x[3]
ux_background = interpolate_everywhere(V_background,fx)

ux_background.dirichlet_values

uy_background = interpolate_everywhere(V_background,fy)
# uz_background = interpolate_everywhere(V_background,fz)
u_background = [ux_background,uy_background]
uh = interpolate_everywhere(V,VectorValue(0.0,0.0))
_free_values = uh.free_values
##

dof = 0
for (comp,node) in zip(V.dof_to_comp,V.dof_to_node)
  global dof
  dof += 1
  old_node = grid.node_to_oldnode[node]
  println(dof)
  _free_values[dof] = u_background[comp].free_values[old_node]
end
```
