### ISSUE TITLE
Wrong numerical integration

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#16]
It seems that there is a problem with the numerical integration

```
D=2
nparts1d = 2
nparts = nparts1d*ones(Int64,D)
nparts_t = tuple(nparts...)
grid = CartesianGrid(partition=nparts_t,domain=(0,1,0,1),order=1) # domain, and order are optional
trian = triangulation(grid) # Generates the Triangulation associated with this grid
quad = quadrature(trian,order=2)
fun(x::Point{2}) = 1.0
ksca = integrate(fun, trian, quad)
# ksca = 0.25
```

where it should provide `ksca = 1.0`

**Comment by santiagobadia** [comment]
I misunderstood the method, I though it was integrating the function in a given domain, but it provides a cell array with the cellwise integrals.

It provides

```
ksca = [0.25, 0.25, 0.25, 0.25]
```

Is that what we want?

**Comment by santiagobadia** [comment]
Other issues arise when evaluating FE vectors and matrices in l. 100 of `FESpacesTests.jl`

**Comment by fverdugo** [comment]
> 
> ```
> ksca = [0.25, 0.25, 0.25, 0.25]
> ```
> 
> Is that what we want?

yes, we perform cell inegration, the user can always do `sum(ksca)`

**Comment by fverdugo** [comment]
> Other issues arise when evaluating FE vectors and matrices in l. 100 of `FESpacesTests.jl`

@santiagobadia please check if the issues have gone after PR #18 

If it is the case, please close the issue

**Comment by santiagobadia** [comment]
The issue has been solved after CellValue and CellMap nodifications
