### ISSUE TITLE
Extend the AffineFEOperator and FEOperator interface with matrix type

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#166]
Extend the AffineFEOperator and FEOperator interface with matrix type as we had in version 0.6.

**Comment by fverdugo** [comment]
Once done, un-comment the line in 
https://github.com/gridap/GridapPardiso.jl/blob/master/README.md

**Comment by fverdugo** [comment]
- [ ] Also use a Petsc-compatible matrix in
https://github.com/gridap/GridapPETSc.jl/blob/master/README.md

**Comment by fverdugo** [comment]
- [ ] Also here:
https://github.com/gridap/GridapPardiso.jl/blob/70198c9748891c73d118184a71e93bbaab86b886/test/femdriver.jl#L24

**Comment by victorsndvg** [comment]
I forgot to modify GridapPardiso too. Finally done in https://github.com/gridap/GridapPardiso.jl/commit/859db5ada17c60bb13ecd99f43bc19f1f58fff5a

Closing the issue
