### ISSUE TITLE
JuliaCon contribution ?

### ISSUE THREAD

**Issue by j-fu** [gridap/Gridap.jl#207]
Hi, I am Jürgen Fuhrmann from Weierstrass Institute Berlin, and the author of VoronoiFVM.jl

I would like to propose a minisymposium for JuliaCon in July which "collects" people interested in PDEs. Below is a draft of a proposal. Would you like to participate ? I am also in contact with @PetrKryslUCSD on this.

Julia for Partial Differential Equations

Simulations based on models described with partial differential equations (PDEs) are demanding with respect to probelem sizes, memory access patterns, and the high diversity of models and discretization approaches.

Julia with its capabilities with respect to near optimal scalar performance, build-in multithreading, multiprocessing and packages for GPU computing in combination with its generic programming facilities provides a new opportunity to implement well performing and easy to uses packages for PDE solution.

On the other hand due to the juvenile age of the language and the package universe, the full potential of Julia with respect to this problem class has not been reached yet.

The minisymposium contributors present several Julia packages connected with the solution of partial differential equations and systems thereof which might appeal to a broader public.

The minisymposium intends to conclude with a discussion of possible developments of features and packages for PDE simulations which would help Julia to become one of the primary choices for researchers and engineers interested in PDE simulations.

Possible schedule:

- 3-5 talks  30-20min each
- Discussion 30-20min

**Comment by fverdugo** [comment]
Hi @j-fu, @PetrKryslUCSD,

We are willing to present Gridap at JuliaCon2020 and this mini-symposium seems to be the perfect place.

I have already sent a 30-min talk proposal to JuliaCon con to present Gridap, but joining your mini-symposium is a better idea.

How I should proceed to joint your mini-symposium? 

Regards

**Comment by j-fu** [comment]
Hi,
just by telling us ;) In fact when submitting the application we just could mention your talk.
So thanks for the interest!

**Comment by fverdugo** [comment]
Ok! so please mention our talk in your proposal.

If you contact me per email (fverdugo  at  cimne.upc.edu) I can provide you the link to the draft of my talk.
