### ISSUE TITLE
Tests with julia nighlty builds are failing

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#22]
To be explored why...

**Comment by santiagobadia** [comment]
The problem is the `CellIntegration` test.

Commented for the moment, we should check why it gets stuck

**Comment by fverdugo** [comment]
I have isolated the problem. It is in line
https://github.com/gridap/Gridap.jl/blob/c0777205d5a06da330911781a782c5c3e3bfd675/test/CellIntegrationTests.jl#L63

Perhaps, it is a bug in the dev version of julia.

**Comment by fverdugo** [comment]
The nightly test do not pass again. I have reported the issue to julia in here https://github.com/JuliaLang/julia/issues/32488

**Comment by fverdugo** [comment]
Obsolete issue. Closing.
