### ISSUE TITLE
Nonlinear operator constructor with cell and boundary and/or skeleton terms

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#230]
Hi @fverdugo,

Let us consider that I want to solve a nonlinear problem + a boundary term, e.g., from Neumann. If I understand properly, we should do:

```julia
res(x,y) = c(x,x,y) - l(y)
jac(x,dx,y) = c(x,dx,y)

t_Ω = FETerm(res,jac,trian,quad)
t_Γb = FESource(l_Γb,btrian,bquad)
```
I find a little bit confusing the fact that indepedendent terms are internally multiplied by one for nonlinear problems, but (obviously) not when they are within a `FETerm`. I would prefer

```julia
t_Ω = FETerm(residual=res,jacobian=jac,trian,quad)
t_Γb = FESource(residual=-l_Γb,btrian,bquad)
```

and we can create other methods for linear problems like

```julia
t_Ω = FETerm(matrix=jac,rhs=l,trian,quad)
t_Γb = FETerm(rhs=l_Γb,btrian,bquad)
```

This is somehow aligned with the `FESpace` constructor. I think that the `FEOperator` deserves a factory with `kwargs`, etc. This allow us to be very flexible and expressive and not to bond our methods with the user interface, which is also excellent for backward compatibility.

Don't you think that this is far clearer? We can discuss the details, but I think you grasp the idea.

I feel we want a way to have full control of what is going on.

**Comment by fverdugo** [comment]
Hi @santiagobadia, I see a potential problem:

Operating with a function like `-l_Γb` in 
```julia
t_Γb = FESource(residual=-l_Γb,btrian,bquad)
```
is not very nice, since it would require to write
```julia
minus_l_Γb(v) = - l_Γb(v) 
Base.(-)(::typeof(l_Γb)) =minus_l_Γb
```
A work around can be 
```julia
t_Γb = FESource(residual=(v)->-l_Γb(v),btrian,bquad)
```

Anyway, I prefer to use different function names than using key-word arguments (since they introduce some noise when doing multiple dispatch).  But, of course both APIs can coexist.

**Comment by santiagobadia** [comment]
I wouldn't write the problem above that way. If I would have a nonlinear problem, I would use the same syntax (e.g., `res` and `jac`) for the interior, boundary, and skeleton cells. The sign `-1` would already be in the definition of `res_Γ`, as it is for `res`. What I don't like is to mix things/styles.

In any case, as you say, one can use the `kwargs` version and also the provided creational method. But I think that `kwargs` functions are essential when dealing with things as general as a `FESpace` or `FETerm`. I think that these functions are *very* limited in `Gridap`, as it should be, but they are essential in a couple of places, where we have a plethora of possibilites.
