### ISSUE TITLE
Bug in Forward Diff of VectorValue

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#240]
@fverdugo I think we have a typo in the forward diff of diff operators when the field is not a scalar.

I have created a test in this branch that crashes

https://github.com/gridap/Gridap.jl/blob/bug-forward-diff/test/GridapTests/VectorPoisson.jl

**Comment by fverdugo** [comment]
I'll take a look!

In any case, it is strange since autodiff for vector-valued PDEs is been tested in these two tests also with 2nd order manufatured solutions.

https://github.com/gridap/Gridap.jl/blob/master/test/GridapTests/PoissonTests.jl

https://github.com/gridap/Gridap.jl/blob/master/test/GridapTests/StokesTaylorHoodTests.jl

**Comment by fverdugo** [comment]
your diver passed in my environment:

```julia
$ julia --project=.
pkg> instantiate
julia> include("test/GridapTests/VectorPoisson.jl")
[ Info: Precompiling Gridap [56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e]
Test Passed
```
Can you provide this info?

```julia
julia> versioninfo()
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIAROOT = /home/fverdugo/Apps/julia/julia-1.4.0

(Gridap) pkg> status ForwardDiff
Project Gridap v0.9.1
Status `~/Code/jl/Gridap.jl/Project.toml`
  [f6369f11] ForwardDiff v0.10.10
```

**Comment by fverdugo** [comment]
In addition, try to run these tests (they pass in my machine and in Travis):

```julia
julia> include("test/GridapTests/PoissonTests.jl")
Main.PoissonTests

julia> include("test/GridapTests/StokesTaylorHoodTests.jl")
Main.StokesTaylorHoodTests

julia> include("test/FieldsTests/DiffOperatorsTests.jl")
Main.DiffOperatorsTests

```

If they fail in your machine, it should be something environment-related not Gridap-related. Perhaps we are using different versions of some dependency.

**Comment by santiagobadia** [comment]
I have updated and now seems to work
