### ISSUE TITLE
Change the type of sizes/partition member variables of CartesianDescriptor

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/Gridap.jl#244]
Change the types of the `sizes` and `partition` fields of `CartesianDescriptor` to tuples instead of points

Currently the (unique) inner constructor of `CartesianDescriptor`, available here:

https://github.com/gridap/Gridap.jl/blob/master/src/Geometry/CartesianGrids.jl#L22

clashes with

https://github.com/gridap/Gridap.jl/blob/master/src/Geometry/CartesianGrids.jl#L46

**Comment by fverdugo** [comment]
Thanks for reporting!

**Comment by fverdugo** [comment]
Closed via PR #246
