### ISSUE TITLE
Inconsistent implementation of `reindex(i_to_v::Fill, j_to_i::AbstractArray)`?

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/Gridap.jl#251]
Hi @fverdugo

The current implementation of `reindex(i_to_v::Fill, j_to_i::AbstractArray)`, i.e., 

```julia
function reindex(i_to_v::Fill, j_to_i::AbstractArray)
  v = i_to_v.value
  l = length(j_to_i)
  Fill(v,l)
end
```
seems, to me, inconsistent with the general spirit of the `Reindexed{T,N,A,B}`. In particular, the returned FilledArray, is always a rank-1 array, instead of being of the same rank as `j_to_i`.

I wonder whether it should be instead implemented as: 

```julia
function reindex(i_to_v::Fill, j_to_i::AbstractArray)
  v = i_to_v.value
  Fill(v,size(j_to_i)...)
end
```
Anyway, this does not seem to be causing any trouble, i.e., all tests pass with the current implementation.

**Comment by fverdugo** [comment]
Yes sure, it's a small thing, but we want to fix it anyway.

@amartinhuertas  Can you file a PR with this enhancement? and also with a new test that checks the correct behavior.

**Comment by amartinhuertas** [comment]
> @amartinhuertas Can you file a PR with this enhancement? and also with a new test that checks the correct behavior.

Done in PR #253

**Comment by amartinhuertas** [comment]
BTW ... should this BUG-fix appear in NEWS.md? (I think so, right?)

**Comment by fverdugo** [comment]
> BTW ... should this BUG-fix appear in NEWS.md? (I think so, right?)

as you prefer!
