### ISSUE TITLE
Eliminate `CompressedArray` and replace it by `IndexedArray`

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/Gridap.jl#271]
It turns out that `CompressedArray` and `IndexedArray` offer very similar functionality. They are indeed conceptually equivalent.

The dev effort underlying this issue involves deleting `CompressedArray` with care since there are a lot of methods overloaded for `CompressedArrays` that would need to be overloaded for `Reindexed`

**Comment by fverdugo** [comment]
The name of the fields in `CompressedArray` and `Reindexed` are different, I would like to keep the ones in `CompressedArray`. Perhaps we can delete `Reindexed` instead of `CompressedArray`.
