### ISSUE TITLE
Reducing compilation times

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#276]
I think we should consider using 

https://github.com/timholy/SnoopCompile.jl

An example of what we should do can be found for Matlang.

See 

https://github.com/juliamatlab/MatLang/blob/85640e269e902b6fb68ad254f0b939e1ffb47e7d/src/MatLang.jl#L26

We need to create a file with the functions we would like to precompile, see, e.g.,

https://github.com/juliamatlab/MatLang/blob/85640e269e902b6fb68ad254f0b939e1ffb47e7d/SnoopCompile/snoopCompile.jl

that could be a set of FE solvers in the Tests or some Tutorials.

**Comment by amartinhuertas** [comment]
This PR https://github.com/gridap/Gridap.jl/pull/432 solves to a large extent this issue

**Comment by amartinhuertas** [comment]
#432 was just merged ... closing this issue

**Comment by clason** [comment]
At the risk of sounding ungrateful, I don't think #432 is a full solution to this issue (for example, I use PDEs in different contexts, so Gridap would only be one of a changing list of modules; it's also a problem for sharing benchmark code for algorithms I develop -- if Gridap compilation takes 20s, it'll completely dominate the runtime... Hence I usually just assemble things manually).

I think a better approach (which I totally understand is low priority at the moment, but would be nice to be tracked) is actually using `precompile` statements and tracking down and fixing recompilations:
```
julia> @time using Gridap
  5.042203 seconds (15.00 M allocations: 1.138 GiB, 3.92% gc time, 5.86% compilation time: 76% of which was recompilation)
```
(note the recompilation percentage!) Including a simple test script afterward will even trigger "100% recompilation"!

**Comment by clason** [comment]
Yeah, I understand that; DSLs are difficult. I was just surprised by 
1. the extent of recompilation
2. that the (re)compilation time (TTFA, "time to first assemble", which is significant) is not even tracked as an issue.
