### ISSUE TITLE
Add cross product for gridap VectorValue type

### ISSUE THREAD

**Issue by jesusbonilla** [gridap/Gridap.jl#278]
I have added new methods to function `cross` to perform the cross product of R3 vectors. I have also included the case for R2 which returns a scalar. 

Apart from a couple tests, these are the only changes introduced, but I am not sure if I am missing something else:
https://github.com/gridap/Gridap.jl/blob/c64872a919dd7ca09195d8175b5c5205b7565123/src/TensorValues/Operations.jl#L263-L277

**Comment by fverdugo** [comment]
Hi @jesusbonilla 

That's it. The only thing is that you don't need generated functions here:
```julia
  function cross(a::MultiValue{Tuple{3}}, b::MultiValue{Tuple{3}}) 
    VectorValue{3}(a[2]b[3]-a[3]b[2], a[3]b[1]-a[1]b[3], a[1]b[2]-a[2]b[1])
 end 
  
 function cross(a::MultiValue{Tuple{2}}, b::MultiValue{Tuple{2}}) 
   a[1]b[2]-a[2]b[1]
 end 
```

Please add some tests (using both `cross` and `\times`), add a line in NEWS.md and file a PR.

Thanks!

**Comment by jesusbonilla** [comment]
Ok, perfect! Done, see PR #280
