### ISSUE TITLE
TRY "Gridap" ONLINE

### ISSUE THREAD

**Issue by asdasdqwdqwfsdf** [gridap/Gridap.jl#291]
Hello,

Can we try "Gridap" online in the future (wishlist)?

E.g. [https://freefem.org/tryit](url)

**Comment by fverdugo** [comment]
You can run online our tutorials written in jupyter notebooks using binder. Simply go to the tutorial you want and click to the binder icon.

https://gridap.github.io/Tutorials/stable/

In any case, installing Julia and Gridap is straightforward. So, I recommend to run locally.
