### ISSUE TITLE
Re-thinking ReferenceFE wrt dof ownership

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#301]
**Background**
The Ciarlet definition of reference FE involves geometry + interpolation space + dof space. Note that it does not include any knowledge of dof ownership. Thus,  the dof ownership is not an intrinsic quantity of a reference FE as defined by Ciarlet. The dof ownership depends in general on the reference FE, but also on the type of conformity one wants to impose at cell boundaries, eg. from full conformity to fully discontinuous functions passing through some intermediate situations in which one imposes conformity in a subset of the faces.

Since dof ownership is not intrinsic to a the Ciarlet's refference FE, a FE space cannot be constructed from a reference FE alone. It requires to add information about dof ownership (or about the desired conformity in order to determine the corresponding dof ownership)

**Gridap status**
Currently the `ReferenceFE` interface has the method `get_face_own_dofs(reffe::ReferenceFE)`, which suggests that the dof ownership is something intrinsic to a reference FE, which is not true following the Ciarlet's mathematical abstraction. This inconsistency has lead to some problems (see issues #292 and #300). Moreover, the construction of conforming spaces is based on the dof ownership provided by `get_face_own_dofs(reffe::ReferenceFE)`, which again assumes that dof ownership is something intrinsic to a given reffe.

**Comment by fverdugo** [comment]
**Solution**
After discussing the topic with @santiagobadia, we have realized that:

The low level `ConformingFESpace` constructor should take the reference FE(s) and also and object describing the dof ownership. In this way, the concept of reffe and the concept of dof ownership are separated, as suggests the Ciarlet's abstraction.

```julia

struct DofOwnership{A,B}
  face_own_dofs::A
  face_own_dofs_permutations::B
end

function ConformingFESpace(
  reffes::Vector{<:ReferenceFE},
  reffe_to_dof_ownership::Vector{<:DofOwnership},
  model::DiscreteModel,
  face_labeling::FaceLabeling,
  dirichlet_tags,
  dirichlet_components=nothing,
  is_ref=true)
```

Function `get_face_own_dofs`  (idem for `get_face_own_dofs_permuttions`) should be parametrized with the conformity one wants to impose in order to be consistent with the underlying mathematical abstractions. To this end, we can add a new abstract type and proceed as follows:

```julia
abstract type Conformity end
get_face_own_dofs(reffe::ReferenceFE,conf::Conformity) = @abstractmethod
get_face_own_dofs_permutations(reffe::ReferenceFE,conf::Conformity) = @abstractmethod
function get_dof_ownership(reffe::ReferenceFE,conf::Conformity) 
  DofOwnership(
    get_face_own_dofs(reffe,conf),
    get_face_own_dofs_permutations(reffe,conf))
end
```
Then, the user can define its own specialization of `Conformity` and implement the method `get_face_own_dofs` and `get_face_own_dofs_permutations` with the desired behavior. We can even implement a default version of `get_face_own_dofs_permutations` which only returns identity permutations so that the user does not needs to implement this function for the case of oriented meshes.

In the library, we can provide some usual implementations of `get_face_own_dofs` (idem for `get_face_own_dofs_permutations`). For instance, for Lagrangian reffes:

```julia
struct GradConformity <: Conformity end
function get_face_own_dofs(reffe::LagrangianRefFE,conf::GradConformity)
# return the usual dof ownership needed to compute grad-conforming spaces
end
get_default_conformity(reffe::LagrangianRefFE) = GradConformity()
```

For the `GenericRefFE`:
```julia
struct GenericRefFE{D} <: ReferenceFE{D}
  ndofs::Int
  polytope::Polytope{D}
  prebasis::Field
  dofs::Dof
  face_own_dofs::Vector{Vector{Int}}
  face_own_dofs_permutations::Vector{Vector{Vector{Int}}}
  conformity::Conformity
  face_dofs::Vector{Vector{Int}}
  shapefuns::Field
end
function get_face_own_dofs(reffe::GenericRefFE,conf::Conformity)
  @assert  conf == get_default_conformity(reffe)
  reffe.face_own_dofs
end
get_default_conformity(reffe::GenericRefFE) = reffe.conformity
```


We can also implement L2 conformity for all reffes


```julia
struct L2Conformity <: Conformity end
get_face_own_dofs(reffe::ReferenceFE,conf::L2Conformity) #-> the last face owns all dofs
```

**Comment by fverdugo** [comment]
@santiagobadia 

I have refactored a bit the ReferenceFE interface wrt the dof ownership.

Now you can do:
```julia
using Gridap
using Gridap.ReferenceFEs

quad9 = LagrangianRefFE(Float64,QUAD,2)
V = FESpace(model=model,reffe=quad9) # Default conformity (i.e. GradConformity)
V = FESpace(model=model,reffe=quad9,conformity=GradConformity())
V = FESpace(model=model,reffe=quad9,conformity=L2Conformity())
V = FESpace(model=model,reffe=quad9,conformity=CDConformity((CONT,DISC)))
```

I think that the API is quite elegant now.

The user can implement a new specialization of `Conformity` and define the methods
```julia
get_face_own_dofs(reffe::ReferenceFE,conf::Conformity)
get_face_own_dofs_permutations(reffe::ReferenceFE,conf::Conformity)
```
for the particular cases of interest. Then, you can build a FE space with this custom conformity. Thus, this is now completely extensible without creating new reference FEs or new reference FE constructors.

I have leaved the `CDLagrangian` constructor, but you can remove it if you wish. The following constructions are equivalent
```julia
quad9 = LagrangianRefFE(Float64,QUAD,2)
V = FESpace(model=model,reffe=quad9,conformity=CDConformity((CONT,DISC)))

cdquad9 = CDLagrangianRefFE(Float64,QUAD,2,(CONT,DIDC))
V = FESpace(model=model,reffe=cdquad9)
```

PR coming soon.

**Comment by fverdugo** [comment]
I have just realized that this is not yet working due to the `LagrangianRefFE` constructor:
```julia
reffe= LagrangianRefFE(Float64,QUAD,(2,0))
V = FESpace(model=model,reffe=reffe,conformity=CDConformity((CONT,DISC)))
```

**Comment by fverdugo** [comment]
Perhaps it works once issue #306 is fixed.

**Comment by santiagobadia** [comment]
Same answer as #306

**Comment by santiagobadia** [comment]
With this implementation, I would like to be able to check that if you define the order in one dim to be zero, that the continuity in that dim will be `DISC`. Otherwise it has no sense.

However, I cannot check the order now in this method:

https://github.com/gridap/Gridap.jl/blob/3ad0be1d85ee81220f7ba40825db5ba4633a97d5/src/ReferenceFEs/CDLagrangianRefFEs.jl#L69

We should fix it.
