### ISSUE TITLE
Missing work from PR #249?

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/Gridap.jl#313]
Hi @fverdugo,

I have the impression that two LOCs within `SparseMatrixAssemblers.jl` should have been rewritten as well after the incorporation of `AlgebraInterfaces.jl` in PR #249. In particular, shouldn't these LOCs:

* https://github.com/gridap/Gridap.jl/blob/db9210396102c5ee1cb66b321a94a3bf557bf972/src/FESpaces/SparseMatrixAssemblers.jl#L294
*  https://github.com/gridap/Gridap.jl/blob/db9210396102c5ee1cb66b321a94a3bf557bf972/src/FESpaces/SparseMatrixAssemblers.jl#L357

call `add_entry!(...)` , as, e.g., https://github.com/gridap/Gridap.jl/blob/db9210396102c5ee1cb66b321a94a3bf557bf972/src/FESpaces/SparseMatrixAssemblers.jl#L64 ?

If you agree, and confirm, I will submit the PR ASAP to fix this.

@amartinhuertas

**Comment by amartinhuertas** [comment]
Hi @fverdugo ... any comments/remarks on this issue?

**Comment by fverdugo** [comment]
Yes you can change this if you wish!

**Comment by fverdugo** [comment]
Closed via PR #316
