### ISSUE TITLE
Cleaning up NodalReferenceFE et al.

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#314]

**Comment by fverdugo** [comment]
We only need need 2 APIs:

- `RefereceFE` for FE-interpolation related stuff
- `LagrangianRefFE` for geometry related stuff

NodalRefFE related:

- Hence we can remove `NodalReferenceFE` and related things. 
- If we need to keep some function that takes a `NodalReferenceFE` object, we replace it for `LagrangianRefFE`


Related with `GenericRefrenceFE`

- Remove pre-computed dof ownership (but keep conformity)
- For reffes like Raviart-Thomas implement
```julia
get_face_own_dofs(reffe::GenericRefFE{D,DivConformity},conf::DivConformity)
``` 

Related with `LagrangianRefFE`:

```julia
struct LagrangianRefFE{D,C} <: NodalReferenceFE{D}
  data::GenericRefFE{D,C}
  face_nodes::Vector{Vector{Int}}
  reffaces
end
```

Fill `reffaces` only when possible, set it to `nothing`  otherwise. All functions that use this field need to check that  it is not `nothing`

```julia
get_face_own_dofs(reffe::LagrangianRefFE,conf::GradConformity)
get_face_own_dofs(reffe::LagrangianRefFE,conf::CDConformity)
```

**Comment by fverdugo** [comment]
After taking a closer look into the code I am not sure if we want to completely delete `NodalReferenceFE` (perhaps rename it?).

The problem is that there are a number of functions that are common to `LagrangianReferenceFE` and `DiscRefFE`, and now these are implemented at the `NodalReferenceFE` level to reduce code duplication. Thus we need some abstract type in the type hierarchy above `LagrangianReferenceFE` and `DiscRefFE`, but below `ReferenceFE`. 

The key is that `DiscRefFE` is conceptually also a Lagrangian  element. Thus, we have like 2 concrete implementations of (conceptually) Lagrangian elements. In consequence, perhaps what makes more sense is to have an abstract type for lagrangian elements. The type hierarchy would be something like:

```
ReferenceFE
|
|
|---------------------------------|
|                                 |
LagrangianRefFE             GenericRefFE
|
|
|------------------------------|
|                              |
GenericLagrangianRefFE     DiscRefFE
```

We can even add a new concrete implementation `GeometricLagrangianRefFE` (better name?) that is the one to be used in geometry-related parts. This would be the only one that needs `reffaces` (in this way we isolate the `reffaces` which is a quite ugly thing).

```
ReferenceFE
|
|
|---------------------------------|
|                                 |
LagrangianRefFE             GenericRefFE
|
|
|------------------------------|------------------------------|
|                              |                              |
GenericLagrangianRefFE     DiscRefFE               GeometricLagrangianRefFE
```

**Comment by fverdugo** [comment]
Another iteration. Perhaps the only types we need ara these:

```
ReferenceFE
|
|
|---------------------------------|
|                                 |
LagrangianRefFE             GenericRefFE
|
|
|----------------------------------------------|
|                                              |
GenericLagrangianRefFE              GeometricLagrangianRefFE
```

**Comment by santiagobadia** [comment]
The last one looks nice, if possible.

**Comment by fverdugo** [comment]
@santiagobadia Work done in PR #319 

The final type hierarchy is 
```
ReferenceFE
|
|
|---------------------------------|
|                                 |
LagrangianRefFE             GenericRefFE
|
|
|-----------------------------------------|
|                                         |
GenericLagrangianRefFE              PDiscRefFE 
```

When using the high-level `LagrangianRefFE` constructor, one gets:

`GenericLagrangianRefFE{GradConformity}` if all orders are !=0, `GenericLagrangianRefFE{L2Conformity}` if all orders are ==0, and `GenericLagrangianRefFE{CDConformity}` otherwise.

@santiagobadia take a look into NEWS.md for a summary of the major changes from the user perspective.

Closing issue. We can always re-open if something is missing.

**Comment by fverdugo** [comment]
Some further refactoring:

Remove `CDLagrangian` and `PDiscRefFE` constructors and extend `LagrangianRefFE` constructor with a new argument denoting the type of polynomial space

**Comment by santiagobadia** [comment]
Closing the issue
