### ISSUE TITLE
Using broadcast notation for FEFunctions in-place operations

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#325]
Let us consider we want to do operations with `FEFunction`s
```
xh = xh + yh
wh = xh+2*yh+zh
```
The current implementation of these operations is lazy, returning `GenericCellField`, which is neat and very powerful, but not the most efficient implementation possible.

I think we could consider a broadcast-like implementation of operations over `FEFunction`s, e.g.,
```
xh .= xh .+ yh
wh .= xh.+2.*yh+.zh
```
where the operations are in-place, and we can even reuse allocations.

@fverdugo what do you think?

In any case, I don't think it is an urgent matter

Interesting post

https://julialang.org/blog/2017/01/moredots/

**Comment by fverdugo** [comment]
I see the point of having in-place versions but I am not sure if broadcast is the abstraction we are looking for. 

I would say that the only operations we want to perform with `FEFunctions` via their free values are addition, subtraction and scaling. Adding new methods to `sum!` an `mul!` will do the job.

**Comment by santiagobadia** [comment]
Sure, these methods must be there... I was wondering whether we could use dot notation for some syntactic sugar. Do you think this is it misleading?

**Comment by fverdugo** [comment]
Yes, quite misleading:

`wh = uh + uh` and  `wh .= uh .+ uh` both make sense, but

`wh = uh ⊙ uh` makes sense but `wh .= uh .⊙ uh`  would make no sense if you interpret broadcast in therms of free values

**Comment by fverdugo** [comment]
The thing is that broadcast is applying an operation to the items of an array. A FEFunction is  understood as an array of fields (not as an array of free values). That is:  these two currently give the same numeric answer (with a different memory layout):
```julia
evaluate(uh ⊙ uh,q)
evaluate(get_array(uh) .⊙ get_array(uh),q)
```

**Comment by fverdugo** [comment]
If you want to use broadcast syntax, perhaps the best way is to get the free values and work with them explicitly. 

```julia
wh.free_values .= uh.free_values .+ uh.free_values
```

**Comment by santiagobadia** [comment]
Ok, the point was a more compact version that would not require the user to write this (which is probably not what we want, by the way, you would also need to take care of Dirichlet data). It is true that the dot notation has sense for array operations, but not for the all the ones that have sense for FEFunctions. So, we could just use function names, no operator overload. It is a performance trick at the end of the day.

**Comment by fverdugo** [comment]
Yes!

in fact i like getting the free values and using broadcast with them. It is 100% inteniton revealing. And it  is just 1 LOC more:
```julia
w, u = map(get_free_values,(wh,uh)) 
w .= u .+ u
```

**Comment by santiagobadia** [comment]
Ok, agreed but you need
```
w, u = map(get_free_values,(wh,uh)) 
w .= u .+ u
w, u = map(get_dirichlet_values,(wh,uh)) 
w .= u .+ u
```
it is OK anyway

**Comment by santiagobadia** [comment]
I think I can close the issue
