### ISSUE TITLE
joss-paper: Software design

### ISSUE THREAD

**Issue by PetrKryslUCSD** [gridap/Gridap.jl#334]
Starting on page 1, in the sentence beginning with "In contrast...": The paper introduces some concepts which are in my opinion described at a level that does not/cannot provide any real insight. 

For instance, when I hear "cell -wise" I can certainly form a mental picture, but the detail supplied in the paper is not sufficiently granular to allow me to judge the agreement or disagreement of that mental picture with what is designed and implemented in the repository.

What is a "cell -wise array" and a "cell -wise field"? Again, there is a hint that this might be interesting, but not enough detail to make sense of it really.

Similarly "laziness".  The concept is introduced, but the reader is not told enough to make sense of it. 

Next, "lambda variational form" is mentioned. What is it, how is it used? 

Finally, "state diagram" is mentioned. What is it? Why should the reader care? Not enough information is provided.

So, I think the authors need to decide whether or not this is something that can be described in a compact space, and if it cannot, is it worthwhile introducing it in the first place?

**Comment by fverdugo** [comment]
Related to https://github.com/openjournals/joss-reviews/issues/2520

**Comment by fverdugo** [comment]
@PetrKryslUCSD Following your suggestion, I have simplified the paragraph about software design. I have opted for not introducing concepts that cannot be properly explained in such compact document.

If you are happy with the changes, please close the issue.
