### ISSUE TITLE
joss-paper: Missing operators

### ISSUE THREAD

**Issue by PetrKryslUCSD** [gridap/Gridap.jl#335]
The weak form definition is incomplete: the gradient operators and the dot product operator are missing. Perhaps the font did not include these symbols?

**Comment by fverdugo** [comment]
Related to https://github.com/openjournals/joss-reviews/issues/2520

**Comment by fverdugo** [comment]
@PetrKryslUCSD The operators are in the paper.md source file, but they are not visualized correctly.

In standard .tex documents to be compiled with pdflatex, I am able to display these operators by including
```tex
\usepackage[utf8x]{inputenc}
\usepackage{textgreek}
```  
in the preamble.  However, I do not know how to achieve this in this for the JOSS paper.

Dear editor  @Kevin-Mattheus-Moerman, could you provide any hint on how to fix this? Could you please forward the issue to the person in charge of the paper compilation system?

**Comment by Kevin-Mattheus-Moerman** [comment]
@fverdugo could you paste the code generating the desired expression here? Also could you share a screenshot of the expression being rendered correctly (e.g. using a different Latex editor)? I'll have out development team look at it then. 
Worst case an ugly but practical solution would be to represent the expression as an image in the paper instead.

**Comment by Kevin-Mattheus-Moerman** [comment]
@fverdugo :point_up:

**Comment by fverdugo** [comment]
This is a MWE with some code snippets containing the Greek operators.

Consider a file `main.tex` with these contents:
```tex
\documentclass{article}
\usepackage[utf8x]{inputenc}
\usepackage{textgreek}
\begin{document}
\begin{verbatim}
f(x) = -Δ(u)(x); g(x) = u(x)
a(u,v) = ∇(u)⋅∇(v); l(v) = v*f
trian_Ω = Triangulation(model)
\end{verbatim}
\end{document}
```

Compile it with pdflatex
```bash
pdflatex main.tex
```
Result:
[main.pdf](https://github.com/gridap/Gridap.jl/files/5028555/main.pdf)

As I have said, the trick is to include these lines in the preamble:
```tex
\usepackage[utf8x]{inputenc}
\usepackage{textgreek}
```

**Comment by fverdugo** [comment]
@Kevin-Mattheus-Moerman

**Comment by fverdugo** [comment]
@Kevin-Mattheus-Moerman 
@PetrKryslUCSD 

I have added the code sniped as a figure. Now the code symbols are visualized correctly.

https://raw.githubusercontent.com/openjournals/joss-papers/joss.02520/joss.02520/10.21105.joss.02520.pdf

You can close the issue, please.

**Comment by PetrKryslUCSD** [comment]
Resolved
