### ISSUE TITLE
joss paper: Contribution and authorship

### ISSUE THREAD

**Issue by TeroFrondelius** [gridap/Gridap.jl#343]
I think that in Engineering we have too few authors in all papers. Anyway, I checked the contributions and the best of my understanding @victorsndvg has made some major contributions and could be listed as joss-paper author. 

Xref: https://github.com/openjournals/joss-reviews/issues/2520

**Comment by santiagobadia** [comment]
@TeroFrondelius thanks for the suggestion. In any case, we would like to keep the list of authors is it is. @fverdugo and myself were the ones that started the project, designed its kernel, and the only developers during the first stage of the project.

**Comment by TeroFrondelius** [comment]
Here: https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort, it defines 1000 LOC as a major contribution. Of course, I didn't look very detailed, but @victorsndvg has contributed 5903 LOC in 78 commits.

**Comment by santiagobadia** [comment]
As far as I can see, this number is about the min scholarship effort of the project to be accepted. We consider that LOC alone do not give much information. E.g., it is not the same to create wrappers using clang than designing the kernel of Gridap. 

Victor created wrappers to PETSc and re-implement in Julia the COO matrices and compression algorithms in our previous [project](https://github.com/fempar). This is not the core of the library, and as a result, we consider that the list of authors is appropriate and complete in its current version. On the other hand, the project has had about 200K of LOCs.

So, we consider that this the list of authors is appropriate and complete.

**Comment by TeroFrondelius** [comment]
I accept the explanation, even though I don't fully agree. Engineering and mathematics should learn from medical and physics, where the list of authors is much longer and smaller contributions to the research are also recognized.
