### ISSUE TITLE
Add DiractDistribution for point "things"

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#357]
A point load can be mathematically represented as a distribution, e.g., a Dirac delta. It breaks the `Gridap` flow, since one cannot use Gauss quadratures and numerical integration (what we usually do in FEM) to compute the integral of f*v in that case.

I don't want to consider hacks, e.g., touch the vector entry in a particular node in which you want to put the force  (assuming the force is on a node).

Instead, e.g., I would consider a constructor for `f = DiracDelta(x_0)` that returns a `Distribution <: Field` that we know cannot be used with integration BUT instead, `integrate(f*v,trian,quad)` returns v(x).

**Comment by Omega-xyZac** [comment]
As an aside to this, how would you do the 'hack' in this case? I would implement the above but I don't think I have enough experience in Gridap just yet.
