### ISSUE TITLE
`is_entry_stored` has a confusing name

### ISSUE THREAD

**Issue by mohamed82008** [gridap/Gridap.jl#362]
The name `is_entry_stored` is confusing because here for example, it is always true.
https://github.com/gridap/Gridap.jl/blob/28dd80b2ad2c099a85c030f4d6670552f8a2fdb5/src/Algebra/SparseMatrixCSC.jl#L15
Reading the docstring, I understand why it is always true here. But maybe `can_insert_entry` is a better name.

**Comment by santiagobadia** [comment]
It is just used for symmetric matrices, in which case it returns `false` when `i > j`. In that case, the entry is stored in (added to) the `[j,i]` entry instead.

I am not sure about what is better. Something link `is_entry_stored_in_ij`? Probably a minor point.

I think that `can` can be misleading too.

**Comment by mohamed82008** [comment]
I see. I think the documentation can just be clarified without changing the name if there is no better name.
