### ISSUE TITLE
Adding an element/face to a tag

### ISSUE THREAD

**Issue by Omega-xyZac** [gridap/Gridap.jl#367]
Is this currently possible? ie, I have 2D cartesian elements with id 1-1800. I want to add some of these elements to a tag "material_2" so that I can introduce a multi-material problem.

**Comment by fverdugo** [comment]
You have to add a new entity and tag to our model:

```julia
label = get_face_labeling(model)

# get the next entity number
entity = num_entities(label) + 1

# mark the cells you want with the new entity.
d = num_cell_dims(model)
for cell in 1:num_cells(model)
  if (your_own_criterion_here)
    label.d_to_dface_to_entity[d+1][cell] = entity
  end
end

# Add a new tag associated with the new entity
add_tag!(label,"material1",[entity])
```

**Comment by oriolcg** [comment]
Hi @Omega-xyZac , I did something similar some time ago. You can check this issue #322. The final working code is given in the following link: https://github.com/gridap/Gridap.jl/issues/322#issuecomment-661263254

**Comment by Omega-xyZac** [comment]
Thanks for the help guys. That is very helpful.
