### ISSUE TITLE
Point and Line Dirichlet Tags

### ISSUE THREAD

**Issue by Omega-xyZac** [gridap/Gridap.jl#371]
Hi,
I'm trying to run a simple 2D linear elasticity model on gridap on a a 2x2 grid of square elements. The left boundary is constrained in the x direction and to fully constrain the model the top left point should have a xy-support. There is then a Neumann bc applied to the right boundary. I tried doing this using the Dirichlet tags and Dirichlet masks as per the tutorial, however it is clear from the stiffness matrix that the xy-support on the top left point is not being correctly applied since the size of the matrix is larger than it should be. 
```
using Gridap
using Gridap.FESpaces
using Gridap.Fields
using Gridap.ReferenceFEs
using Gridap.Geometry

domain = (0.0, 1.0, 0.0, 1.0);
model = CartesianDiscreteModel(domain,(2,2));
nodes_coords = get_node_coordinates(model);

labels = get_face_labeling(model);
add_tag_from_tags!(labels,"point4",[3,]);
add_tag_from_tags!(labels,"dirichlet",[7,]);
add_tag_from_tags!(labels,"neumann",[8,]);

#writevtk(model,string(pwd(),"\\Gridap Testing\\Gridap LE Square Element\\square"))

btrain = BoundaryTriangulation(model, "neumann")
bquad = CellQuadrature(btrain,2)

V0 = TestFESpace(
  reffe=:Lagrangian, order=1, valuetype=VectorValue{2,Float64},
  conformity=:H1, model=model, dirichlet_tags=["dirichlet","point4"],
  dirichlet_masks=[(true,false),(false,true)])

g1(x) = VectorValue(0.0, 0.0)
g2(x) = VectorValue(0.0, 0.0)

U = TrialFESpace(V0,[g1,g2])

h(x) = VectorValue(2.0,0);

a(u,v) = ε(v) ⊙ σ(ε(u))
l_Γ(v) = v ⊙ h
t_Γ = FESource(l_Γ,btrain,bquad)

using LinearAlgebra: tr
const E = 1;
const ν = 0.3;
const λ = (E*ν)/((1+ν)*(1-2*ν));
const μ = E/(2*(1+ν));
@law σ(ε) = λ*tr(ε)*one(ε) + 2*μ*ε;

trian = Triangulation(model)
degree = 2;
quad = CellQuadrature(trian,degree)
t_Ω = LinearFETerm(a,trian,quad)
op = AffineFEOperator(U,V0,t_Ω,t_Γ)

stiffness = op.op.matrix;
F = op.op.vector;

uh = solve(op)

nodes = get_cell_coordinates(trian)
uh_values = Fields.evaluate(uh,nodes)

#writevtk(trian,"Gridap LE Square Element\\results",cellfields=["uh"=>uh,"epsi"=>ε(uh),"sigma"=>σ(ε(uh))])

D= stiffness\F
```
Of course, I could just concatenate the stiffness matrix and vector F at the end of the script. This isn't very satisfying however. If you have any suggestions please let me know

**Comment by fverdugo** [comment]
I think you want something like this

```julia
add_tag_from_tags!(labels,"dirichlet",[1,7])
dirichlet_masks=[(true,false),(true,true)]
```

**Comment by Omega-xyZac** [comment]
No luck. It doesn't seem to actually be constraining the top left point in the y direction. I think the left boundary is fine and is constrained in the x direction though.

**Comment by fverdugo** [comment]
It works fine for me.

```julia
using Gridap

domain = (0.0, 1.0, 0.0, 1.0)
model = CartesianDiscreteModel(domain,(2,2))

labels = get_face_labeling(model)
add_tag_from_tags!(labels,"point4",[3,])
add_tag_from_tags!(labels,"dirichlet",[1,7,])
add_tag_from_tags!(labels,"neumann",[8,])

V0 = TestFESpace(
  reffe=:Lagrangian, order=1, valuetype=VectorValue{2,Float64},
  conformity=:H1, model=model, dirichlet_tags=["dirichlet","point4"],
  dirichlet_masks=[(true,false),(true,true)])

vh = interpolate(V0,VectorValue(1.0,1.0))

trian = Triangulation(model)
writevtk(trian,"trian",cellfields=["vh"=>vh])

```

v_x is constrained at the left boundary:

![v_x](https://user-images.githubusercontent.com/48508177/90497601-8a73e480-e147-11ea-86e0-10bc980a6b49.png)

v_y is constrained at the top left-point

![v_y](https://user-images.githubusercontent.com/48508177/90497644-98296a00-e147-11ea-9e49-182de4990b80.png)
:

**Comment by fverdugo** [comment]
I have used Gridap@0.13.3 (the latest version as of today)
