### ISSUE TITLE
Code organization

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#4]
Discussion to find a proper way of organizing code

**Comment by fverdugo** [comment]
Random questions that I cannot still properly solve:

* How to avoid name clashes in the library? (using sub-modules maybe?)

* How to avoid name clashes between tests?

* How to organize tests properly, so that it is easy to run a subset of them?

* How to automatically detect performance regressions? I think this is as important in julia as unit testing

**Comment by fverdugo** [comment]
To isolate `@testsets` and avoid name clashes between tests the way to go is to create modules: https://discourse.julialang.org/t/testset-scoping/17025/4

It we don't want to create modules manually, one can use [SafeTestsets](https://github.com/YingboMa/SafeTestsets.jl), which does it for you.  [DifferentialEquations](https://github.com/JuliaDiffEq/DifferentialEquations.jl) is using [SafeTestsets](https://github.com/YingboMa/SafeTestsets.jl). We can do the same.

**Comment by santiagobadia** [comment]
I would define header files for collections of types, e.g.
one `CellArraysHeader` and `CellArraysImpl` `CellBasesImpl` for all subcollections of types.

If we separate these `structs` in different submodules, we will have to write e.g. `CellArrays.Method()` in `CellBases`, etc.

**Comment by fverdugo** [comment]
I think, there are two different things:

1) How to make visible names that are created and exported in `Numa.CellArrays` when the user does
```
pkg> add Numa
pck> using Numa
```
2) How to make visible (and overload-able) names that are created and exported in `Numa.CellArrays`  from `Numa.CellBases`.

Reexporter only solves 1). For 2), I think it is quire easy. Simply write  `import ..CellArrays` (with two periods) just after opening the module `Numa.CellBases`.

**Comment by santiagobadia** [comment]
But as far as I understand it only works for names that are exported.

If you check the current interaction between `Cell*` modules, I would say they are sharing much more than just exported names. If you do `import ..CellArrays` in `CellBases` you will need to use `CellArrays.Method` based on [this](https://docs.julialang.org/en/v1/manual/modules/#modules-1)

It is a decision we have to make. But it would be better to make it soon, because it will imply modifications. I would prefer to consider a common NameSpace for very related types, e.g., one for `CellArrays`, `CellBases`, `CellFields`, etc.

I have been playing with this in the branch I created but then, tests do not pass yet...

**Comment by fverdugo** [comment]
We can discus this face to face tomorrow.

**Comment by santiagobadia** [comment]
```julia
module CellArrays

export CellArray
export ConstantCellArray

# CellArrays.jl file

#Abstract types: 

abstract type CellArray end

# Concrete types

struct ConstantCellArray
	fields
end

# Methods

include(CellArraysMethods.jl)

end # module CellArrays
´´´

´´´julia
# Numa.jl

include("CellArrays.jl")

using Numa.CellArrays : CellArray
export CellArray
# Assuming we only want to export CellArray from Numa
# but not ConstantCellArray

´´´

**Comment by fverdugo** [comment]
I also would sugest to avoid full imports from external libraries. E.g.

```julia
module CellArrays

# using LinearAlgebra (to be avoided)
using LinearAlgebra: det # preferred

export CellArray
export maxsize
export maxlength

...

```
It can happen that after a refactorization of CellArrays, the funciontion `det` is not used any more. In this case using the selective imports make it easy to check if LinearAlgebra is longer needed in the module (since we can look for `det` in the source files).  Otherwise you don't know which words look for

**Comment by santiagobadia** [comment]
@fverdugo We should think more about convention for getters and setters.
I am using now fieldname(X) to get X.fieldname. The only issue with this is that you cannot use fieldname as local variable.

 https://github.com/JuliaLang/julia/issues/16770

**Comment by fverdugo** [comment]
With v0.7.0 we have converged to a sensible project structure. Closing issue.
