### ISSUE TITLE
redundant method definition?

### ISSUE THREAD

**Issue by stevengj** [gridap/Gridap.jl#407]
My student @wenjie was looking through your code and noticed that [this `apply_kernel!` method](https://github.com/gridap/Gridap.jl/blob/c1e0e6a7768539b15fb7a05a42a851557cf56d76/src/Fields/Integrate.jl#L38-L45) and [this `apply_kernel!` method](https://github.com/gridap/Gridap.jl/blob/c1e0e6a7768539b15fb7a05a42a851557cf56d76/src/Fields/Integrate.jl#L62-L79) have apparently identical signatures, which means that Julia will overwrite the first method with the second method and hence the first method will never be called.   Is this a bug, or just some obsolete code that never got deleted?

**Comment by fverdugo** [comment]
I can see that one definition is for ::AbstractVector and the other for ::AbstractArray. I would say that there is no method overwriting here. In addition, the compiler does not throw any of the usual warnings when one overwrites a method.

Have you experienced some issue related with those methods??

**Comment by amartinhuertas** [comment]
I agree here with @ferdugo. There shouldn't be method overwritting nor ambiguities:

```
julia> Tuple{Gridap.Fields.IntKernel,Gridap.Fields.IntKernel,AbstractArray,Any,Any} <: 
Tuple{Gridap.Fields.IntKernel,Gridap.Fields.IntKernel,AbstractVector,Any,Any}
false

julia> Tuple{Gridap.Fields.IntKernel,Gridap.Fields.IntKernel,AbstractArray,Any,Any} >: 
Tuple{Gridap.Fields.IntKernel,Gridap.Fields.IntKernel,AbstractVector,Any,Any}
true

julia> Tuple{Gridap.Fields.IntKernel,Gridap.Fields.IntKernel,AbstractArray,Any,Any} == 
Tuple{Gridap.Fields.IntKernel,Gridap.Fields.IntKernel,AbstractVector,Any,Any}
false
```

If there is a missbehaviour of the Julia REPL, it would be nice to trace it down and report it.

**Comment by stevengj** [comment]
Whoops, thanks, my eye missed that distinction.  I agree that they aren't redundant.
