### ISSUE TITLE
3-tensor contractions with 2-tensor and 1-tensor

### ISSUE THREAD

**Issue by Omega-xyZac** [gridap/Gridap.jl#414]
This doesn't seem to be implemented just yet. Would definitely be beneficial.

**Comment by fverdugo** [comment]
Hi @Omega-xyZac,

I thought that these contractions were rather non standard. Do you really need them?

Do you need simple, or full contractions ? which one of the following?

```
a_i = b_ijk*c_jk
a_ijl = b_ijk*c_kl
a_ij = b_ijk*c_k
```

In any case, you can take a look how contractions are implemented in 
https://github.com/gridap/Gridap.jl/blob/master/src/TensorValues/Operations.jl
and try to add the ones you need, but we need to agree in the symbol used to express each case though.

**Comment by Omega-xyZac** [comment]
Hi @fverdugo,

I guess I can use Voigt notation but I would prefer not to since I am working on a homogenisation problem which would ideally have use full tensor formulation. I need:
```
a_i = b_ijk*c_jk
a_ij = b_kij*c_k
```
in the above, `c_jk` would be symmetric. I guess symbol wise we would use `\odot` 2nd case and `\cdot` for first?

**Comment by fverdugo** [comment]
We use \odot for full contraction and \cdot for simple contraction. This would be the syntax for your cases:
```julia
a = b ⊙ c # a_i = b_ijk*c_jk
a = c ⋅ b #  a_ij = c_k*b_kij
```

**Comment by Omega-xyZac** [comment]
Thanks. I'll have a look at implementing those.

**Comment by Omega-xyZac** [comment]
This seems to do the trick:
```
@generated function dot(a::A, b::B) where {A<:MultiValue{Tuple{D1,D2,D3}},B<:MultiValue{Tuple{D1}}} where {D1,D2,D3}
  ss = String[]
  for k in 1:D3
    for j in 1:D2
      s = join([ "a[$i,$j,$k]*b[$i]+" for i in 1:D1])
      push!(ss,s[1:(end-1)]*", ")
    end
  end
  str = join(ss)
  Meta.parse("TensorValue{$D2,$D3}(($str))")
end

import Gridap.TensorValues.inner

@generated function inner(a::A, b::B) where {A<:MultiValue{Tuple{D1,D2,D3}},B<:MultiValue{Tuple{D2,D3}}} where {D1,D2,D3}
  ss = String[]
  for i in 1:D1
    s = join([ "a[$i,$j,$k]*b[$j,$k]+" for j in 1:D2 for k in 1:D3])
    push!(ss,s[1:(end-1)]*", ")
  end
  str = join(ss)
  Meta.parse("VectorValue{$D1}(($str))")
end
```

Are you happy with this @fverdugo ?

**Comment by Omega-xyZac** [comment]
This seems to create issues elsewhere:
```
function a_uϕ(Uϕ,VQ)
     v, q = VQ
     u, ϕ = Uϕ
     return (- e ⋅ -∇(ϕ)) ⊙ ε(v)
  end
```
...
```
Ke_uϕ = get_cell_matrix(LinearFETerm(a_uϕ,trian,quad),get_cell_basis(Uϕ),get_cell_basis(VQ))[1];
```
gives `AssertionError: L == D1 * D2 * D3`. I don't see why this would be.

**Comment by Omega-xyZac** [comment]
Issue seems to be that new methods are not being called in weak form. I have a lot of issues debugging in Julia. I have taken
```
import LinearAlgebra.⋅
⋅(a::A,b::B) where {A<:MultiValue{Tuple{D1,D2,D3}},B<:MultiValue{Tuple{D3}}} where {D1,D2,D3} = dot(a, b)
⋅(a::A,b::B) where {A<:MultiValue{Tuple{D1}},B<:MultiValue{Tuple{D1,D2,D3}}} where {D1,D2,D3} = dot(a, b)
```
in my code to extend `⋅`. (Note new method as mentioned in #415)

Please advise

**Comment by Omega-xyZac** [comment]
Okay, I seem to of fixed the issue by implementing `@law gradϕ_e(∇ϕ) = -∇ϕ ⋅ -e`.

**Comment by Omega-xyZac** [comment]
Hi @fverdugo, would you be interested in me adding the some additional operations. Eg below:
```
# a_ijpm = b_ijkl*c_jkpm
@generated function (:)(a::A, b::B) where {A<:SymFourthOrderTensorValue{D},B<:SymFourthOrderTensorValue{D}} where D

  Sym4TensorIndexing = [1111, 1121, 1131, 1122, 1132, 1133, 2111, 2121, 2131, 2122, 2132, 2133,
                        3111, 3121, 3131, 3122, 3132, 3133, 2211, 2221, 2231, 2222, 2232, 2233,
                        2311, 2321, 2331, 2322, 2332, 2333, 3311, 3321, 3331, 3322, 3332, 3333]
  ss = String[]
  for off_index in Sym4TensorIndexing
    i = parse(Int,string(off_index)[1]); j = parse(Int,string(off_index)[2]);
    m = parse(Int,string(off_index)[3]); p = parse(Int,string(off_index)[4]);
    s = join([ "a[$i,$j,$k,$l]*b[$k,$l,$m,$p]+" for k in 1:D for l in 1:D])
    push!(ss,s[1:(end-1)]*", ")
  end
  str = join(ss)
  Meta.parse("SymFourthOrderTensorValue{$D}($str)")
end
```
