### ISSUE TITLE
Gradient of field / @law across domains

### ISSUE THREAD

**Issue by AndiMD** [gridap/Gridap.jl#426]
In the weak form of the heat equation, the gradient of the thermal conductivity is required. When there are just two homogeneous domains, it seems straightforward to define the thermal conductivity independent of coordinates like this:
```
@law function fλx(tag) # [W/um/K] Thermal conductivity
  (tag == SiO2_tag) && return λSiO₂
  (tag == Cu_tag) && return λCu
  error("Bad tag in fλx(tag)")
end
```
However, this is not compatible with the gradient in the weak form. Could we somehow generalize `@law` to have this work seamlessly? (apologies if I missed something)

**Comment by Omega-xyZac** [comment]
Have you looked at the multi-material section in [https://gridap.github.io/Tutorials/stable/pages/t003_elasticity/](url)? I think this solves your problem. I might be mistaken though.

**Comment by AndiMD** [comment]
Thanks, this tutorial was actually my starting point. This is what I want to accomplish:
`a(u,v) = fλx(tags)*(∇(v)⊙∇(u)) + (∇(fλx(tags))⊙∇(u))*v`

**Comment by Omega-xyZac** [comment]
Ah. I see. Are `λSiO₂` and `λCu` functions of x? You might need to pass x to `@law` function the tag as the first argument.

**Comment by AndiMD** [comment]
For now, they are scalars. I remember a simple function x->fλx(x) to be working, not with an additional tags parameter, though. As soon as I can get to it, I will do a MWE.

**Comment by fverdugo** [comment]
@AndiMD computing the gradient of `fλx(tag)` would mean differentiate with respect to tag.  Are you sure that you want this?

**Comment by AndiMD** [comment]
@fverdugo : Of course, the function implicitly depends on x.

Maybe I can rephase it like this: How can I efficiently create a function across domain tags that does the following: `x->fλx(x2tag(x))` where `x2tag` returns the tag of the current domain?

**Comment by fverdugo** [comment]
@AndiMD Perhaps it is an issue related with propagation of dual numbers. Try to write f(x) so that the julia type of the result depends on the type of the input.

**Comment by AndiMD** [comment]
@fverdugo : I am sorry if my intentions are still unclear.
The function `x2tag` is pseudocode to show what I want to do. I do not know how to do it in a straightforward manner. Using a coordinate x to identify a cell tag sounds highly inefficient (can we even differentiate through that?).

**Comment by santiagobadia** [comment]
> In the weak form of the heat equation, the gradient of the thermal conductivity is required. 

@AndiMD if I understand, you have a heat equation with piecewise constant coefficient (two regions). This equations has the form `∇⋅fλ∇u = g` and after integration by parts you simply integrate `fλx(tags)*(∇(v)⊙∇(u))` on the volume (plus boundary terms if Neumann), assuming that your heat conductivity is a scalar, not a tensor. 

So, you do not need the problematic term.

In any case, you can see that this term is not well-defined. You are trying to compute the gradient of a discontinuous function. There are other issues, but I think that first it is better to clarify this.

**Comment by fverdugo** [comment]
Hi @AndiMD !

can you provide a MWE fo clarify things ?

**Comment by AndiMD** [comment]
Thanks for you explanations. I had wrongfully assumed that the nondifferentiable thermal conductivity jump would automatically become differentiable by projection to the finite element space.
I will provide a small MWE asap.

**Comment by AndiMD** [comment]
@fverdugo @santiagobadia 
Although I understand now why the gradient is ill-defined, here the MWE for reference. Most relevant, lines 71..76.
[gridapHeat.zip](https://github.com/gridap/Gridap.jl/files/5432014/gridapHeat.zip)

Can I project the conductivity formula onto the finite element field and differentiate that?

**Comment by AndiMD** [comment]
The FeNiCS reference that addresses this problem also
[https://fenicsproject.org/pub/tutorial/sphinx1/._ftut1005.html](https://fenicsproject.org/pub/tutorial/sphinx1/._ftut1005.html) (around Eqn. 74) indicates that the gradient is not required, so its probably my poor understanding of FEM at fault here
