### ISSUE TITLE
BlockArrayCoo assumes same type for all blocks

### ISSUE THREAD

**Issue by oriolcg** [gridap/Gridap.jl#430]
This issue is related to issue https://github.com/gridap/GridapODEs.jl/issues/29. 

The current implementation of `BlockArrayCoo` assumes the same type for all blocks, i.e. `blocks::Vector{A}`. Would it be possible to consider a more general case where each block has its own type?

This is needed, for instance, when using ForwardDiff for a transient and multi-field problem. In this case we can have a block made out of an array of `Float64` and a block with an array of `ForwardDiff.Dual`.

Any thoughts on this @fverdugo @santiagobadia ?

**Comment by fverdugo** [comment]
I see some potential problems related to type stability in the algorithms that iterate over blocks.

**Comment by fverdugo** [comment]
BTW, ForwardDiff does not work with block matrices. Perhaps collecting the block array into an standard array before sending it to ForwardDiff would fix the problem.

**Comment by fverdugo** [comment]
In any case, good point @oriolcg !

**Comment by oriolcg** [comment]
> BTW, ForwardDiff does not work with block matrices. Perhaps collecting the block array into an standard array before sending it to ForwardDiff would fix the problem.

I don't think the problem is there. The current implementation works well for multiple blocks (see steady Stokes). The problem comes at the binary operation `+` happening at the evaluation of the weak form, where you have the mismatch of types for different blocks.

**Comment by fverdugo** [comment]
BlockArrayCoo has been removed and this issue is out of date now.
