### ISSUE TITLE
Move the CI pipeline to GH actions (travis not unlimited free for OSS anymore)

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#442]
In particular, we want:

- Tests
- Documentation
- Coverage reports

and the corresponding badges in the README.md file.

**Comment by amartinhuertas** [comment]
Tests badge with GH can be found here: https://github.com/gridap/GridapDistributed.jl/blob/master/README.md

More information here as well: https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/adding-a-workflow-status-badge

**Comment by fverdugo** [comment]
PR #450 solves this issue.

**Comment by amartinhuertas** [comment]
Hi @fverdugo ... I would also add `x86` arch to the matrix of Github Actions. What do u think?

Going even further, we could investigate a github actions linter that triggers warnings by parsing the code in the search of explicit use of Int64 ... but perhaps this is too much. 

What do you think about the first and the second? I can do the first ... I may investigate the second, not actually sure if this can be achieved and how ...

**Comment by amartinhuertas** [comment]
FYI ... the whole set of Julia-related Github Actions are maintained here ... https://github.com/julia-actions

**Comment by fverdugo** [comment]
It also would be nice to lint against trailing white spaces!
