### ISSUE TITLE
Hyperbolic function support for FEFunction?

### ISSUE THREAD

**Issue by WenjieYao** [gridap/Gridap.jl#446]
I have a FEFunction `ph=FEFunction(P,pvec)` and I want to pass something like `tanh(ph)` to the FE terms, e.g. `a(u,v)=tanh(ph)*u*v`, then it tells me that no method matching `tanh(::Gridap.CellData.GenericCellField{true,()})`, is there a workaround to fix this?

**Comment by fverdugo** [comment]
try `operate(tanh,ph)` instead of `tanh(ph)`

**Comment by WenjieYao** [comment]
Thanks, that works! But I still need to define `Gridap.Helpers.operate(::typeof(tanh),x::Number)=tanh(x)` to make my code work though.
