### ISSUE TITLE
Raviart-Thomas reffes for cubes/simplices in v0.15.0

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#471]
Work to be done before releasing v0.15.0

**Comment by jesusbonilla** [comment]
Right now Raviart-Thomas reffes seem to be working for cubes/simplices. However, there are some pending tasks:
- [ ] Avoid computing the transpose of the transpose, i.e., work directly with the transposed Jacobian.
- [ ] Optimize `get_dof_basis` by Implementing proper `return_cache` and `evaluate!` functions.
- [ ] Add a check to ensure we are using affine mappings at the functions evaluating the gradients, i.e. `@check isa(Jt,ConstantField)`. Before, an optimization for simplex meshes needs to be done.
- [ ] Refactor RaviartThomasRefFEs.jl to simplify notation.

**Comment by jesusbonilla** [comment]
Partially solved in PR #499
Opened issue #500 for remaining tasks.
