### ISSUE TITLE
Miscellaneous renaming tasks in v0.15.0

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/Gridap.jl#480]
- [x] `get_cell_nodes` -> `get_cell_node_ids`
- [x] `get_cell_id` -> `get_cell_to_bgcell`
- [x] ~**TO-THINK:** `get_cell_measure` -> ??? (` get_bgcell_measure`? perhaps too confusing)~
- [x] For `a::LazyArray`, `a.g` -> `a.maps`, `a.f` -> `a.args` **We can pospone this to a future release since they are private fields**
- [x] `get_cell_data` is a bit confusing, because you apply it to a `CellDatum`, but you do not get a `CellDatum` out of it. ~Perhaps `get_cell_array` or `get_cell_data_array`, or `get_cell_datum_array` less confusing.~ Use `get_data`.

**Comment by fverdugo** [comment]
Hi @amartinhuertas, have you had some time to do the renaming?

This and the work on reffes that @jesusbonilla is doing are the two major parts missing for the 0.15 release.

**Comment by amartinhuertas** [comment]
>Hi @amartinhuertas, have you had some time to do the renaming?

No. Deadline?

**Comment by fverdugo** [comment]
No deadline, but the sooner we have this, the sooner we can release and start building on top of Gridap@0.15 in the other repos.

Having the renaming for `get_cell_nodes` and `get_cell_id` is the most important (and fortunately the easy) part since they are public.

We can pospone the renaming of the fields in `LazyArray` (this is the difficult part) since they are private and thus can be done at any time.

**Comment by amartinhuertas** [comment]
Ok, I will do it now, then.

**Comment by amartinhuertas** [comment]
>We can pospone the renaming of the fields in LazyArray (this is the difficult part) since they are private and thus can be done at any time.

Yes, this is definitely more time-consuming. Ideally, this work should also rename the local variables which are used for aliasing these two member variables of LazyArray ...

**Comment by fverdugo** [comment]
done in PR #494

**Comment by fverdugo** [comment]
@amartinhuertas call it `get_data`

A `CellDatum` is just some data (the plain array) plus some metadata. So I think that `get_data` is OK.

**Comment by santiagobadia** [comment]
Renaming `get_cell_data` to `get_data` in PR #504

**Comment by santiagobadia** [comment]
Renaming `LazyArray` args in PR #506
