### ISSUE TITLE
Misc low-level, non-strategic observations on 0.15 release

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/Gridap.jl#493]
Hi @fverdugo, 

find below a list of misc low-level observations (nothing strategic) that I made while navigating through the kernel refactorization that goes into Gridap `v0.15`. If any of these observations imply further work, I can made it myself, but better If I can hear from your side before.

Thanks! @amartinhuertas

* In `CellField` constructors (`CellFields.jl` source file), what is the reason for using `s=size(get_cell_map(trian))` instead of `s=(num_cells(trian),)` ? In other words, in which scenarios the cell map can be a higher to one rank array different from the number of cells?

* In `CellField(f::Function,trian::Triangulation,domain_style::DomainStyle)`,  `domain_style` is not used. Why not? Should we remove the parameter?

* `TrialBasis`, `TestBasis`, and  `FEBasis` are not published (exported) by `Gridap.FESpaces`. `GenericCellBasis` (i.e., the one replaced by `FEBasis`, if I understand properly, was actually published by `Gridap.FESpaces` in previous releases).

* What is the performance impact of using `return_value` instead of `evaluate!` at several places  in those contexts in which a `Map`'s or `Field`'s cache is already available (e.g., in `return_cache(c::OperationMap,x...)` or `return_cache(c::OperationField,x::Point)`)?

* Should `CellQuadrature` data type provide a `get_weights()` function? I would need it in the Poisson Tutorial for developers in order to avoid accessing directly to a member variable of a data type.

* In `function lazy_map(::typeof(evaluate),::Type{T}, f::Fill, a::Fill...) where T` (`LazyArrays.jl`), `T` is NOT needed, right?

* Is it `a.value` the recommended way of accessing to the value of all entries of a `Fill` array `a` or is there a getter instead ? 

* Is it `a.parent` the recommended way of accessing the array to be transposed by `Transpose` or is there a getter instead ? 
  
* why `evaluate!(::Nothing, ::FieldGradient{1,Gridap.Polynomials.Monomial}, ::VectorValue{2,Int64})` not available?

* In order to reduce code replication in `ApplyOptimizations.jl` ... Is it possible to replace

```julia
function lazy_map(
  k::Broadcasting{typeof(∇)}, a::LazyArray{<:Fill{typeof(linear_combination)}})

  i_to_basis = lazy_map(k,a.f[2])
  i_to_values = a.f[1]
  lazy_map(linear_combination,i_to_values,i_to_basis)
end
```

by 

```julia
function lazy_map(
  k::Broadcasting{typeof(∇)}, a::LazyArray{<:Fill{typeof(linear_combination)}})
  lazy_map(∇,a)
end
```

???

* In this piece of code

```julia
function return_cache(f::Broadcasting,x::Union{Number,AbstractArray{<:Number}}...)
  s = map(_size,x)
  bs = Base.Broadcast.broadcast_shape(s...)
  T = return_type(f.f,map(testitem,x)...)
  N = length(bs)
  r = fill(testvalue(T),bs)
  cache = CachedArray(r)
  _prepare_cache!(cache,x...)
  cache
end

@inline function _prepare_cache!(c,x...)
  s = map(_size,x)
  bs = Base.Broadcast.broadcast_shape(s...)
  if bs != size(c)
    setsize!(c,bs)
  end
  c
end
```
why the call to `prepare_cache` is needed?

* Replace ...

  ```julia
  function _operate_cellfields(k::Operation,a...)
     b = _to_common_domain(a...)
     OperationCellField(k,b...)
   end
   ```

  by 
  
  ```julia
  function _operate_cellfields(k::Operation,a::CellField...)
    b = _to_common_domain(a...)
    OperationCellField(k,b...)
  end 
  ```

  ???

* In the following piece of code: 

```julia
struct OperationCellField{DS} <: CellField
  op::Operation
  args::Tuple
  trian::Triangulation
  domain_style::DS
  function OperationCellField(op::Operation,args::CellField...)

    @assert length(args) > 0
    trian = get_triangulation(first(args))
    domain_style = DomainStyle(first(args))
    @check all( map(i->DomainStyle(i)==domain_style,args) )
    @check all( map(i->have_compatible_domains(get_triangulation(i),trian),args) )

    if num_cells(trian)>0
      x = _get_cell_points(args...)
      try
         ax = map(i->i(x),args)
         axi = map(first,ax)
         r = Fields.BroadcastingFieldOpMap(op.op)(axi...)
      catch
        @unreachable """\n
        It is not possible to perform operation $(op.op) on the given cell fields.

        See the catched error for more information.
        """
      end
    end

    new{typeof(domain_style)}(op,args,trian,domain_style)
  end
end
```

Isn't a bit of brute force doing 

```julia
         ax = map(i->i(x),args)
         axi = map(first,ax)
         r = Fields.BroadcastingFieldOpMap(op.op)(axi...)
```
to check that everything is compatible? Perhaps to deactivate it in release mode?

* In many context the gradient cannot by applied to an array of fields, except in some circumstances, e.g., `function lazy_map(
  ::typeof(gradient), a::LazyArray{<:Fill{typeof(linear_combination)}})`. Why these exceptions are allowed? Are they strictly necessary? If not necessary, perhaps we are somehow confusing the user of Gridap.

* In 

```
struct BroadcastOpFieldArray{O,T,N,A} <: AbstractArray{T,N}
  op::O
  args::A
  function BroadcastOpFieldArray(op,args::Union{Field,AbstractArray{<:Field}}...)
    fs = map(testitem,args)
    T = return_type(Operation(op),fs...)
    s = map(size,args)
    bs = Base.Broadcast.broadcast_shape(s...)
    N = length(bs)
    A = typeof(args)
    O = typeof(op)
    new{O,T,N,A}(op,args)
  end
end
```
should be `s = map(_size,args)`?

**Comment by fverdugo** [comment]
Hi @amartinhuertas, thanks for your comments. Perhaps better a face-to-face meeting to discuss this.

**Comment by amartinhuertas** [comment]
> Hi @amartinhuertas, thanks for your comments. Perhaps better a face-to-face meeting to discuss this.

Yes. That would be perfect. I have other questions as well. What about Tuesday? Are u available?

**Comment by fverdugo** [comment]
What about Wednesday? Tuesday holiday here.

**Comment by amartinhuertas** [comment]
> What about Wednesday? Tuesday holiday here.

Ok deal. Time?

**Comment by fverdugo** [comment]
7:30 BCN ?

**Comment by amartinhuertas** [comment]
Yes. Wednesday 09th, 7:30AM, BCN time. FYI, @santiagobadia will join the meeting as well.
