### ISSUE TITLE
Norm not defined for Tensor Valued Spaces

### ISSUE THREAD

**Issue by Paulms** [gridap/Gridap.jl#536]
In the p-Laplacian tutorial you can use norm∘∇(u). If you try to do the same: norm∘T where T belongs to a Tensor Valued Space (like, ```TestFESpace(model,ReferenceFE(lagrangian,TensorValue{2,2,Float64,4},order),conformity=:L2)```), it doesn`t work. Adding the method: ```norm(u::MultiValue{Tuple{D1,D2}}) where {D1,D2} = sqrt(inner(u,u)) ```  in TensorValues/Operations.jl seems to solve the issue.

PD: It is useful for instance when implementing the dual-mixed method for p-Laplacian.

**Comment by santiagobadia** [comment]
Hi @Paulms you can create a PR with the missing method if you like.

**Comment by Paulms** [comment]
Ok, I create the PR: https://github.com/gridap/Gridap.jl/pull/538
