### ISSUE TITLE
Different tensor types should not compare equal

### ISSUE THREAD

**Issue by eschnett** [gridap/Gridap.jl#558]
I find this:
```Julia
julia> VectorValue(1,2,3) == SymTensorValue(1,2,3)
true
```

This shouldn't be the case; 3d vectors are different from 2d tensors...

**Comment by eschnett** [comment]
I think that
```
(==)(a::MultiValue,b::MultiValue) = a.data == b.data
```
should instead be
```
(==)(a::T,b::T) where {T <: MultiValue} = a.data == b.data
```
together with appropriate promotion rules. Alternatively, the comparison function could explicitly compare the tensor types (`VectorValue`, `TensorValue`, etc) of the arguments.

**Comment by fverdugo** [comment]
Thanks for noting this @eschnett. You are right!
Can you open please a PR with the proposed changes?
