### ISSUE TITLE
Including partial derivatives in variational formulation

### ISSUE THREAD

**Issue by urbainvaes** [gridap/Gridap.jl#561]
Is there a way of using partial derivatives individually (not only as part of the gradient) when defining a variational formulation? I'd like to use Gridap to solve a hypoelliptic PDE posed on a two-dimensional domain, with second derivatives only with respect to the variable y.

**Comment by fverdugo** [comment]
You need to compute ∇(u) or ∇∇(a) and extract the component you want

Eg.
```
∂y(a::CellField) = Operation(_get_y)(∇(a))
_get_y(a::VectorValue) = a[2]

# then you can write in the weak form
a(u,v) = ∂y(u)*∂y(v)
```

(I know that computing he hole gradient is sub-optimal, but it is the easy way to implement this)

**Comment by urbainvaes** [comment]
Thank you very much for your quick response! Works perfectly! :)
