### ISSUE TITLE
assert in `ConformingFESpaces.jl`correct?

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/Gridap.jl#569]
Hi @fverdugo  .... is the following assert in `ConformingFESpaces.jl` correct?

https://github.com/gridap/Gridap.jl/blob/bcaa82a2233421f92d4ef184dc33395837177435/src/FESpaces/ConformingFESpaces.jl#L80

It is always evaluated to true ... We can either remove the assert or replace by the correct one, right? If the second option, do you know which should be the assertion to check here?

**Comment by amartinhuertas** [comment]
Perhaps ... `@assert length(cell_fe.cell_ctype) == length(cell_conf.cell_ctype)` ?

**Comment by fverdugo** [comment]
Yes! It's a typo. Good catch

**Comment by amartinhuertas** [comment]
PR https://github.com/gridap/Gridap.jl/pull/570 opened to fix this issue
