### ISSUE TITLE
Obsolete comment (and function?) in FESpaceInterfaces.jl

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/Gridap.jl#593]
Hi @fverdugo, 

while digging in the internals of Gridap.jl, I just found the following obselete comment:

https://github.com/gridap/Gridap.jl/blob/7414a4e6c83510e0bf20d0aeaa6e651e2fe02e30/src/FESpaces/FESpaceInterface.jl#L211

(MultiFieldFEBasis no longer exists after refactorization). I wonder whether the function associated to the function is still needed (no idea, I did not try to determine this, just reporting). 

@amartinhuertas

**Comment by amartinhuertas** [comment]
A follow-up on this issue. The function mentioned seems to be being executed from the tests:

https://codecov.io/gh/gridap/Gridap.jl/src/7414a4e6c83510e0bf20d0aeaa6e651e2fe02e30/src/FESpaces/FESpaceInterface.jl

Thus it seems to be needed. It would be great to also know from where it is being called, but I think this is not possible with codecov.io ...

**Comment by fverdugo** [comment]
> (MultiFieldFEBasis no longer exists after refactorization). I wonder whether the function associated to the function is still needed (no idea, I did not try to determine this, just reporting).

Replace

"We implement this for FEBasis since MultiFieldFEBasis will use this code"

by 

"We implement this for FEBasis since extensions of FEBasis might want to re-use this code"


Eg,  we have an extension of FEBasis in a GridapODEs.

**Comment by amartinhuertas** [comment]
Done in PR #595
