### ISSUE TITLE
Help with understanding `lazy_map` overload

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/Gridap.jl#594]
Hi @fverdugo, 

I need your help! 

do you know which is the rationale behind the following `lazy_map` overload? 

https://github.com/gridap/Gridap.jl/blob/7414a4e6c83510e0bf20d0aeaa6e651e2fe02e30/src/Arrays/PosNegReindex.jl#L64

I do not see why it is implemented like that. In particular, why should one `Reindex` the `x` array? (as far as I understand an array with evaluation `Points`). It makes more sense to me to be implemented like that:

```julia
function Gridap.Arrays.lazy_map(::typeof(evaluate),::Type{T},a::Gridap.Arrays.LazyArray{<:Fill{<:Gridap.Fields.PosNegReindex}},x::AbstractArray) where T
  apos = a.maps.value.values_pos
  aneg = a.maps.value.values_neg
  i_to_iposneg = a.args[1]
  #ipos_to_i, ineg_to_i = pos_and_neg_indices(i_to_iposneg)
  #xpos = lazy_map(Reindex(x),ipos_to_i)
  #xneg = lazy_map(Reindex(x),ineg_to_i)
  cpos = lazy_map(evaluate,apos,x)#xpos)
  cneg = lazy_map(evaluate,aneg,x)#xneg)
  lazy_map(Gridap.Fields.PosNegReindex(cpos,cneg),T,i_to_iposneg)
end
```
Sure I am missing something. BTW, FYI, I double checked that is being executed by the tests: https://codecov.io/gh/gridap/Gridap.jl/src/7414a4e6c83510e0bf20d0aeaa6e651e2fe02e30/src/Arrays/PosNegReindex.jl

Thanks! @amartinhuertas

**Comment by fverdugo** [comment]
Hi @amartinhuertas I would say that your proposal should not work in general.

Here there are different sets of indices

1. Vectors `a` and `x` are indexed with the same index, namely `i`
2. `apos` is indexed with another index, namely `ipos`
3. `aneg` is indexed with another index, namely `ineg`

thus you cannot call 
```julia
cpos = lazy_map(evaluate,apos,x)
```
since lazy_map requires arrays with the same indices (at least the same linear indices).

**Comment by fverdugo** [comment]
BTW, this optimization takes place e.g. when using extended FE spaces, e.g. in FSI problems.

**Comment by amartinhuertas** [comment]
It turns out that, after a huge refactorization of my code, am no longer in need of this feature. Closing the issue.
