### ISSUE TITLE
Inconsistency among eltype of LazyArray and the type of the entry returned by get_index

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/Gridap.jl#603]
Hi @fverdugo, 

I think I have found a subtle issue (BUG?) in Gridap's kernel. Find below a not minimum working example in which the issue is reproduced. In particular, the assertion below fails, and it should not because the invariant of the eltype of a LazyArray being equal to the type of the entry returned by `get_index` cannot be violated; see, e.g.

  https://github.com/gridap/Gridap.jl/blob/1a009fb899afa531b78576f6c3b9895bc11b1ee5/src/Arrays/LazyArrays.jl#L226

```julia
using Gridap
using FillArrays
using Gridap.Geometry

# Geometry part
D=2
domain  = (0,1,0,1)
cells   = (1,2)
model   = CartesianDiscreteModel(domain,cells)
model_Γ = BoundaryDiscreteModel(Polytope{D-1},model,collect(1:num_facets(model)))
btrian  = BoundaryTriangulation(model)

order  = 0
reffeᵤ = ReferenceFE(raviart_thomas,Float64,order)
reffeₚ = ReferenceFE(lagrangian,Float64,order)
reffeₗ = ReferenceFE(lagrangian,Float64,order)

# Define test FESpaces
V = TestFESpace(model  , reffeᵤ; conformity=:L2)
Q = TestFESpace(model  , reffeₚ; conformity=:L2)
M = TestFESpace(model_Γ, reffeₗ; conformity=:L2, dirichlet_tags=[7,8])
Y = MultiFieldFESpace([V,Q,M])

# Create trial spaces
U = TrialFESpace(V)
P = TrialFESpace(Q)
L = TrialFESpace(M,p)
X = MultiFieldFESpace([U, P, L])

xh = get_trial_fe_basis(X)
uh,_,_ = xh

uh_btrian=Gridap.CellData.get_data(
            Gridap.CellData.change_domain(uh,btrian,DomainStyle(uh))) 
uh_btrianx=lazy_map(evaluate,uh_btrian,[ [Point(0)] for i=1:length(uh_btrian)])
@assert eltype(uh_btrianx) == typeof(uh_btrianx[1])
```

After a long while spent in debugging (I found this to be quite difficult to spot), I think I have found where the issue stems from. In particular, it can be spot using the following debugger call 

```julia
VSCodeServer.@enter evaluate(uh_btrian.parent.maps[1],uh_btrian.parent.args[1][1],uh_btrian.parent.args[2][1])
```

putting a breakpoint in this particular line:

https://github.com/gridap/Gridap.jl/blob/1a009fb899afa531b78576f6c3b9895bc11b1ee5/src/Fields/ArrayBlocks.jl#L488

There, `A<:LinearAlgebra.Transpose`. The application of a `Broadcasting(∘)` Map to an instance of this type + a single Field, translates into the Julia native `broadcast` here

https://github.com/gridap/Gridap.jl/blob/1a009fb899afa531b78576f6c3b9895bc11b1ee5/src/Arrays/Maps.jl#L153

This transforms the lazy Transpose array into an instance of the standard `Matrix{A}` type, ultimately causing the asser to fail (Btw, which is the impact of this into memory allocation? Not sure if we end up having per-cell memory allocation)

What do you think? How can we solve this? Perhaps adding this specialization? (perhaps it can be solved earlier in the hierarchy of calls, didnt though much about possible solutions).

```julia
@inline evaluate!(cache,f::Broadcasting,x::Transpose,y)=Transpose(evaluate!(cache,f,x.parent,y))
```

**Comment by amartinhuertas** [comment]
Remark from @fverdugo: *"el error que dices, normalmente se soluciona definiendo return_value  para el Map+args que te estan dando problemas"*

**Comment by amartinhuertas** [comment]
A follow-up on this issue. It turns out that the working example above does not actually reproduce the issue (sorry about that). The assert statement was wrong (`@assert eltype(uh_btrianx) == eltype(uh_btrianx[1])` -> `@assert eltype(uh_btrianx) == typeof(uh_btrianx[1])`). After fixing it, it returns `true`.  It seems that I will have to work a little bit more to get a working example that reproduces the issue.

**Comment by amartinhuertas** [comment]
Ok, after a little twist, I got the WE right. See below. 

**CRUCIAL NOTE: In order to let this code work, the modification discussed here https://github.com/gridap/Gridap.jl/issues/594#issuecomment-843951712 is required!**

```julia
using Gridap
using FillArrays
using Gridap.Geometry
using ExploringGridapHybridization

# Geometry part
D=2
domain  = (0,1,0,1)
cells   = (1,2)
model   = CartesianDiscreteModel(domain,cells)
model_Γ = BoundaryDiscreteModel(Polytope{D-1},model,collect(1:num_facets(model)))
btrian  = BoundaryTriangulation(model)

order  = 0
reffeᵤ = ReferenceFE(raviart_thomas,Float64,order)
reffeₚ = ReferenceFE(lagrangian,Float64,order)
reffeₗ = ReferenceFE(lagrangian,Float64,order)

# Define test FESpaces
V = TestFESpace(model  , reffeᵤ; conformity=:L2)
Q = TestFESpace(model  , reffeₚ; conformity=:L2)
M = TestFESpace(model_Γ, reffeₗ; conformity=:L2, dirichlet_tags=[7,8])
Y = MultiFieldFESpace([V,Q,M])

# Create trial spaces
U = TrialFESpace(V)
P = TrialFESpace(Q)
L = TrialFESpace(M)
X = MultiFieldFESpace([U, P, L])

xh = get_trial_fe_basis(X)
uh,_,_ = xh

uh_btrian=Gridap.CellData.get_data(
            Gridap.CellData.change_domain(uh,btrian,DomainStyle(uh))) 

posneg_uh_btrian=lazy_map(Gridap.Arrays.PosNegReindex(uh_btrian,uh_btrian),[1,-2])

posneg_uh_btrianx=lazy_map(evaluate,posneg_uh_btrian,[ [Point(0)] for i=1:length(posneg_uh_btrian)])
@assert eltype(posneg_uh_btrianx) == typeof(posneg_uh_btrianx[1])
```

**Comment by amartinhuertas** [comment]
> Remark from @fverdugo: "el error que dices, normalmente se soluciona definiendo return_value para el Map+args que te estan dando problemas"

I tried, but could not solve the issue using an specialized definition of `return_value`. Indeed, I am not sure if it is possible. The `eltype` of the `posneg_uh_btrianx` LazyArray is ultimately decided by a call to `get_index` with `uh_btrian`. This in turn calls the pair of `return_cache`/`evaluate!` functions pointed above in `ArrayBlocks.jl`.

Thus, I could solve (workaround?) the problem using the following function definition (not currently in Gridap):

```
@inline Gridap.Arrays.evaluate!(cache,f::Gridap.Fields.Broadcasting,
                 x::Transpose,y::Gridap.Fields.Field)=Transpose(evaluate(f,x.parent,y))
```
(I did not check whether this breaks anything within Gridap, only that my particular issue is solved).

It might help to have a meeting to talk about this issue.

**Comment by amartinhuertas** [comment]
>Is the error introduced by this modification?

Yes. Do you see anything wrong there that might be causing the issue? Perhaps to use the same `T` at the last call to `lazy_map`?

**Comment by amartinhuertas** [comment]
Please note that, without the modification, the following line fails:

```julia
posneg_uh_btrian=lazy_map(Gridap.Arrays.PosNegReindex(uh_btrian,uh_btrian),[1,-2])
```

**Comment by fverdugo** [comment]
> Please note that, without the modification, the following line fails:

OK! this looks more interesting.  What is the length of `uh_btrian`?  If it is 2 or larger, it should work unless there is a bug.

**Comment by amartinhuertas** [comment]
> What is the length of uh_btrian?

I has as many entries as facets there are in the boundary triangulation (6 in this case).

> If it is 2 or larger, it should work unless there is a bug.

What do you mean by this. Not sure if I understand. The current version of the function at hand, i.e., 

https://github.com/gridap/Gridap.jl/blob/7414a4e6c83510e0bf20d0aeaa6e651e2fe02e30/src/Arrays/PosNegReindex.jl#L64

fails, because [-1,2] is not an "exhaustive" mapping, i.e., 

https://github.com/gridap/Gridap.jl/blob/7414a4e6c83510e0bf20d0aeaa6e651e2fe02e30/src/Arrays/PosNegReindex.jl#L112

This is why i had to modify it as pointed out in #594

**Comment by fverdugo** [comment]
Now I remember! 

This check is needed since all the PosNegReindex machinery is designed, implemented, and optimized assuming that `i_to_iposneg` defines a PARTITION of a 1:n range into 2 sets. E.g., DOF ids partitioned into free/dirichlet or cell ids partitioned into void/active.  Thus, the use of this `Map` is restricted to this case for now.

Options:
1. Generalize  `PosNegReindex`. Careful work required and I don't know if this can be done without performance hit.
2. Try to implement your code without using `PosNegReindex`, or using it only in the way it's currently is designed for.

In which context do you need to call `PosNegReindex` ?

**Comment by fverdugo** [comment]
I would clearly go for 2.

**Comment by amartinhuertas** [comment]
> This check is needed since all the PosNegReindex machinery is designed, implemented, and optimized assuming that i_to_iposneg defines a PARTITION of a 1:n range into 2 sets. 

Ok, this is what I could grasp reading the code. From your experience, what is the peformance hit incurred by not using this optimization? Anyway, as you suggest, I think I can bypass PosNegReindex (see below for more details).

> In which context do you need to call PosNegReindex ?

Good question. We have a cell-wise array X with the per-cell "signed" (more in the next sentence) global facet identifiers. For each cell K, and facet F in \partial K, if K is the owner of F, then K stores the global identifier of the facet, otherwise the global identifier with the sign flipped (i.e., a negative global identifier).

Then we want to do the following (lazily): 
  1. Restrict X, for all cells, to the facet located in a given local position (i.e., if there are 4 faces per cell, local position goes from 1 to 4).
  2. Use the resulting cell-wise array from 1. + PosNegReindex to extract data from a pair of arrays of length number of cells with the facet data for the owner cells (positive index) and non-owner cells (negative index). 

> Try to implement your code without using PosNegReindex, or using it only in the way it's currently is designed for.

Ok, I have done this. In particular, I have replaced:

```julia
function _get_local_facet_cell_wise_array(tpa,
                                           tma,
                                           signed_cell_wise_facets_ids,
                                           facet_lid)
indices=lazy_map((x)->x[facet_lid],signed_cell_wise_facets_ids)
lazy_map(Gridap.Arrays.PosNegReindex(tpa,tma),indices)
end 
```

by

```julia
function _get_local_facet_cell_wise_array(tpa,
                                          tma,
                                          signed_cell_wise_facets_ids,
                                          facet_lid)
  Gridap.Helpers.@check length(tpa) == length(tma)
  tpa_tma=Gridap.Arrays.AppendedArray(tpa,tma)
  function transform_signed_index_to_appended_index(x)
      signed_index=x[facet_lid]
      Gridap.Helpers.@check signed_index != 0
      if (signed_index>0)
        return signed_index
      else
        return length(tpa)+abs(signed_index)
      end
  end
  indices=lazy_map(transform_signed_index_to_appended_index,
                   signed_cell_wise_facets_ids)
  lazy_map(Gridap.Arrays.Reindex(tpa_tma),indices)
end
```

With the latter solution, it seems that I do not longer need the following method definition 

```julia
@inline Gridap.Arrays.evaluate!(cache,f::Gridap.Fields.Broadcasting,
                 x::Transpose,y::Gridap.Fields.Field)=Transpose(evaluate(f,x.parent,y))
```

to get the working example working.

Do you fully understand why it was needed in the first example? I feel there is something wrong with the default definnition of Broadcasting with a Lazy tranpose array of fields, but I cannot fully express my concerns.
