### ISSUE TITLE
Nnz and structure of matrices

### ISSUE THREAD

**Issue by tmigot** [gridap/Gridap.jl#612]
In algorithms where we compute several times the jacobian and/or the hessian of a problem with different values of `x`, it would be more efficient to allocate once the structure of the matrix, i.e. the rows and columns indices of the non-zeros elements.

The functions `_jacobian` and `_hessian` are computing the matrix directly. It would be great to also have additional functions computing the number of non-zeros elements of the computed matrix, the structure, and the values.
What do you think?

I can help and suggest a PR if needed.

**Comment by fverdugo** [comment]
Hi @tmigot !

these functions compute the cell-wise contributions to the jacobian and hessian. i.e., they are elemental (dense) matrices. If you want the global sparse matrix, you need to assemble these contributions. 

Note that the assembly machinery allows one to create the global sparse matrix from scratch or to assemble in-place on an existing sparse matrix

**Comment by tmigot** [comment]
Sorry for the late reply, let me just be concrete to be sure I understand correctly. I usually means the global sparse matrix. I believe in practice we would ideally want:
- the number of non-zeros elements without having to compute (and therefore allocate) the whole sparse matrix.
- get the coordinates of the non-zeros elements without computing the values of the global matrix.
- In-place version for the values of the sparse matrix. Say, `vals` is a vector of length `nnzh` (number of non-zeros elements in the matrix - there might be duplicates at this point before forming the matrix) and the in-place jac vals would allocate in this vector.

The motivation is to reuse the memory when re-computing the matrices in an iterative method. Would any of those be useful? I had some drafts of such functions in 0.14.2, but these could be adapted easily I think.

**Comment by tmigot** [comment]
I finally used the functions:
`Gridap.FESpaces.count_matrix_nnz_coo(assem, matdata_y)`
`Gridap.FESpaces.allocate_coo_vectors`
`Gridap.FESpaces.fill_matrix_coo_numeric!`

**Comment by fverdugo** [comment]
For the record, these functions have been replaced by other ones in Gridap 0.16.
