### ISSUE TITLE
Doubts in regards to some functions in `ArrayBlocks.jl`

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/Gridap.jl#619]
Hi @fverdugo, @santiagobadia 

I have a pair of questions regarding some functions in `ArrayBlocks.jl`. (I had to take a look at the file in some detail for the work I am currently doing).

1. I have the impression that some of the implementations of `BroadcastingFieldOpMap` (e.g., [this one](https://github.com/gridap/Gridap.jl/blob/a52bc10503f77f700b7cee096c7311aebc131cee/src/Fields/ArrayBlocks.jl#L763))  are only well-defined when the underlying operation fulfills `op(a,0)=0`, as e.g., `*`.  For example, such an implementation would not reproduce the following Julia native behaviour:
```
julia> broadcast(-,[0 0 1],[0,0,1])
3×3 Matrix{Int64}:
  0   0  1
  0   0  1
 -1  -1  0
```
Is that true?  If, yes, should we add a check on the requirements of the operation for that particular functions as currently implemented? Anyway, I guess that in finite elements this case does not happen, as the test functions are always multiplying the equations of the strong form. 

2. In the following function: 

https://github.com/gridap/Gridap.jl/blob/a52bc10503f77f700b7cee096c7311aebc131cee/src/Fields/ArrayBlocks.jl#L710

when the code enters this line:

https://github.com/gridap/Gridap.jl/blob/a52bc10503f77f700b7cee096c7311aebc131cee/src/Fields/ArrayBlocks.jl#L726

and `A` is an `AbstractArray` and `B` is an `ArrayBlock`, the cache returned here:

https://github.com/gridap/Gridap.jl/blob/a52bc10503f77f700b7cee096c7311aebc131cee/src/Fields/ArrayBlocks.jl#L728

is `nothing`. Thus, the following line:

https://github.com/gridap/Gridap.jl/blob/a52bc10503f77f700b7cee096c7311aebc131cee/src/Fields/ArrayBlocks.jl#L203

fails. Should this case be supported? If not, its ok, I think I can bypass it. But anyway, then I guess that we should change the `evaluate!` signatures by:

```julia
function evaluate!(cache,::ZeroBlockMap,a::AbstractArray,b::AbstractArray) 
```

```julia
function evaluate!(cache,::ZeroBlockMap,a::ArrayBlock,b::ArrayBlock)
```

(BTW, what is the role of the comma after `cache`?) What is the motivation behind the current `evaluate!` signatures? 

Let me know your thoughs! Thanks!

**Comment by fverdugo** [comment]
> I have the impression that some of the implementations of BroadcastingFieldOpMap (e.g., this one) are only well-defined when the underlying operation fulfills op(a,0)=0, as e.g., *. For example, such an implementation would not reproduce the following Julia native behaviour:

`BroadcastingFieldOpMap` is intentionally not a general broadcast. The general broadcast is `Broadcasting`. The former assumes a number of pre-conditions that allow one to implement the block-related things in an efficient way. These preconditions are always fulfilled when `BroadcastingFieldOpMap` comes from a field operation in the weak form. I.e., you only operate test and trial shape funs via a product, and you only operate test and test (resp. trial and trial) via a linear operation. This, allows one to know in advance the non-zero block structure resulting from the operation. There is no way of figuring out the non-zero block structure for the general broadcasting for any given operation.

**Comment by amartinhuertas** [comment]
> BroadcastingFieldOpMap is intentionally not a general broadcast. The general broadcast is Broadcasting. The former assumes a number of pre-conditions that allow one to implement the block-related things in an efficient way. These preconditions are always fulfilled when BroadcastingFieldOpMap comes from a field operation in the weak form. I.e., you only operate test and trial shape funs via a product, and you only operate test and test (resp. trial and trial) via a linear operation. This, allows one to know in advance the non-zero block structure resulting from the operation. There is no way of figuring out the non-zero block structure for the general broadcasting for any given operation.

Ok, makes sense. What about point 2.?
