### ISSUE TITLE
Element-specific material properties

### ISSUE THREAD

**Issue by mohamed82008** [gridap/Gridap.jl#633]
Is it possible to have element specific material properties? I saw the use of `tags` for multiple materials. Can the element-specific vector be a vector of continuous values?

**Comment by oriolcg** [comment]
Hi @mohamed82008 , you can have element specific material properties, check out this tutorial on adding a damage model: https://gridap.github.io/Tutorials/stable/pages/t010_isotropic_damage/#Tutorial-10:-Isotropic-damage-model-1. You can also make your material properties depend on a continuous function in space (and time).

Does it answer your question?

**Comment by mohamed82008** [comment]
You mean using the `r = CellState(r_0,dΩ)`?

**Comment by mohamed82008** [comment]
Is there a way to access the element index from within the weak form?

**Comment by fverdugo** [comment]
@mohamed82008 this can be done very easily.

Say you have `cell_param::Vector{T}` a vector holding a parameter of type `T<:Number` for each cell of your triangulation `Ω`. Then, simply build `τ = CellField(cell_param,Ω)`. Now you can use `τ` in your weak form just like any other variable. E.g. `a(u,v) = ∫( ∇(v)⋅(τ*∇(v) )dΩ`.

**Comment by mohamed82008** [comment]
Thanks @fverdugo! Now I can do element-based and node-based topology optimization in Gridap!
