### ISSUE TITLE
Access the coordinate x in the weak form

### ISSUE THREAD

**Issue by mohamed82008** [gridap/Gridap.jl#635]
Is it possible to access the coordinate in the weak form?

**Comment by oriolcg** [comment]
Yes, you can write a weak form like:
```julia
μ(x::VectorValue) = x[1]+x[2]
a(u,v) = ∫( μ*∇(v)⋅∇(u) )dΩ
```

Is that what you are looking for?

**Comment by mohamed82008** [comment]
Ah perfect! Yes this is what I am looking for. Thanks!
