### ISSUE TITLE
Rationale behind `DiscreteModelPortion` inheritance relation

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/Gridap.jl#644]
Hi @fverdugo,

is there a rationale behind this inheritance relationship?

https://github.com/gridap/Gridap.jl/blob/master/src/Geometry/DiscreteModelPortions.jl#L4

I would say it is a typo, isn't? Perhaps I am missing something ...

Let me know your thoughts!

**Comment by fverdugo** [comment]
It looks it should be `<: DiscreteModel{Dc,Dc}` right?

**Comment by amartinhuertas** [comment]
Yes, I think so. I will PR this change, ok?

**Comment by fverdugo** [comment]
OK!

**Comment by fverdugo** [comment]
with some test calling num_cell_dims, num_point_dims

**Comment by amartinhuertas** [comment]
sure ... this is what I am writing now ...

**Comment by amartinhuertas** [comment]
Worked it out in PR https://github.com/gridap/Gridap.jl/pull/645
