### ISSUE TITLE
Complex PDEs? 

### ISSUE THREAD

**Issue by volkerkarle** [gridap/Gridap.jl#658]
Dear developers,

Would this also be the right library to work on a complex solver (for a PDE such as Gross–Pitaevskii equation)?

Thanks,

v.

**Comment by fverdugo** [comment]
See e.g. https://gridap.github.io/Tutorials/dev/pages/t012_emscatter/#Tutorial-12:-Electromagnetic-scattering-in-2D-1

We setup a complex-valued finite element space there.
