### ISSUE TITLE
Homogenize node_and_comp_to_dof

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#66]
The types `LagrangianDOFBasis` and `CLagrangianFESpace` uses different strategies to represent the relation between  nodes, components, and dofs (see the field   `node_and_comp_to_dof` in both structs). 

It would be nice to homogenize things. I would adopt the strategy of `CLagrangianFESpace`

**Comment by santiagobadia** [comment]
Ok, first I need to understand what is the reason for `CLagrangianDOFBasis`, it is in my list of questions.

**Comment by fverdugo** [comment]
Done in v0.7.0. Closing.
