### ISSUE TITLE
How to compute the "change of surface" for facet integration in arbitrary dimensions?

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#67]
Given the D-1 tangent vectors  (i.e. the Jacobian of a geomap from D-1 to D dimensions) how to compute the scalar value representing the corresponding "change of surface" ?

In D=3, I am taking the 2-norm of the cross product of the D-1 tangent vectors

In D=2, I am taking the 2 norm of the tangent vector

I even have a formula for D=4....

But, how to do it in general? is there any way?

**Comment by santiagobadia** [comment]
My first intuition, compute the det of the Jacobian of the transformation with an extra row being the unit normal, and take absolute value. Given a manifold M of dimension d-1, the Jacobian of the map from R^ (d-1) into M provides a rectangular Jacobian of dim (d-1)xd. If we append the unique (up to the sign) normal vector, we have a squared Jacobian. If we take its determinant and absolute value, we have a measure of the "surface".

**Comment by santiagobadia** [comment]
Replace |det J| by  sqrt(det J^T J)

**Comment by fverdugo** [comment]
Nice! 

This is the missing generic implementation of function `meas`.

 (I would keep our current specializations for squared jacobians and also for changes of surface in 2D and 3D)
