### ISSUE TITLE
Remove FESolver and derived types

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#706]
FESolver et al. are no needed and can be removed to simplify the code.

Since PR #705 it is not needed to use FE solvers in the user code i.e.

```julia
op = AffineFEOperator(...)
solver = LinearFESolver(LUSolver())
uh = solve(solver,op)
```
Can be written as 
```julia
op = AffineFEOperator(...)
solver = LUSolver()
uh = solve(solver,op)
```
We can also remove them from the library completely in the next breaking release.

**Comment by fverdugo** [comment]
To check if removing of `FESolver` will cause trouble in `GridapODEs` cc @oriolcg

**Comment by oriolcg** [comment]
> To check if removing of `FESolver` will cause trouble in `GridapODEs` cc @oriolcg

It should be fine. In `GridapODEs` we have `TransientFESolver` that receives an `ODESolver`. Each `ODESolver` calls `solve!` using a `NonlinearSolver` so no `FESolver` involved. In any case, we could also remove the `TransientFESolver` there to keep things aligned with Gridap. I'll take care of that.
