### ISSUE TITLE
LU solver with cache

### ISSUE THREAD

**Issue by LaurentPlagne** [gridap/Gridap.jl#707]
Hi, 
I try to use gridap with a time loop and the default linear solver (lu).
It seems that the LU factorization is done each time because newmatrix is set to true:

function solve!(x::AbstractVector,ls::LinearSolver,op::AffineOperator,cache)
  newmatrix = true
  solve!(x,ls,op,cache,newmatrix)
  cache
end

any hint ?

**Comment by oriolcg** [comment]
Hi @LaurentPlagne,  

In [GridapODEs.jl](https://github.com/gridap/GridapODEs.jl) we have some ODE solvers that re-use the factorization. You can take a look at how this can be done in this function: https://github.com/gridap/GridapODEs.jl/blob/710f76f283f9333c306517207adfaa1846d004d3/src/ODETools/AffineThetaMethod.jl#L42 or here: https://github.com/gridap/GridapODEs.jl/blob/710f76f283f9333c306517207adfaa1846d004d3/src/ODETools/ConstantNewmark.jl#L1

Probably some of the tools given in `GridapODEs` would also work for your problem. For instance, if you want to use the Theta-method with constant matrix, you could do something like what is done in this test: https://github.com/gridap/GridapODEs.jl/blob/master/test/TransientFEsTests/ConstantFEOperatorsTests.jl

**Comment by LaurentPlagne** [comment]
Hi @oriolcg,
thank you very much for your reply and the links to GridapODEs.jl

Before I dive in this time integration layer, I still wonder why the boolean `newmatrix` arg is unconditionnaly set to true.

It seems that the solve! function docstring indicates that one can pass a cache extra argument to prevent this passing from
```
solver = LinearFESolver()
...
cache=nothing
for n in 1:nT
   ...
   uₙ₊₁,cache=solve!(uₙ₊₁, solver, op,cache)
   ...
end
```

and following the code execution I encouter the LinearSolver.jl functions

```
function solve!(x::AbstractVector,ls::LinearSolver,op::AffineOperator,cache)
  newmatrix = true ##LP not an option
  solve!(x,ls,op,cache,newmatrix)
  cache
end
```
calling
```
function solve!(
  x::AbstractVector,ls::LinearSolver,op::AffineOperator,cache,newmatrix::Bool)
  A = op.matrix
  b = op.vector
  ns = cache
  if newmatrix
    numerical_setup!(ns,A) #new factorization 
  end
  solve!(x,ns,b)
  cache
end
```

Again, thank you very much for your previous answer and I guess that I am doing something wrong in my naive approach.

P.S.1 For gridap questions like this one, what is the best channel : direct questions on Discourse or  gihub _issues_ ?
P.S.2 Are you in a stage where you encourage external users to use gridap or you are more in a fast development stage where you are focusing on a small team both using and developing gridap ?

Best,
Laurent

**Comment by fverdugo** [comment]
Hi @LaurentPlagne !

Consider these scenarios

## Scenario 1

Solve a collection of systems `A*x_i==b_i` for the same matrix `A` and several rhs `b_i`. We can reuse the numerical setup of the solver since the matrix does not change.

### Option 1 (recommended)
```julia
ls = LUSolver() # Or any other object implementing the linear solver interface of Gridap
ss = symbolic_setup(ls,A)
ns = numerical_setup(ss,A)
x = similar(b_1)
solve!(x,ns,b_1)
solve!(x,ns,b_2)
solve!(x,ns,b_3)
solve!(x,ns,b_4)
```
### Option 2 
```julia
ls = LUSolver() # Or any other object implementing the linear solver interface of Gridap
x = similar(b_1)
newmatrix = false
op = AffineOperator(A,b_1)
cache = solve!(x,ls,op,nothing)
op = AffineOperator(A,b_2)
solve!(x,ls,op,cache,newmatrix)
op = AffineOperator(A,b_3)
solve!(x,ls,op,cache,newmatrix)
op = AffineOperator(A,b_4)
solve!(x,ls,op,cache,newmatrix)
```

## Scenario 2

Solve a collection of systems `A_i*x_i==b_i` for several  matrices`A_i` and several rhs `b_i`, **but all matrices ` A_i` have the SAME sparsity pattern**.  We CANNOT reuse the numerical setup, but we CAN reuse the symbolic setup of the solver since the matrix sparsity pattern does not change.

```julia
ls = LUSolver() # Or any other object implementing the linear solver interface of Gridap
x = similar(b_1)
ss = symbolic_setup(ls,A_1)
ns = numerical_setup(ss,A_1)
solve!(x,ns,b_1)
ns = numerical_setup(ss,A_2)
solve!(x,ns,b_2)
ns = numerical_setup(ss,A_3)
solve!(x,ns,b_3)
ns = numerical_setup(ss,A_4)
solve!(x,ns,b_4)
```

**Comment by LaurentPlagne** [comment]
Crystal Clear ! 
I did use scenario1/option 1 and obtain a good speedup (x15) ! 
Thank you very much for your help and the great work on gridap :+1:

**Comment by fverdugo** [comment]
> P.S.1 For gridap questions like this one, what is the best channel : direct questions on Discourse or gihub issues ?

For questions we have the gitter chat https://gitter.im/Gridap-jl/community But I agree that sometimes long questions deserve an issue

> P.S.2 Are you in a stage where you encourage external users to use gridap or you are more in a fast development stage where you are focusing on a small team both using and developing gridap ?

**We do encourage external users to use (and cite) gridap!** The high level API is quite stable (i.e., the functions used in the tutorials are not going to change dramatically, perhaps some renaming at most)

**Comment by fverdugo** [comment]
BTW, do we really need scenario1/option2 ? (Now I don't remember why I implemented it 😅) Could GridapODEs be implemented in terms of scenario1/option1 instead ?? @oriolcg

**Comment by oriolcg** [comment]
We can take a closer look at that, there are probably things that could be further optimized (or simplified) in GridapODEs.
