### ISSUE TITLE
The divergence of an scalar field in 1D currently returns a VectorValue{1} and it should not ...

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/Gridap.jl#710]
Hi @fverdugo, @santiagobadia, (cc @davelee2804)

the following 1D code crashes during `assemble_matrix` no matter we use gradient or divergence in the bilinear form. (see error backtrace below for full details). The error is caused because either gradient or divergence of a scalar field in 1D returns a `VectorValue{1,T}` instance of length 1, and not an scalar. Thus, `q*∇(u)` is not an scalar, and the assemble process fails.

Before thinking about any solution, I wonder whether this is actually an issue but the expected behaviour. What is your view?

Thanks!
@amartinhuertas

```julia
using LinearAlgebra
using Gridap

D = 2*π
order = 1
domain = (0,D)
partition = (128,)

model = CartesianDiscreteModel(domain, partition; isperiodic=(true,))
Ω = Triangulation(model)
dΩ = Measure(Ω, 4*order)

V = FESpace(model, ReferenceFE(lagrangian, Float64, order), conformity=:H1)
Q = FESpace(model, ReferenceFE(lagrangian, Float64, order-1), conformity=:L2)
U = TrialFESpace(V)
P = TrialFESpace(Q)

md(u,q) = ∫(q*∇(u))dΩ  # with md(u,q) = ∫(q*divergence(u))dΩ also crashes
Md = assemble_matrix(md, U, Q)
```

```
ERROR: LoadError: MethodError: no method matching Float64(::VectorValue{1, Float64})
Closest candidates are:
  (::Type{T})(::T) where T<:Number at boot.jl:760
  (::Type{T})(::AbstractChar) where T<:Union{AbstractChar, Number} at char.jl:50
  (::Type{T})(::Base.TwicePrecision) where T<:Number at twiceprecision.jl:243
  ...
Stacktrace:
  [1] convert(#unused#::Type{Float64}, x::VectorValue{1, Float64})
    @ Base ./number.jl:7
  [2] setindex!(A::Vector{Float64}, x::VectorValue{1, Float64}, i1::Int64)
    @ Base ./array.jl:839
  [3] add_entry!(#unused#::typeof(+), a::Gridap.Algebra.InserterCSC{Float64, Int64}, v::VectorValue{1, Float64}, i::Int32, j::Int32)
    @ Gridap.Algebra ~/.julia/packages/Gridap/YCaeo/src/Algebra/SparseMatrixCSC.jl:132
  [4] _add_entries!
    @ ~/.julia/packages/Gridap/YCaeo/src/Algebra/AlgebraInterfaces.jl:160 [inlined]
  [5] add_entries!
    @ ~/.julia/packages/Gridap/YCaeo/src/Algebra/AlgebraInterfaces.jl:138 [inlined]
  [6] evaluate!(cache::Nothing, k::Gridap.Arrays.AddEntriesMap{typeof(+)}, A::Gridap.Algebra.InserterCSC{Float64, Int64}, v::Matrix{VectorValue{1, Float64}}, i::Vector{Int32}, j::Vector{Int32})
    @ Gridap.Arrays ~/.julia/packages/Gridap/YCaeo/src/Arrays/AlgebraMaps.jl:47
  [7] _numeric_loop_matrix!(mat::Gridap.Algebra.InserterCSC{Float64, Int64}, caches::Tuple{Nothing, Nothing, Gridap.Arrays.CachedVector{Int32, Vector{Int32}}, Gridap.Arrays.CachedVector{Int32, Vector{Int32}}}, cell_vals::FillArrays.Fill{Matrix{VectorValue{1, Float64}}, 1, Tuple{Base.OneTo{Int64}}}, cell_rows::Gridap.Arrays.Table{Int32, Vector{Int32}, Vector{Int32}}, cell_cols::Gridap.Arrays.Table{Int32, Vector{Int32}, Vector{Int32}})
    @ Gridap.FESpaces ~/.julia/packages/Gridap/YCaeo/src/FESpaces/SparseMatrixAssemblers.jl:267
  [8] numeric_loop_matrix!(A::Gridap.Algebra.InserterCSC{Float64, Int64}, a::Gridap.FESpaces.GenericSparseMatrixAssembler, matdata::Tuple{Vector{Any}, Vector{Any}, Vector{Any}})
    @ Gridap.FESpaces ~/.julia/packages/Gridap/YCaeo/src/FESpaces/SparseMatrixAssemblers.jl:254
  [9] assemble_matrix(a::Gridap.FESpaces.GenericSparseMatrixAssembler, matdata::Tuple{Vector{Any}, Vector{Any}, Vector{Any}})
    @ Gridap.FESpaces ~/.julia/packages/Gridap/YCaeo/src/FESpaces/SparseMatrixAssemblers.jl:107
 [10] assemble_matrix(f::typeof(md), a::Gridap.FESpaces.GenericSparseMatrixAssembler, U::Gridap.FESpaces.UnconstrainedFESpace{Vector{Float64}, Nothing}, V::Gridap.FESpaces.UnconstrainedFESpace{Vector{Float64}, Nothing})
    @ Gridap.FESpaces ~/.julia/packages/Gridap/YCaeo/src/FESpaces/Assemblers.jl:285
 [11] assemble_matrix(f::Function, U::Gridap.FESpaces.UnconstrainedFESpace{Vector{Float64}, Nothing}, V::Gridap.FESpaces.UnconstrainedFESpace{Vector{Float64}, Nothing})
    @ Gridap.FESpaces ~/.julia/packages/Gridap/YCaeo/src/FESpaces/Assemblers.jl:342
 [12] top-level scope
    @ ~/pml_atmos/101121/Dave/wave_eqn_eigs_test.jl:21
 [13] include(fname::String)
    @ Base.MainInclude ./client.jl:444
 [14] top-level scope
    @ REPL[8]:1
in expression starting at /home/dave/pml_atmos/101121/Dave/wave_eqn_eigs_test.jl:21
```

**Comment by davelee2804** [comment]
...I am not 100% sure this is the same thing, but I thought I should also try and see if the issue presented for 1D skeleton mesh integrals. The following code snippet:

```
using LinearAlgebra
using Gridap

D = 2*π
order = 1
domain = (0,D)
partition = (128,)

model = CartesianDiscreteModel(domain, partition; isperiodic=(true,))
Ω = Triangulation(model)
dΩ = Measure(Ω, 2*order)
Γ = SkeletonTriangulation(model)
dΓ = Measure(Γ, 1)
n_Γ = get_normal_vector(Γ)

V = FESpace(model, ReferenceFE(lagrangian, Float64, order), conformity=:H1)
Q = FESpace(model, ReferenceFE(lagrangian, Float64, order-1), conformity=:L2)
U = TrialFESpace(V)
P = TrialFESpace(Q)

buqs(u,q) = ∫(mean(q)*jump((u->u[1])*(n_Γ->n_Γ[1])))dΓ
Buqs = assemble_matrix(buqs, U, Q)
```

produces the error:
```
ERROR: LoadError: MethodError: no method matching *(::var"#483#485", ::var"#484#486")
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
  *(::ChainRulesCore.AbstractThunk, ::Any) at /home/dave/.julia/packages/ChainRulesCore/7ZiwT/src/tangent_arithmetic.jl:125
  *(::CellField, ::Function) at /home/dave/.julia/packages/Gridap/YCaeo/src/CellData/CellFields.jl:662
  ...
Stacktrace:
 [1] buqs(u::Gridap.FESpaces.SingleFieldFEBasis{Gridap.FESpaces.TrialBasis, ReferenceDomain}, q::Gridap.FESpaces.SingleFieldFEBasis{Gridap.FESpaces.TestBasis, ReferenceDomain})
   @ Main ~/tsw_eigs/src/1D_boundary_test.jl:21
 [2] assemble_matrix(f::typeof(buqs), a::Gridap.FESpaces.GenericSparseMatrixAssembler, U::Gridap.FESpaces.UnconstrainedFESpace{Vector{Float64}, Nothing}, V::Gridap.FESpaces.UnconstrainedFESpace{Vector{Float64}, Nothing})
   @ Gridap.FESpaces ~/.julia/packages/Gridap/YCaeo/src/FESpaces/Assemblers.jl:285
 [3] assemble_matrix(f::Function, U::Gridap.FESpaces.UnconstrainedFESpace{Vector{Float64}, Nothing}, V::Gridap.FESpaces.UnconstrainedFESpace{Vector{Float64}, Nothing})
   @ Gridap.FESpaces ~/.julia/packages/Gridap/YCaeo/src/FESpaces/Assemblers.jl:342
 [4] top-level scope
   @ ~/tsw_eigs/src/1D_boundary_test.jl:22
 [5] include(fname::String)
   @ Base.MainInclude ./client.jl:444
 [6] top-level scope
   @ REPL[2]:1
in expression starting at /home/dave/tsw_eigs/src/1D_boundary_test.jl:22
```
I'm not 100% sure this is the same thing, perhaps I'm doing something silly here. However replacing the bilinear operator with 
`buqs(u,q) = ∫(mean(q)*jump(u*n_Γ))dΓ` also yields an error: `ERROR: LoadError: MethodError: no method matching Float64(::VectorValue{1, Float64})`

**Comment by amartinhuertas** [comment]
Hi @davelee2804 ... have you tried to define `V` as an space of vector-valued functions with just a single component? I guess the issue stems from here.

**Comment by santiagobadia** [comment]
I think Gridap is not the problem. The gradient is conceptually a vector for a scalar field. 
If you write your problem dim-agnostic, you need `q` to be in a vector space.
The product is an inner product `.` between vectors, not the scalar product `*`.
If you write the weak form this way, I think it should fix the issue.

**Comment by santiagobadia** [comment]
Another approach is to use the divergence operator...

**Comment by amartinhuertas** [comment]
> I think Gridap is not the problem. The gradient is conceptually a vector for a scalar field.

Ok, that makes sense.The only thing that I wonder is whether the gradient operator for ordinary functions (i.e., univariate functions) has sense at all. Isn't it just the ordinary derivative operator, that given an scalar function returns an scalar function? I guess the answer is NO if you want to have a dim-agnostic code, as you say ...

> I see that you say it also crashes. For the divergence, the result should not be a vector, that one has to be fixed.

Note that @davelee2804 is using an space of scalar-valued functions for `V`. Shouldn't it be defined as an space of vector-valued functions with only one component to be consistent? Then, the divergence of a vector-valued field with one component is an scalar. Anyway, the divergence of a scalar field should not return a vector ... this does not seem correct.

**Comment by santiagobadia** [comment]
Ok, that is another problem. The div operator only applies to vector fields.

As I said, we must write things in 1D as in any other dimension:

- The divergence does not make sense for scalar functions.
- The gradient is a vector (even in 1D for uni-variate functions).
 
Another story is that there is a bijective isometry between scalars and vectors in 1D.

But trying to make scalars and vectors in 1D the same thing in Gridap is a very bad idea IMO. We need to keep the distinction in whatever dimension.

**Comment by amartinhuertas** [comment]
> But trying to make scalars and vectors in 1D the same thing in Gridap is a very bad idea IMO. We need to keep the distinction in whatever dimension.

Ok. Agreed. I also think it is very bad idea, and the root of many inconsistencies. I have changed to title of the issue to reflect the actual issue that we think we found.

@davelee2804 ... can you please try to replace Float64 by VectorValue{1,Float64} in the reference fe definition for V and see if the problems disappear using bilinear forms **exactly defined as in higher dimensions**?

**Comment by santiagobadia** [comment]
agreed, easy fix, it is better not to open these doors in the code...

**Comment by fverdugo** [comment]
I also see it like @santiagobadia

**Comment by davelee2804** [comment]
Thanks for the helpful comments @amartinhuertas , @santiagobadia @fverdugo . Yes, I can see why conflating a Lagrangian basis with H1 conformity with a RT basis in 1D could be misleading. After re-defining `V` as a 1D RT test function as suggested by @amartinhuertas both the divergence operator and the facet integral work as expected now. 

In fact, this is very useful, as I am exploring dispersion relations for which the buoyancy field may be have either H1 or L2 conformity, so being able to make the distinction between a RT velocity field and Lagrangian buoyancy field in 1D is very useful.

Thanks again for the clarification.
