### ISSUE TITLE
Fixing Newmark test

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#749]
Hi @oriolcg 

Could you fix the following test? (the test suite was commented)

https://github.com/gridap/Gridap.jl/blob/630f3c6b7169f04791e36fd459042e868b5d2320/test/GridapODEsTests/ODEsTests/ODESolversTests.jl#L158

Thanks!

--Santi

**Comment by oriolcg** [comment]
Done in PR #750
