### ISSUE TITLE
No command to find eigen value and eigen vector

### ISSUE THREAD

**Issue by vishnuuk20** [gridap/Gridap.jl#757]
I am trying to develop a code as part of my project in Julia. But I am unable to find any function to find eigen value and eigen vector for a vector or tensor using gridap. But the same is available in Tensors.jl and LinearAlgebra.jl. I would like to get a solution for this problem

**Comment by fverdugo** [comment]
Transform the tensor to an array with `get_array` and then use LinearAlgebra.

**Comment by vishnuuk20** [comment]
I have already tried using get_array function, which will definitely produce eigen value and eigen vector, but in the form of array. I want to get the results in the form of SingleFEfieldfunction. Please note that the operators such as ε or ∇ produces such type of results.

**Comment by fverdugo** [comment]
This can be easily done with the \circ operator. Paste here a small MWE so that we are able to tell how to do this.

**Comment by vishnuuk20** [comment]
I am using the code below. The function σEigen(ε) is not working for the developed eigenvalue and eigenvector. `
using Gmsh: gmsh
using Gridap
using GridapGmsh
using Gridap.Algebra
using Gridap.TensorValues
using Gridap.ReferenceFEs
using LinearAlgebra
using PyPlot

gmsh.initialize()
gmsh.option.setNumber("General.Terminal", 1)
L = 1.0
h = 0.25
p1 = gmsh.model.geo.addPoint(0, 0, 0, h)
p2 = gmsh.model.geo.addPoint(L, 0, 0, h)
p3 = gmsh.model.geo.addPoint(L, L, 0, h)
p4 = gmsh.model.geo.addPoint(0, L, 0, h)

l1 = gmsh.model.geo.addLine(p1, p2)
l2 = gmsh.model.geo.addLine(p2, p3)
l3 = gmsh.model.geo.addLine(p3, p4)
l4 = gmsh.model.geo.addLine(p4, p1)

cl1 = gmsh.model.geo.addCurveLoop([l1,l2,l3,l4])
ps1 = gmsh.model.geo.addPlaneSurface([cl1])

pg1 = gmsh.model.addPhysicalGroup(2, [ps1])
pg2 = gmsh.model.addPhysicalGroup(1, [l1])
pg3 = gmsh.model.addPhysicalGroup(1, [l3])

gmsh.model.setPhysicalName(2, pg1, "Domain")
gmsh.model.setPhysicalName(1, pg2, "support")
gmsh.model.setPhysicalName(1, pg3, "load")

gmsh.model.geo.synchronize()
gmsh.model.mesh.generate(2)
gmsh.write("ExampleModel.msh")
gmsh.finalize()

model = GmshDiscreteModel("ExampleModel.msh")
writevtk(model,"Model1")

using Gridap.Geometry
labels = get_face_labeling(model)
dimension = 2
mat_tags = get_face_tag(labels,dimension)

p = get_vertex_node(model)
gr = get_grid(model)
nodes = get_node_coordinates(gr);

order = 1

reffe = ReferenceFE(lagrangian,VectorValue{2,Float64},order)
V0 = TestFESpace(model,reffe;
  conformity=:H1,
  dirichlet_tags=["support","load"],
  dirichlet_masks=[(true,true), (true,false)])

g1(x) = VectorValue(0.0,0.0)
g2(x) = VectorValue(0.01,0.0)

U = TrialFESpace(V0,[g1,g2])

const E = 70.0e9
const ν = 0.33
const λ = (E*ν)/((1+ν)*(1-2*ν))
const μ = E/(2*(1+ν))
σ(ε) = λ*tr(ε)*one(ε) + 2*μ*ε
function Eigen(E)
    E2 = get_array.(E)
    Egn = eigvals.(E2)
    Egn1 = eigvecs.(E2)
    σ1 = map(x->x[1], Egn)
    σ2 = map(x->x[2], Egn)
    n1 = map(x->x[:,1], Egn1)
    n2 = map(x->x[:,2], Egn1)
    return σ1, σ1, n1, n2   
end

function σEigen(ε)
    σElas = σ∘(ε)
    σEval = evaluate(σElas,nodes)
    σ1, σ1, n1, n2 = Eigen(σEval)
    σEg = σ1*(n1 ⊗ n1) + σ2*(n2 ⊗ n2) 
    return σEg
end

degree = 2*order
Ω = Triangulation(model)
dΩ = Measure(Ω,degree)

a(u,v) = ∫( ε(v) ⊙ (σEigen∘(ε(u)) ))*dΩ
l(v) = 0

op = AffineFEOperator(a,l,U,V0)
uh = solve(op)

**Comment by fverdugo** [comment]
Try this:
```julia
function Eigen(E)
    E2 = get_array(E)
    Egn = eigvals(E2)
    Egn1 = eigvecs(E2)
    σ1 = Egn[1]
    σ2 = Egn[2]
    n1 = VectorValue(Egn1[:,1])
    n2 = VectorValue(Egn1[:,2])
    return σ1, σ1, n1, n2   
end

function σEigen(ε)
    σElas = σ(ε)
    σ1, σ1, n1, n2 = Eigen(σEval)
    σEg = σ1*(n1 ⊗ n1) + σ2*(n2 ⊗ n2) 
    return σEg
end
```

**Comment by vishnuuk20** [comment]
It is working.
My sincere thanks to you
