### ISSUE TITLE
Module MultiNonLinearFEOperatorsTests crashes for order > 1

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#77]
Module MultiNonLinearFEOperatorsTests crashes for order > 1.

**Comment by fverdugo** [comment]
This is embarrassing !😅

Can you provide a small reproducer?

**Comment by fverdugo** [comment]
Same kind of error in module `NonLinearFEOperatorsTests`. Thus, the error is not related with the fact of having multiple fields.

There an array dimension mismatch when doing operations like u*du, where u is a FEFunction and du is a FEBasis. I know what is happening.  I'll try to fix it tomorrow.

**Comment by fverdugo** [comment]
Fixed via aa49689be2a8dc14e052a6409c8348f492b52b3e. Closing issue.
