### ISSUE TITLE
More work on C/DLagrangianFESpace constructors

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#78]
1. I would create a new constructor for `C/DLagrangianFESpace` without the need to pass `diritags`, e.g., using the following code
```
diritags = [1,2,3]
num_comps = 2 # To check how to extract the num of components from the field type T
dirimasks = Vector{NTuple{num_comps,Bool}}(undef,length(diritags))
flag = ntuple(i -> true, D)
fill!(dirimasks,flag)
fespace = CLagrangianFESpace(T,model,order,diritags,dirimasks)
```
For instance, such tags are not needed for scalar problems. 

2. To define a space with no boundary condition, the most common situation for DG methods, we need
```
diritags = Int[]
dirimasks = []
fespace = DLagrangianFESpace(T,model,order,diritags,dirimasks)
```
I would provide a constructor that does not require the last two arguments

3. On the other hand, it seems these FESpaces do not work for "boundary" tag.
It would be nice to add this functionality too.

**Comment by fverdugo** [comment]
The following signatures have been added for both `C/DLagrangianFESpaces`:
```julia
CLagrnagianFESpace(T,model,order)
CLagrnagianFESpace(T,model,order,diritags)
CLagrnagianFESpace(T,model,order,diritags,dirimasks)
```
In all cases `diritags` can be a vector of `Int` or of `String`

Done via f1ee797f512ef2e473f30ac7f0d7e9b6bbb69e2f  and 776b40238365f145037fc5e490600bf5b45434ef

Closing issue
