### ISSUE TITLE
Quick Question: Gradient of a VectorValue is a Tensor?

### ISSUE THREAD

**Issue by umbriquse** [gridap/Gridap.jl#784]
Hello, I'm running into some functionality that I don't understand. The `res` function from the MWE (shown below) has a printout with the result `u = (0.0, 0.0, 0.0)      ∇(u) = (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)`. That shows that performing the gradient function on a vector returns a tensor. The desired functionality would be for the gradient function to return a vector. 

### Question
How would I be able to calculate the gradient of a vector that returns a vector?

```julia
using Gridap

domain = (0,1,0,1,0,1)
partition = (10,10,10)
model = CartesianDiscreteModel(domain,partition)

refFe = ReferenceFE(lagrangian, VectorValue{3, Float64}, 1)
V = TestFESpace(model, refFe)
U = TransientTrialFESpace(V)

dΩ = Measure(Interior(model), 2)

res(t, u, v) = ∫( (x -> println("u = $(u(x)) \t ∇(u) = $(∇(u)(x))")) ⋅ v )dΩ

op_ADStress = TransientFEOperator(res, U, V; order = 2)
ode_solver = Newmark(LUSolver(), 1, 0.5, 0.25)

u₀ = interpolate_everywhere(VectorValue(0.0, 0.0, 0.0), U(0.0))
v₀ = interpolate_everywhere(VectorValue(0.0, 0.0, 0.0), U(0.0))
a₀ = interpolate_everywhere(VectorValue(0.0, 0.0, 0.0), U(0.0))
uₕₜ = solve(ode_solver,op_ADStress,(u₀,v₀,a₀),0,1)
for (uₕ, t) in uₕₜ end
```

### Version Info
```julia
julia> versioninfo()
Julia Version 1.6.5
Commit 9058264a69 (2021-12-19 12:30 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen Threadripper 3990X 64-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, znver2)
```

### Package Status
```julia
(Knox) pkg> st Gridap
  [56d4f2e9] Gridap v0.17.12
```

**Comment by fverdugo** [comment]
Hi @umbriquse! the gradient of a vector function is indeed a tensor function.

If you want to obtain a vector from a vector, then you are thinking of another diff operator (the curl perhaps?) but not the gradient.

Which is the definition of the quantity you want to compute?

**Comment by umbriquse** [comment]
I think It's technically called a jacobian.

Say if I have a vector `v` where `v = (x1, x2, x3)`. 
What I would like to compute would be `dv/dx = (dv/dx1, dv/dx2, dv/dx3)`

**Comment by umbriquse** [comment]
Ah, I see that you are using the [jacobian](https://en.wikipedia.org/wiki/Jacobian_matrix_and_determinant) definition and that my understanding of that was incorrect. It's the main diagonal of the jacobian matrix that I am after. Sorry for the distraction.

**Comment by umbriquse** [comment]
[Here's](https://en.wikipedia.org/wiki/Gradient) a Wikipedia article about what the functionality of the gradient operation I assumed. 
This bit of syntax might be confusing to other users as well. My background is in physics, and the linked article is primarily the definition I have experience with.

**Comment by fverdugo** [comment]
Yes, you are looking for the diagonal of the gradient/jacobian
