### ISSUE TITLE
"boundary" of closed boundary

### ISSUE THREAD

**Issue by JonasIsensee** [gridap/Gridap.jl#791]
Hi,
I'm confused by the following reduced problem.
Here, I'm trying to solve for the displacement field in the bulk after imposing the displacement of the surface via a dirichlet condition.
The mesh is a circle with the perimeter labelled as `"boundary"`.

In principle, this seems to work well but at the 
```
using Gridap # v0.17.12
using GridapGmsh # v0.6.0

#= 
//+
SetFactory("OpenCASCADE");
//+
Disk(1) = {0, 0, 0, 0.5, 0.5};
//+
Physical Surface("disk", 3) = {1};
//+
Physical Curve("boundary", 4) = {1};
=# 

mshfile = "disk.msh"
model = GmshDiscreteModel(mshfile)
order = 2
degree = 2*order
E = 1.0
νₚ = 0.49
σ_def(ε) = E/(1+νₚ)*ε + E*νₚ/(1+νₚ)/(1-2νₚ)*tr(ε)*one(ε)
Ω = Interior(model)
dΩ = Measure(Ω, degree)
reffeᵤ = ReferenceFE(lagrangian,VectorValue{2,Float64},order)
V = TestFESpace(Ω, reffeᵤ, dirichlet_tags=["boundary"])
boundary_fun = (x) -> VectorValue(0.0, -0.7*x[2]*(exp(-10x[1]^2)))
U = TrialFESpace(V, [boundary_fun])
lhs(𝑢, 𝑣) = ∫(ε(𝑢)⊙(σ_def ∘ ε(𝑣)))dΩ
rhs(𝑣) = 0
op = AffineFEOperator(lhs,rhs,U,V)
sol = solve(op)
writevtk(Ω,"trian", cellfields=["uh" => sol,])
```

![image](https://user-images.githubusercontent.com/33990604/170700289-bc13db08-f3dd-447f-90b3-00b55a9b79ad.png)

In this reduced example, I can "fix" it by giving the point in question a tag in the mesh
`Physical Point("point", 5) = {1};`  

and then writing
```
V = TestFESpace(Ω, reffeᵤ, dirichlet_tags=["boundary", "point"])
U = TrialFESpace(V, [boundary_fun, boundary_fun])
```
![image](https://user-images.githubusercontent.com/33990604/170707254-e4f948e2-4523-4179-af48-343d15be5264.png)

However, this feels a bit clunky and I'm not sure, how I'd do this in a more general use-case.

Comment: I first encountered this in 3D meshes created by intersecting various spheres. This lead to these "spikes" as above but in "random" places where gmsh put the support points.

**Comment by ericneiva** [comment]
Hi, @JonasIsensee,

I would say that having `Physical Point("boundary", 5) = {1};` also works. Thus, you can group all GMSH entities lying at the Dirichlet boundary under the same tag and proceed as in the first snippet, i.e., building the test FE space with a single Dirichlet tag. Let me know it it works.

**Comment by JonasIsensee** [comment]
Oh, it hadn't occurred to me that you could label objects of different dimensionality with the same tag.
This works!

Thanks for your quick response!

Do you think the docs would benefit from a "gotcha's" section?
I spent quite some time debugging this....

**Comment by ericneiva** [comment]
I think this "trick" is implied in the first gotcha point in [GridapGmsh readme](https://github.com/gridap/GridapGmsh.jl). What do you think? If so, maybe it's a little bit obscure and could use a rewording... so, go ahead and PR a rewording. It will surely help the rest of the community.
