### ISSUE TITLE
Adding new operators to CellBasis

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#80]
I would like to add (at least) the `div` and `curl` operator, but probably also `trace`, etc, over `CellBasis`. For instance, now, to compute the bilinear form of the Stokes operator, I do it as:
```
divfun(x,∇u) = tr((∇u))
div(u) = CellBasis(trian,divfun,∇(u))
a(v,u) = inner(∇(v[1]),∇(u[1])) + inner(v[2],u[2]) - inner(div(v[1]),u[2]) + inner(v[2],div(u[1]))
```
but the target would be just
```
a(v,u) = inner(∇(v[1]),∇(u[1])) + inner(v[2],u[2]) - inner(div(v[1]),u[2]) + inner(v[2],div(u[1]))
```
I know it is not a critical point.

**Comment by fverdugo** [comment]
Added `div`, `curl`, and `trace` operators via commit 5a0f322c5b938f12e26e9c0a7c9361aa649e014f. 

Closing issue.
