### ISSUE TITLE
Name conflict with `Statistics`

### ISSUE THREAD

**Issue by lhupe** [gridap/Gridap.jl#814]
Gridap defines and exports a `mean` function (in `/src/CellData/CellFields.jl`) that conflicts with the `Statistics` standard library.
Is there a specific reason to define a new function instead of extending `Statistics.mean` in Gridap?

**Comment by kishore-nori** [comment]
Great, this would fix the problem of name clash when using `BenchmarkTools.jl`

**Comment by JordiManyer** [comment]
Will be part of v0.18
