### ISSUE TITLE
Basic tutorial for writing and meaning of special characters

### ISSUE THREAD

**Issue by mhechthz** [gridap/Gridap.jl#818]
I'm not sure whether this is a general Julia quiestion or a Gridap question, but is there any tutorial on how to write all the special characters, e.g. in Jupyter notebook?

E.g. from the Poisson example:
a(u,v) = ∫( ∇(v)⋅∇(u) )*dΩ
b(v) = ∫( v*f )*dΩ + ∫( v*h )*dΓ

or from p-Laplacian example:
dflux(∇du,∇u) = (p-2)*norm(∇u)^(p-4)*(∇u⊙∇du)*∇u+norm(∇u)^(p-2)*∇du
jac(u,du,v) = ∫( ∇(v)⊙(dflux∘(∇(du),∇(u))) )*dΩ

And I'm sure that some of the special characters have special meaning. Where are those basics documented?

**Comment by colinthart** [comment]
The Julia manual page [Unicode Input](https://docs.julialang.org/en/v1/manual/unicode-input/) provides good general information for working with special symbols in Julia code generally. 

> The following table lists Unicode characters that can be entered via tab completion of LaTeX-like abbreviations in the Julia REPL (and in various other editing environments). You can also get information on how to type a symbol by entering it in the REPL help, i.e. by typing ? and then entering the symbol in the REPL (e.g., by copy-paste from somewhere you saw the symbol).

In other words typing `\int` becomes `∫` etc. I have used these completions successfully in VS Code (with the Julia extension installed) and in Jupyter notebooks. 

If your trouble isn't typing the symbols but knowing what they represent, you can follow the suggestion to copy and paste a Unicode symbols in [REPL help](https://docs.julialang.org/en/v1/stdlib/REPL/#Help-mode), then in addition to displaying the docstring it will also suggest the full name of the function for which the symbol is an alias.

**Comment by mhechthz** [comment]
Ok, it works. I slowly start to understand. But what about

```
1 dflux(∇du,∇u) =  ...
2 dflux∘(∇(du),∇(u))
```

Why not to call in line 2
`dflux(∇(du),∇(u))`
or even
`dflux(∇du,∇u)`?

**Comment by colinthart** [comment]
> or even
> `dflux(∇du,∇u)`?

Julia recognizes nabla as a valid character that can appear anywhere in an identifier, and so `∇u` is a symbol separate and distinct from `∇` and `u`. In the Manufactured Solution section of [Tutorial 2](https://gridap.github.io/Tutorials/stable/pages/t002_validation/#Tutorial-2:-Code-validation-1) you can find an example of how to associate these. In essence, `∇u` is assigned to a function that returns a `VectorValue` with the analytical gradient. Then, a new method specializing `∇` on `typeof(u)` is assigned to that analytical gradient function.

> dflux∘(∇(du),∇(u))

The composition syntax here is discussed in [The software design of Gridap](https://arxiv.org/pdf/2109.12818.pdf). Section 2.5 introduces the value of lazily computing cell-wise operations on the fly, and section 2.9 demonstrates the composition of operations acting on fields.

**Comment by mhechthz** [comment]
Ok, document "The software design of Gridap" seems to be the most important document. Thank you!
