### ISSUE TITLE
PETSc Error

### ISSUE THREAD

**Issue by DevasmitDutta** [gridap/Gridap.jl#826]
Hi, I am operating on macOS Monterey, version 12.5.1, and i am facing an issue when i try to run code using GridapPETSc, below is the error in stack-trace
```
PETSc Error --- Application was linked against both OpenMPI and MPICH based MPI libraries 
and will not run correctly
```

After i got this error, i have un-installed MPICH from my machine, and currently only have OPEN-MPI, but still it shows having linked with multiple MPI implementation.

**Comment by JordiManyer** [comment]
Hi, 
It's hard to asses the problem with such a limited information, but I think your problem might be that the library that `MPI.jl` is using is different to the mpi library used to compile PETSc. 
First, I would advise you to read the `MPI.jl` [configuration manual](https://juliaparallel.org/MPI.jl/stable/configuration/#Configuration).

Also, if you are using `GridapPETSc.jl` I would suggest you
1) Set your `MPI.jl` package to use your system mpi library. 
2) Dowload and compile PETSc locally using the same mpi library. [This CI script](https://github.com/gridap/GridapPETSc.jl/blob/master/.github/workflows/ci_extra.yml) contains bash instructions to do so. 
3) Rebuild both the artifacts in your project by running
```julia
julia --project=. -e `using Pkg; Pkg.build()` 
```

Hopefully this solves your issue.
