### ISSUE TITLE
TransientFESolution modifies the cellfields previously yielded

### ISSUE THREAD

**Issue by Antoinemarteau** [gridap/Gridap.jl#827]
When iterating on timesteps solutions of TransientFESolution, new iteration modifies the previously yielded solution.  

Reproduce by replacing poisson_transient.jl tutorial postprocessing by :
```julia
# ## Postprocessing
(uh1, t1), state1  = iterate(uₕₜ)
writevtk(Ω, "uh1",    cellfields=[ "uh1"=>uh1])    # exports uh1 as expected

(uh2, t2), state2  = iterate(uₕₜ, state1)
writevtk(Ω, "uh1_KO", cellfields=[ "uh1_KO"=>uh1]) # exports something diff from uh1
writevtk(Ω, "uh2",    cellfields=[ "uh2"=>uh2])    # exports uh2 as expected
```
The second export of 1st time step solution `uh1` is different from the fist one.
This prevents me from visualizing $\partial_t(uh)$ as I never have two consecutive solutions available simultaneously.

**Comment by Antoinemarteau** [comment]
I see there is an `allocate_trial_space` in `iterate(sol)` but not in `iterate(sol, state)`  https://github.com/gridap/Gridap.jl/blob/f4236fb4b89f61f20570973d8105dc85e7b1b1d4/src/ODEs/TransientFETools/TransientFESolutions.jl#L73 

Would adding the allocation in the second iterate method solve it?
Would it be better to implement copy(cellfield::CellDatum) to allow the user to save a yielded solution (and avoid allocation when user don't use it) ?

**Comment by fverdugo** [comment]
@Antoinemarteau I think this is the expected behaviour. It gets modified because we allocate a vector of free dof values and reuse it between time steps. Otherwise, allocating a new vector for each time step would be overkill in a large computation.

If you can allocate a new solution in your script and use it to store the previous step.

**Comment by Antoinemarteau** [comment]
@oriolcg that would be perfect !
But somehow I always get `uf`=`u0` 
```julia
# ## Postprocessing
iter_result = iterate(uₕₜ)
while iter_result !== nothing
    (uh,t), state = iter_result

    Uh, (uf, u0, tf, cache) = state
    uf == u0 && @error "same consecutive solution at $tf"

    global iter_result = iterate(uₕₜ, state)
end
```
![image](https://user-images.githubusercontent.com/43928194/188917523-c0fc7a2d-9beb-4caf-b658-fed683c8c1d8.png)
Did I do something wrong ?

**Comment by fverdugo** [comment]
@Antoinemarteau 

> It would be very nice to have uhp=copy(uh) and an in-place copyto!(uhp, uh) for this use :P

This would be indeed very useful if not yet available! Please feel free to add it via a PR.

**Comment by Antoinemarteau** [comment]
Yes Base.copy has to be specialized. I will try with ::FEFunction this WE!
