### ISSUE TITLE
Use rethrow to improve error messages in notebook and vscode

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#843]
Use rethrow here : https://github.com/gridap/Gridap.jl/blob/e6d3d5d240d0d10fdecfb48f3e783452a4a4cae1/src/CellData/CellFields.jl#L476

**Comment by stevengj** [comment]
Doing
```
try
   foo()
catch
   rethrow()
end
```
is equivalent to
```jl
foo()
```
no?  Why have the `try-catch` at all here?

**Comment by fverdugo** [comment]
If I remember well, I introduced the try catch statement to provide a more "meaningful" error message than the default one (i.e. an error message with a Gridap-related hint). But it seems that this is creating a lot of confusion in Jupyter and VSCode.

So, I think I would go for removing the try-catch completelly.

**Comment by fverdugo** [comment]
I removed the try-catch statement in [f709a9d](https://github.com/gridap/Gridap.jl/commit/f709a9da315208c33db905150166943191938a0c)

Just for the record: I accidentally pushed this direclty into master. I should have opened a PR instead.
