### ISSUE TITLE
Evaluation at nodes

### ISSUE THREAD

**Issue by zjwegert** [gridap/Gridap.jl#846]
Hi all,
I'm trying to efficiently evaluate the basis function at each node but having some issues with what looks like a bug (attempt 1). Here is a snippet of code:
```
n = 200
model = CartesianDiscreteModel((0,1,0,1),(n,n),isperiodic=(true,true));
V = TestFESpace(model,ReferenceFE(lagrangian,VectorValue{2,Float64},1),conformity=:H1);
Ω = Triangulation(model)
dv = get_fe_basis(V);
```

**Attempt 1 - Evaluate at the nodes:** At a single point, `dv(get_node_coordinates(Ω)[1])` gives
```
8-element Vector{VectorValue{2, Float64}}:
 VectorValue{2, Float64}(1.0, 0.0)
 VectorValue{2, Float64}(0.0, 0.0)
 VectorValue{2, Float64}(0.0, 0.0)
 VectorValue{2, Float64}(0.0, 0.0)
 VectorValue{2, Float64}(0.0, 1.0)
 VectorValue{2, Float64}(0.0, 0.0)
 VectorValue{2, Float64}(0.0, 0.0)
 VectorValue{2, Float64}(0.0, 0.0)
```
as expected. Then, for a vector of points, the result doesn't appear to be correct. E.g., `dv(get_node_coordinates(Ω)[:])` gives
```
40401-element Vector{VectorValue{2, Float64}}:
 VectorValue{2, Float64}(1.0, 0.0)
 VectorValue{2, Float64}(0.0, 0.0)
 VectorValue{2, Float64}(0.0, 0.0)
 VectorValue{2, Float64}(0.0, 0.0)
 VectorValue{2, Float64}(0.0, 0.0)
 VectorValue{2, Float64}(0.0, 0.0)
          ⋮
 VectorValue{2, Float64}(0.0, 0.0)
 VectorValue{2, Float64}(0.0, 0.0)
 VectorValue{2, Float64}(0.0, 0.0)
 VectorValue{2, Float64}(0.0, 0.0)
 VectorValue{2, Float64}(0.0, 0.0)
 VectorValue{2, Float64}(0.0, 0.0)
```
I think this should actually output as a `Vector{Vector{VectorValue{2, Float64}}}`. E.g.,
```
40401-element Vector{VectorValue{2, Float64}}:
[(1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 1.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0)]
          ⋮
```
Is this a bug?

**Attempt 2 - Using a `CellPoint`:** A `CellPoint` seems like another option. However, this gives strange results as well:
```
x = compute_cell_points_from_vector_of_points(get_node_coordinates(Ω)[:],Ω,PhysicalDomain())
dv(x)
```
This gives
```
40000-element LazyArray{FillArrays.Fill{Gridap.Fields.LinearCombinationFieldVector{Matrix{Float64}, Gridap.Polynomials.MonomialBasis{2, VectorValue{2, Float64}}}, 1, Tuple{Base.OneTo{Int64}}}, Matrix{VectorValue{2, Float64}}, 1, Tuple{LazyArray{LazyArray{FillArrays.Fill{typeof(inverse_map), 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}, AffineMap{2, 2, Float64, 4}, 2, Tuple{Gridap.Geometry.CartesianMap{2, Float64, 4}}}, Vector{VectorValue{2, Float64}}, 1, Tuple{LazyArray{FillArrays.Fill{Broadcasting{Reindex{Vector{VectorValue{2, Float64}}}}, 1, Tuple{Base.OneTo{Int64}}}, Vector{VectorValue{2, Float64}}, 1, Tuple{Table{Int64, Vector{Int64}, Vector{Int64}}}}}}}}:
...
```
OR
```
Array(dv(x))
40000-element Vector{Matrix{VectorValue{2, Float64}}}:
...
```
The size of the array and shape of elements (`4 x 8`, `2 x 8`, `0 x 8`) makes me think that I'm not using the `CellPoint` correctly.

**Note**: for context, I'm trying to efficiently evaluate the symmetric gradient of the basis function at each node so that I can efficiently calculate certain results (the same problems above present in this case, hence the simplification). I can post another snippet if there is a possibility of speeding up these calculations in a nicer way...

**Comment by amartinhuertas** [comment]
> Attempt 1 - Evaluate at the nodes:
> Attempt 2 - Using a CellPoint

@zjwegert, FYI, the algorithm which is triggered in the former case (i.e., Attempt 1: evaluate a `CellField` (i..e, dv) at a `Point`/point-wise array of `Point`s) is different from the one triggered in the latter (i.e., Attempt 2: evaluate a `CellField` at a `CellPoint`). 

In the former case, assuming you evaluate a `CellField` on a single `Point`, **the `Point` is assumed to be an arbitrary point within the global domain**. Gridap locates the cell that includes the `Point` by means (of a costly) search algorithm, and returns the result of evaluating the basis functions on that `Point` (e.g., you can try with a point in the middle of say, the first cell, to double check what I am saying). Whenever a `Point` is located at the cells interface, one of the cells sharing this interface is selected arbitrarily. If you pass a point-wise array of `Point`s, then the same operation is done for each `Point` in the array. (e.g., you can try with an array of two points, one point in the middle of the first cell, and another in the middle of the second cell, to double check what I am saying).)

In the latter case, let us first clarify what a `CellPoint` is. A `CellPoint` is as cell-wise array (i.e., as many entries as cells) of arrays of `Point`s, one per cell. The `Point`s in the array corresponding to a cell are assumed to be within the cell, and **NOT** in the whole domain. The coordinate system in which these `Point`s are expressed are either the coordinate system of the reference cell (whenever the `DomainStyle` trait of the `CellPoint` is `ReferenceDomain), or the global domain coordinate system (whenever the `DomainStyle` trait of the `CellPoint` is `PhysicalDomain`). But remember, the `Point`s in the array corresponding to a cell are assumed to be within the cell. 

In regards to your particular question, what you can do is:

```julia
# Returns a `CellPoint` instance that holds inside a
# cell-wise array of `Point`s with the coordinates of the Lagrangian
# node of each cell within the global domain coordinate system.
x = get_cell_points(Gridap.FESpaces.get_fe_dof_basis(V))

# Evaluates a `CellField` on a `CellPoint`. Returns a cell-wise array 
# of 4x8 matrices, with 4 being the number of nodes per cell, and 8 
# the number of shape functions. Note that in each cell we evaluate 
# the 8 shape functions on that cell (columns of the matrix) on the 
# 4 nodes (vertices for first order Lagrange FEs) of the cell. 
dv(x)
```

**Comment by zjwegert** [comment]
Hi @amartinhuertas, firstly, thank you for the detailed explanation regarding both methods.

Just to double check, should each row correspond to a node in `model.grid.cell_node_ids`? I.e., `dv(x)[10][1,:]` should correspond to node 10 and `dv(x)[10][3,:]` should correspond to node 211?

I tried to check this via
```
x = get_cell_points(get_fe_dof_basis(V))
model.grid.cell_node_ids[10]
Array(dv(x))[10][3,:] == dv(get_node_coordinates(problem.gridap_data.Ω)[211])
```
This returns `false`. But I assume that this is because of the discussion regarding the cell interface?

**Comment by amartinhuertas** [comment]
> Just to double check, should each row correspond to a node in model.grid.cell_node_ids? I.e., dv(x)[10][1,:] should correspond to node 10 and dv(x)[10][3,:] should correspond to node 211?

Correct. But note that this is only valid as far as you use first order lagrangian FEs to build `V` (as in your example code). If you need to leverage higher order lagrangian FEs, then the cell-wise global node identifiers cannot be extracted from `model.grid.cell_node_ids`. This latter info encodes the nodes of the geometrical FE mapping used to represent the geometry of the domain. When you use first order for geometry, and first order for `V`, both nodes match, and this is why it works in your case. 

> But I assume that this is because of the discussion regarding the cell interface?

Yes, I think so.

**Comment by zjwegert** [comment]
> Correct. But note that this is only valid as far as you use first order lagrangian FEs to build `V` (as in your example code). If you need to leverage higher order lagrangian FEs, then the cell-wise global node identifiers cannot be extracted from `model.grid.cell_node_ids`. This latter info encodes the nodes of the geometrical FE mapping used to represent the geometry of the domain. When you use first order for geometry, and first order for `V`, both nodes match, and this is why it works in your case.
 
Thank you for the heads up. Is there a nice way for this method to also leverage the higher order Lagrangian FEs?

**Comment by zjwegert** [comment]
Hi @amartinhuertas, I'm encountering some strange behavior when trying to reconstruct an FE function from cell values. This fails in both the periodic and non-periodic case.
```
n = 200
periodic = false;
model = CartesianDiscreteModel((0,1,0,1),(n,n),isperiodic=(periodic,periodic));
V = TestFESpace(model,ReferenceFE(lagrangian,VectorValue{2,Float64},1),conformity=:H1);
V_scalar = TestFESpace(model,ReferenceFE(lagrangian,Float64,1),conformity=:H1);
Ω = Triangulation(model);
dv = get_fe_basis(V);
x = get_cell_points(get_fe_dof_basis(V));
# Dummy function
f(x) = VectorValue(x[1]*(x[1]-1),x[2]*(x[2]-1));
fh = interpolate_everywhere(f,V);
# Some operation evaluated at cell points
εf_map = Array((ε(fh) ⊙ ε(fh))(x));
# Alternative method for operation
# ε_map = Array(ε(dv)(x));
# fh_cell = Array(get_cell_dof_values(fh));
# εf_map2 = broadcast((ε_dv,f)->(ε_dv * f) .⊙ (ε_dv * f),ε_map,fh_cell);

# Create FEFunction from cell values
εf_map_h = FEFunction(V_scalar,gather_free_values(V_scalar,εf_map));
εf_map_return = Array(get_cell_dof_values(εf_map_h));

εf_map_return ≈ εf_map # false
norm(norm.(εf_map_return - εf_map,Inf),Inf) # ~0.0396
```

I imagine that this is because `gather_free_results` is expecting a different cell array?

**Comment by amartinhuertas** [comment]
> I imagine that this is because gather_free_results is expecting a different cell array?

Not really. The function `ε(fh) ⊙ ε(fh)` is not continuous accross cell interfaces.

**Comment by amartinhuertas** [comment]
> But I’d expect that creating a FEFunction from cell values then returning the cell values from the FEFunction would return the same result? Perhaps I’m mistaken..

Yes, correct, but as far as the node has the same value in all cells that share the node, i.e., as far as it is continuous. 

In your case, you may have different values for the same node in the different cells that share it, so that gather_free_values takes one of these arbitrarily assuming that a node has the same value in all cells that share it (when it does not). If you try with a DG-type FE space for V_scalar your checks should work.

**Comment by zjwegert** [comment]
This is exactly what I needed. Thank you for all your help @amartinhuertas!

**Comment by amartinhuertas** [comment]
Why don't you just interpolate ε(fh) ⊙ ε(fh) into the dg-type space ?

**Comment by zjwegert** [comment]
This is certainly an option for the example problem above. 

In my application, this is being used to calculate shape sensitivities using the same style as the alternative operation in the comment above. I think this should be more efficient as the strain only needs to be evaluated once for the basis function.
