### ISSUE TITLE
Surface coupling multiphysics

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#85]
We need to define surface-coupled multiphysics. The main new ingredient here is the definition of a mask in a (volume or surface)mesh that will allow one to describe subsets via labels in cell values arrays. With this feature, the rest should be quite standard.

**Comment by santiagobadia** [comment]
@fverdugo don't you think that it should already be solved with the `MeshRestriction` only being used for integration purposes, since the FESpace must be global but non-constant (different things in different cells).

Can you identify the missing parts here? I guess

1. I think we must have the possibility to integrate on restrictions, but we already can.
2. We should have a full `ModelRestriction` with boundary conditions, I think we haven't.
3. We should be able to integrate e.g. jump terms on interfaces for different quantities, e.g., fluid and solid velocity jumps across interface, which I guess will require some work too.

**Comment by fverdugo** [comment]
Jumps at any interior interface can already be computed. The missing part is if you want to allow the fluid-solid field to be discontinuous at the interface in order to impose continuity with Nitsche. A way of solving this is to implement a new FE space constructor that leads to a continuous space everywhere except on a set of user-defined faces.

The other missing part is the ability to define multifield FESpaces where the underlying fields are defined on different meshes (e.g., the pressure only in the fluid domain)

**Comment by oriolcg** [comment]
When working with domains generated using ```GridPortion```, the resulting geometrical entities are grouped in two sets: "interior" and "boundary". Therefore, a unique boundary/interface condition can only be applied to the whole "boundary" set. 

In order to enable different boundary/interface conditions when working with geometries generated from ```GridPortion```, one should have the ability to define subsets of entities that satisfy certain condition (e.g. all facets on a given coordinate, all facets between two portions, ...)

**Comment by santiagobadia** [comment]
You can do things like...

```
using Test
using Gridap
import Gridap: ∇
using Gridap.Arrays
using Gridap.Geometry

domain = (0,1,0,1)
partition = (2,2)
model = CartesianDiscreteModel(domain,partition)
grid = get_grid(model)
# background_grid = CartesianGrid(domain,partition)

const x0 = 0.5
const x1 = 1.0
const y0 = 0.0
const y1 = 0.4

function is_in(coords)
  n = length(coords)
  x = (1/n)*sum(coords)
  x0 < x[1] < x1 && y0 < x[2] < y1 
end

oldcell_to_coods = get_cell_coordinates(grid)
cell_to_oldcell = findall(collect1d(apply(is_in,oldcell_to_coods)))
```
We certainly need ways to predefine labels in regions of the domain, and then extract from that the restrictions. I think that it is also possible do something similar for interfaces between two domains by  creating a filter that checks the labels of the cells.

In any case, we can start thinking about a problem like FSI, in which one unknown is on the whole domain (the velocity/displacement) and the other one, the pressure, only in a portion. It would be the zero step.

**Comment by santiagobadia** [comment]
I attach a sketch of the simplest surface coupled problem I can imagine, which couples the vector Laplacian with the Stokes problem. First, I consider, as I said above, that the velocity is a space on the whole domain and the pressure only leaves on part of it.

```
using Test
using Gridap
import Gridap: ∇
using Gridap.Arrays
using Gridap.Geometry

domain = (0,1,0,1)
partition = (2,2)
model = CartesianDiscreteModel(domain,partition)
grid = get_grid(model)
# background_grid = CartesianGrid(domain,partition)

const x0 = 0.5
const x1 = 1.0
const y0 = 0.0
const y1 = 0.4

function is_in(coords)
  n = length(coords)
  x = (1/n)*sum(coords)
  x0 < x[1] < x1 && y0 < x[2] < y1
  # true
end

function is_out(coords)
  n = length(coords)
  x = (1/n)*sum(coords)
  !(x0 < x[1] < x1 && y0 < x[2] < y1)
end
a = true
!a

oldcell_to_coods = get_cell_coordinates(grid)

solid_cells= findall(collect1d(apply(is_in,oldcell_to_coods)))
solid_grid = GridPortion(background_grid,solid_cells)

fluid_cells = findall(collect1d(apply(is_out,oldcell_to_coods)))
fluid_grid = GridPortion(background_grid,fluid_cells)

# Probably better having a ModelRestriction
solid_topo = GridTopology(solid_grid)
solid_labels = FaceLabeling(solid_topo)
solid_model = DiscreteModel(solid_grid,solid_topo,solid_labels)

fluid_topo = GridTopology(fluid_grid)
fluid_labels = FaceLabeling(fluid_grip)
fluid_model = DiscreteModel(fluid_grid,fluid_topo,fluid_labels)

order = 1

# Not sure about boundary conditions...
V = TestFESpace(
 model=model,
 order=order,
 reffe=:Lagrangian,
 valuetype=Vector{2,Float64})

u(x) = VectorValue( x[1]^2 + 2*x[2]^2, -x[1]^2 )
∇u(x) = TensorValue( 2*x[1], 4*x[2], -2*x[1], zero(x[1]) )
Δu(x) = VectorValue( 6, -2 )

p(x) = x[1] + 3*x[2]
∇p(x) = VectorValue(1,3)

f_f(x) = -Δu(x) + ∇p(x)
g_f(x) = tr(∇u(x))

f_s(x) = -Δu(x)

∇(::typeof(u)) = ∇u
∇(::typeof(p)) = ∇p

# Poisson solver as always

u(x) = x[1]^2 + x[2]
∇u(x) = VectorValue( 2*x[1], one(x[2]), zero(x[1]) )
Δu(x) = 2
f(x) = - Δu(x)
∇(::typeof(u)) = ∇u

order = 1

V = TestFESpace(
 model=model,
 order=order,
 reffe=:Lagrangian,
 labels=labels,
 valuetype=VectorValue{2,Float64},
 dirichlet_tags="dirichlet",
 conformity=:H1)

Q = TestFESpace(
 model=model,
 order=order-1,
 reffe=:Lagrangian,
 valuetype=Float64,
 conformity=:H1)

U = TrialFESpace(V,u)
P = TrialFESpace(Q)

Y = MultiFieldFESpace([V,Q])
X = MultiFieldFESpace([U,P])

solid_trian = get_triangulation(solid_model)
degree = order
solid_quad = CellQuadrature(solid_trian,degree)

fluid_trian = get_triangulation(fluid_model)
degree = order
fluid_quad = CellQuadrature(fluid_trian,degree)

a_s(v,u) = inner(∇(v),∇(u))
l_s(v) = v*f_s
t_Ωs = AffineFETerm(a,l,solid_trian,quad)


function a_f(x,y)
  u,p = x
  v,q = y
  inner(∇(v),∇(u)) - (∇*v)*p + q*(∇*u)
end

function l_f(y)
  v,q = y
  v*f_f + q*g_f
end

t_Ωf = AffineFETerm(a_f,l_f,fluid_trian,quad)

op = AffineFEOperator(U,V,t_Ωs,t_Ωf)

uh = solve(op)

e = u - uh

l2(v) = v*v
h1(v) = v*v + inner(∇(v),∇(v))

el2 = sqrt(sum( integrate(l2(e),trian,quad) ))
eh1 = sqrt(sum( integrate(h1(e),trian,quad) ))

tol = 1.0e-9
@test el2 < tol
@test eh1 < tol

writevtk(trian,"trian",cellfields=["uh"=>uh,"ph"=>ph])
```
I have not even run the code. You can create a new branch and start looking at it if you want. I think that with what we have everything should work. There are some nasty things, like the creation of the restriction of the model. @fverdugo at which stage is the model restriction? We should have a restriction of the model that inherits Dirichlet flags, etc. Probably, we want a method that creates the `ModelPortion` instead of the `GridPortion`.

The next step would be a Nitsche-type coupling and independent spaces for the velocity...

**Comment by santiagobadia** [comment]
I have created a new branch in 7c940b477210f5257989ff565e88c6b3fb5713c9 with the previous driver...

**Comment by fverdugo** [comment]
Surface-coupled multi-physics is still not solved in Gridap, thus I recommend to wait a bit here. In any case, I think we are not far away from this.

Just a comments: I believe that `GridPortion` and  `ModelPortion` will not be used in multi-physics drivers. They will be used mainly for embedded FEM. For multi-physics, I am thinking in other solutions that will fit better to the current FEspace and Assembly machinery.

**Comment by fverdugo** [comment]
@santiagobadia your driver can work as long as you define the pressure in the whole domain (fluid+solid).  The missing part is to define the pressure only in the fluid domain. I more or less know how to solve it.

**Comment by fverdugo** [comment]
By the way, to integrate in a portion of the domain its not needed to create a `GridPortion` or a `ModelPortion`. A `TriangulationPortion` is enough and much more efficient. That's why I said that `GridPortion` and `ModelPortion` are not needed for multi-physics.

**Comment by santiagobadia** [comment]
If I define the pressure in the whole domain, then I end up with a singular problem.

The `ModelPortion` (or whatever we want to call it) is not needed for integration, it is needed to define the `FESpace`. I think we should be able to generate FE spaces on portions of the domain. I don't think we want to use void FEs or similar things... What do you propose?

**Comment by fverdugo** [comment]
> I don't think we want to use void FEs or similar things...

Completely agree! 

I want to achieve a user API like:

```julia

# Solid-fluid test space with strong continuity at FSI interface 
V = TestFESpace(
  model=model,
  reffe=:QLagrangian,
  valuetype=VectorValue{D,Float64},
  order=order,
  conformity = :H1,
  dirichlet_tags = ["solid_diri", "fluid_diri"])

# Presure space
Q =  TestFESpace(
  model=model,
  reffe=:PLagrangian,
  valuetype=VectorValue{D,Float64},
  order=order-1,
  restricted_at = list_of_cells_in_fluid_domain, # New kw-argument
  conformity = :L2,
  dirichlet_tags = "pressure_diri" ) 
```

Then, the user works as always with the only restriction that pressure-related quantites can only be integrated / computed / etc / on cells in the list `list_of_cells_in_fluid_domain`. The user does not need to be aware of  `ModelPortion` et al.

Moreover, I want to achieve a even more advanced API that allows one to impose the solid-fluid continuity weakly. The related test space would be constructed as 

```julia
V = TestFESpace(
  model=model,
  reffe=:QLagrangian,
  valuetype=VectorValue{D,Float64},
  order=order,
  conformity = :H1,
  discontinuous_at = list_of_interface_facets, # New kw-argument
  dirichlet_tags = ["solid_diri", "fluid_diri"]) 
```
 
Then, the user can impose weak continuity a la Nitsche  using the skeleton triangulation build as

```julia
strian = SkeletonTriangulation(model,list_of_interface_facets)
```

There are some implementation details still missing, but is the basic API that I want to expose to the users.

**Comment by fverdugo** [comment]
@santiagobadia @oriolcg 

In PR #203 I have implemented the main building blocks for surface-coupling problems.

The key components are 
- `RestrictedTriangulation`: A triangulation used to integrate in a subset of the domain functions that are defined in the whole domain. (Not to be confused with `TriangulationPortion`, the latter can be used only to integrate functions defined in the portion of the domain, not in the whole domain).
- `InterfaceTriangulation`. It returns a `SkeletonTriangulation` object whose normal vector is outwards to the "left" side of the interface (in the example below outwards to the fluid domain).
- `ExtendedFESpace`. Given a `FESpace` defined in a subset of a domain, it returns another `FESpace` object representing its extension to the whole domain by using a 0-extension.

By the way, I have also implemented `DiscreteMoedelPortion` which inherits the labels of the given model.

You can find a full driver in https://github.com/gridap/Gridap.jl/blob/starting_to_add_surface_coupling/test/GridapTests/SurfaceCouplingTests.jl

In the following snipped you can see a preview of how these objects are constructed. 

```julia

using Gridap
using Gridap.Arrays
using Gridap.Geometry
using Gridap.FESpaces

# Geometry

n = 40
mesh = (n,n)
domain = 2 .* (0,1,0,1) .- 1
model = CartesianDiscreteModel(domain, mesh)

labels = get_face_labeling(model)
add_tag_from_tags!(labels,"dirichlet",[3,4,6])

trian = Triangulation(model)

const R = 0.4

function is_in(coords)
  n = length(coords)
  x = (1/n)*sum(coords)
  d = x[1]^2 + x[2]^2 - R^2
  d < 0
end

cell_to_coods = get_cell_coordinates(trian)
cell_to_is_solid = collect1d(apply(is_in,cell_to_coods))
cell_to_is_fluid = Vector{Bool}(.! cell_to_is_solid)

trian_solid = RestrictedTriangulation(trian, cell_to_is_solid)
trian_fluid = RestrictedTriangulation(trian, cell_to_is_fluid)

trian_Γ = InterfaceTriangulation(model,cell_to_is_fluid)
n_Γ = get_normal_vector(trian_Γ)

# FESpaces

# Now, this inherits the face labels of model
model_fluid = DiscreteModelPortion(model,cell_to_is_fluid)

# This FESpace is defined only in the fluid part
Q_fluid = TestFESpace(
  model=model_fluid,
  valuetype=Float64,
  order=1,
  reffe=:Lagrangian,
  conformity=:H1,
  dirichlet_tags="dirichlet")

# This one is defined everywhere with a 0 extension
Q = ExtendedFESpace(Q_fluid,trian_fluid)

# Note that qh is 0 outside fluid domain
q(x) = x[1]+x[2]+1
qh = interpolate(Q,q)

writevtk(trian_fluid,"trian_fluid")
writevtk(trian_solid,"trian_solid")
writevtk(trian,"trian",nsubcells=10,cellfields=["qh"=>qh])
writevtk(trian_Γ,"trian_G",nsubcells=2,cellfields=["normals"=>n_Γ])

```

![geom](https://user-images.githubusercontent.com/48508177/75673742-f048de80-5c83-11ea-8cea-eeb5999c9502.png)



Note that `qh0` has been extended with 0, and it fulfills the boundary conditions on the top side.

![ph](https://user-images.githubusercontent.com/48508177/75673788-0787cc00-5c84-11ea-8951-f05f261824a3.png)

**Comment by fverdugo** [comment]
Work already in master.

Sample driver in: https://github.com/gridap/Gridap.jl/blob/master/test/GridapTests/SurfaceCouplingTests.jl
