### ISSUE TITLE
Problems with discontinous pressures for Stokes drivers

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#86]
@fverdugo If I replace in `VectorValuedMultiFEOperatorsTests.jl` the continuous pressure space by a discontinous one, tests do not pass. The mixed FE space with continuous pressures does not satisfy the inf-sup condition whereas the discontinuous one does. I have another test `StokesLidDrivenCavity.jl` with wrong results. The problems are probably related.

**Comment by fverdugo** [comment]
If I am not wrong, I am using Taylor Hood elements, namely Q2(cont)/Q1(cont), which should be inf-sub stable. I am not sure if the space Q2(cont)/Q1(disc) is inf-sub stable (the pressure space is quite large), perhaps this is why the tests do not pass

**Comment by santiagobadia** [comment]
You are right, I forgot DLagrangianFESpace is Q not P, so it is not going to work. For q=2 it works.
I will close this issue and open a new one about disc P on n-cubes
