### ISSUE TITLE
Add P polynomial spaces on n-cubes

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#87]
It will be needed for arbitrary order mixed FEs for the Stokes problem. I would say that it should be quite straightforward, since one can consider just the prebasis without any change of basis. Probably, we will need to interpolate these FE functions in a Q space of the same order for visualization purposes.

**Comment by fverdugo** [comment]
Hi @santiagobadia

I have started to do this work in branch  `implement_p_disct_reffe_for_n_cubes`

BTW, I have called the reference FE `PDiscRefFE`. Any better name??

**Comment by fverdugo** [comment]
By the way, any idea on how to constrain the pressure in one point when using these elements?

If I assign all the DOFs of the cell to the cell interior (which is what I am doing now), I cannot select a vertex to impose a Dirichlet condition. I would need, e.g., to mark a single cell, but in this case all the DOFs in the cell will be constrained instead on only one... and I assume this is not what we want.

**Comment by santiagobadia** [comment]
Hi @fverdugo 

In general, the pressure space is the equivalence class of L2 functions up to a mean value. Since we do not want to deal with indefinite problems, we must enforce one particular instance of these L2 functions. It would be nice to enforce zero mean value but it comes with a cost. Thus, the standard approach is to fix one node. You do not care about which one you impose. As a result, I would probably define a method that given a FESpace without Dirichlet data (it would not have much sense otherwise, but we could do it anyway) to enforce one (not chosen by the user) DOF. We could e.g. internally fix the first free DOF and enforce it to be fixed to zero.

Thus, you do not need to provide a geometrical tag, etc. Much easier. You could later take this pressure and straighforwardly convert it to zero mean value. We could create such a method, but it is 5 lines of code in Gridap.

**Comment by fverdugo** [comment]
Yes, I'll do it in this way. I also was thinking in some "algebraic" strategy instead of relaying on the geometry.

**Comment by fverdugo** [comment]
Done in PR #88!

I have extended my Stokes tests to P disc reference FEs. See file for retails https://github.com/gridap/Gridap.jl/blob/master/test/MultiFieldTests/VectorValuedMultiFEOperatorsTests.jl

Closing issue
