### ISSUE TITLE
Select quadrature data domain

### ISSUE THREAD

**Issue by ericneiva** [gridap/Gridap.jl#877]
Hi, @amartinhuertas,

Some time ago, you added in a6cc908d a trait template parameter to `CellQuadrature`. It lets the user select whether to _integrate_ in reference or physical domain. 

Conversely, the default domain for the quad _data_ is reference and it cannot be changed at the user level :point_down:

https://github.com/gridap/Gridap.jl/blob/a6cc908da289ce453413b069d2bc4151fcc628b6/src/CellData/CellQuadratures.jl#L49-L57

The method above is the only one that calls the constructor (see line 56). As you can see it sets the data domain style to `ReferenceDomain()`.

I am interfacing Gridap to a library that computes quad points and weights directly in the physical domain. I can make it work, but I need to replicate the above method to set the data domain to physical.

Have you thought about letting the user have power over both data and integration domain styles? I thought I could change the API of `CellQuadrature` such that both domain styles are keyword arguments. What do you think?

**Comment by amartinhuertas** [comment]
Hi @ericneiva,

thanks for your issue, and sorry for the very late reply (the last months have been quite hectic for me, but anyway ...) 

Let me answer to your comments one by one. 

> The method above is the only one that calls the constructor (see line 56). As you can see it sets the data domain style to ReferenceDomain().

Let me note that apart from https://github.com/gridap/Gridap.jl/commit/a6cc908da289ce453413b069d2bc4151fcc628b6, there is another related commit, namely, https://github.com/gridap/Gridap.jl/commit/5167a37e2458140df80ac9434722a7083e3f1388. In this later commit, I recovered the signature of an older outer constructor (for backward compatibility). This outer constructor also calls the inner constructor, and lets you specify `DataDomainStyle`. In any case, this outer constructor does not provide extra expressivity **as it is possible to call the inner constructor passing all the fields of the structure.** (i.e., the default inner constructor).

> I am interfacing Gridap to a library that computes quad points and weights directly in the physical domain. I can make it work, but I need to replicate the above method to set the data domain to physical.

If am not missing anything, I don't see why there is **a need**.  You can still leverage the default inner constructor of `CellQuadrature` from `Measure`, e.g.:

`Measure(cell_quad, cell_point, cell_weight, trian, PhysicalDomain(), PhysicalDomain())`

> Have you thought about letting the user have power over both data and integration domain styles? I thought I could change the API of CellQuadrature such that both domain styles are keyword arguments. What do you think?

The user has already this power. See my point above. In any case, I see that this is a quite inconvenient low-level API  for the user as you have to provide all the details of the `CellQuadrature` from `Measure`, while there is part of the work that Gridap can do for you . Was this your main concern? As far I understand,  you would like something as, e.g.: (I am aware you have proposed something different in the PR):

`Measure(trian, degree, PhysicalDomain(), PhysicalDomain())`

Am I correct? 

Now let me comment on PR #885 there. (btw thanks for the PR).

**Comment by ericneiva** [comment]
Hi, @amartinhuertas, thank you so much for your reply.

>  In any case, I see that this is a quite inconvenient low-level API for the user as you have to provide all the details of the `CellQuadrature` from `Measure`, while there is part of the work that Gridap can do for you . Was this your main concern?

Spot on.

> sorry for the very late reply

It's alright :smile: I completely understand.

I think we can finish the discussion at PR #885.
