### ISSUE TITLE
Face labelling tags of an UnstructuredDiscreteModel changed after refining

### ISSUE THREAD

**Issue by wei3li** [gridap/Gridap.jl#890]
Hi @amartinhuertas and @JordiManyer,

I build an `UnstructuredDiscreteModel` by loading a Gmsh file, then I refine the model. The issue is that the face labelling tags of the refined model are not the same as the original model. Could you please look into this?
The following is an MWE.
```julia
using Gridap, GridapGmsh

model = GmshDiscreteModel("square.txt")
println(get_face_labeling(model).tag_to_name)
# prints ["dirichlet_points", "dirichlet_surfaces", "neumann_surface"]
refined_model = Gridap.Adaptivity.refine(model)
println(get_face_labeling(refined_model).tag_to_name)
# prints ["interior", "boundary"]
```

Gridap version: master branch
GridapGmsh version: v0.6.0
Mesh file: [square.txt](https://github.com/gridap/Gridap.jl/files/11048271/square.txt)

**Comment by JordiManyer** [comment]
I see... this is a hard thing to do in general, but i think child-face-related developments in #886 can be just the thing we need. What kind of polytope + refinement do you need this for?

**Comment by amartinhuertas** [comment]
Triangles 1:4 refinement

**Comment by JordiManyer** [comment]
@wei3li , @amartinhuertas I think I've successfully fixed the issue. Could you try to run your code using the `refinement-rule-subface-glue` branch? Let me know if it fixes the issue.

**Comment by wei3li** [comment]
Hi @JordiManyer, I've tested with branch `refinement-rule-subface-glue`, and the labels are correct now. Thanks so much for fixing this issue!

**Comment by JordiManyer** [comment]
No worries! I'll close the issue then.
