### ISSUE TITLE
Oriented simplicial meshes

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Gridap.jl#90]
@fverdugo I would say that high order Tets are almost working. They work for first and second order. For third order the missing ingredient is the fact that we must enforce oriented meshes. I.e., sorting the nodes in increasing order with respect to global / local index must be the same. It is just going through the simplices and change the order of the nodes.

Since you have done most of the mesh work, I wanted to ask you where we can do it. It is a very simple method, I could implement it. But I need to get into grid, triangulation, model, etc... and see were it has sense to do it (and when).

**Comment by fverdugo** [comment]
I would implement the method  in  `Gridap.jl/Geometry/UnstructuredGrids.jl` with a signature

`orient_simplex_connectivities!(cell_to_nodes_data, cell_to_nodes_ptrs)`

where the arguments represent the cell connectivity. The function should only modify the first argument.

Then, I would use this function whenever a grid of simplexes is created. E.g., in the `simplexify(::Grid)` function in Gridap, and in the `GridapGmsh` repo when a mesh of tets is read from GMHS.

**Comment by santiagobadia** [comment]
Would it automatically work when you simplexify a model?
I guess that internally we should also call the orientation of the grid...

**Comment by fverdugo** [comment]
`simplexify(::DiscreteModel)` calls `simplexify(::Grid)`. This is only needed in the later method.

see
https://github.com/gridap/Gridap.jl/blob/master/src/Geometry/Simplexify.jl

**Comment by fverdugo** [comment]
Here is where the connectivity of the tets is created.
https://github.com/gridap/Gridap.jl/blob/0a72671f519e49a411b75d27c42da84f6e1d8627/src/Geometry/Simplexify.jl#L16
Just add the orientation function below.

**Comment by santiagobadia** [comment]
@fverdugo It is not that simple

https://github.com/gridap/Gridap.jl/blob/0a72671f519e49a411b75d27c42da84f6e1d8627/src/Geometry/Simplexify.jl#L38-L46

The graph and face label generation does not rely on the grid.
Only orienting the grid I have ended up with non-consistent models. I have to deep into these methods to see how I have to modify them accordingly.

**Comment by santiagobadia** [comment]
The problems seems to be here
https://github.com/gridap/Gridap.jl/blob/0a72671f519e49a411b75d27c42da84f6e1d8627/src/Geometry/Simplexify.jl#L52-L53

The algorithm seems to be dependent of the orientation of the simplices with respect to the quad

**Comment by santiagobadia** [comment]
As far as I can see, everything is OK till
https://github.com/gridap/Gridap.jl/blob/0a72671f519e49a411b75d27c42da84f6e1d8627/src/Geometry/Simplexify.jl#L74

**Comment by santiagobadia** [comment]
Much cleaner to change
https://github.com/gridap/Gridap.jl/blob/0a72671f519e49a411b75d27c42da84f6e1d8627/src/Geometry/Simplexify.jl#L244
and provide the right mesh right away.
It seems that for 2D order 3 works

**Comment by santiagobadia** [comment]
High order tets working for Gridap-generated models.
Next step, take a look at Gmesh-imported meshes.

**Comment by fverdugo** [comment]
Great!

Could you add a new record in `NEWS.md` mentioning the new functionality?

**Comment by santiagobadia** [comment]
Hi @fverdugo 

Yes, but I saw that in the NEWS we must provide the commit in which the novelty has been added. So, it seems I have to push, get the commit flag, modify news and push again. Is this the way to go? Am I missing anything? I will do it when I will have some time... now I have to leave.

I have installed Gmsh, etc, and I have added a light mesh in GridapMsh for debugging purposes

But I am not sure I understand how it works. E.g., gridap.initialize() gives me an error because gridap is just a string that provides the path of the gmsh executable. 

I am stuck there. I wanted to implement the re-orientation of the mesh in GridapGmsh.

**Comment by fverdugo** [comment]
> Yes, but I saw that in the NEWS we must provide the commit in which the novelty has been added. So, it seems I have to push, get the commit flag, modify news and push again. Is this the way to go? Am I missing anything? I will do it when I will have some time... now I have to leave.

The idea is that, when the new functionality is tested and available in master, then one adds a record in NEWS.md. I typically use the editor in github so that I can preview the markdown.

**Comment by fverdugo** [comment]
> I have installed Gmsh, etc, and I have added a light mesh in GridapMsh for debugging purposes
> But I am not sure I understand how it works. E.g., gridap.initialize() gives me an error because gridap is just a string that provides the path of the gmsh executable.

Have you installed GridapGmsh, properly? can you run the tests?
```
pkg> test GridapGmsh
```

**Comment by santiagobadia** [comment]
Yes, the tests pass. I get stuck in

https://github.com/gridap/GridapGmsh.jl/blob/7a04450783fd6d19b8babdfeb3b0159253add74a/light-mesh/light-mesh.jl#L13

it must be a silly think...

**Comment by fverdugo** [comment]
This is strange. I can execute this file up to line 15 (included). Perhaps you are not in a clean environment.

Try (in the GridapGmsh root folder):
```
$ julia --project=.
# Enter Pkg mode
GridapGmsh> instantiate
# Exit Pkg mode
julia> include("light-mesh/light-mesh.jl")
```
The file should run up to line 15

Please, delete the folder once you are done. Perhaps it is also a good idea to use a branch different from `master` to do tests like this one.

Hope it helps!

**Comment by santiagobadia** [comment]
It seems I have to build every time, I did it only once. Further sessions, only activate the project.
Now, I have added the orientation of meshes for in GridapGmsh. The tests pass.
The missing part is to test high order methods, even though now it should work. 
But first, I need to publish the current version of Gridap with high order tet support and then update the dependencies in GridapGmsh.

**Comment by santiagobadia** [comment]
I have created a new version of Gridap in order to use check high order tets in `GridapGmsh`. I will open an issue in `GridapGmsh` saying that tests for high order Tets are pending to the registration of the new `Gridap` package.

I guess there are ways to use a local version of a package, I will investigate it.

**Comment by fverdugo** [comment]
> It seems I have to build every time, I did it only once. Further sessions, only activate the project.

In theory, the build step is only needed once (when the package is installed).

**Comment by fverdugo** [comment]
> I have created a new version of Gridap in order to use check high order tets in GridapGmsh. I will open an issue in GridapGmsh saying that tests for high order Tets are pending to the registration of the new Gridap package.

Yes, sure. You can track e.g., a particular branch of a package:

```
GridapGmsh> add Gridap#master
```

It is well explained in the Pkg documentation.

Note: never register a package that depends on un-registered versions of other packages.

**Comment by fverdugo** [comment]
If you want to track a local version:

```
GridapGmsh> develop /path/to/Gridap.jl
```

Never to this in the master branch of GridapGmsh since it only work for you.
