### ISSUE TITLE
Neighbours of a cell.

### ISSUE THREAD

**Issue by abaillet** [gridap/Gridap.jl#900]
Dear all, 

I'm trying to build an application for which I require local information about a certain region in the domain. Specifically, given a triangular element in 2d, I want to evaluate the solution at the midpoint of the cell, and at the midpoint of the three cells which share an edge with this element. I've figured out a way to evaluate the solution at the midpoint of every cell using a CellPoint, however, I have not been able to efficiently find the neighbors of a given cell. Is there a way to do this? 

Thank you!
Álvaro

**Comment by JordiManyer** [comment]
Hey! Sorry for the late response...

The information you are looking for is located in the `GridTopology` object: Given a model with cell dimension `Dc`, you can do 

```
topo = get_grid_topology(model)
cells_to_nbor_cells = Geometry.get_faces(topo,Dc,Dc)
```
This will return an array of length the number of cells in your model, with a vector of neighbors in each position. 

You can find a more detailed explanation in this [gitter thread](https://matrix.to/#/!mSZoaZwNZhWulNruaK:gitter.im/$qNiad29RTOp4SyqNiWrZe93QP_tHI2KhSwgaDDeB2ro?via=gitter.im&via=matrix.org&via=tu-dresden.de). By the way, think kind of questions are more suited for our gitter channel (to keep the issues at a minimum).
