### ISSUE TITLE
Change in terminology in FaceLabels

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#92]
Wrt the FaceLabels type, we have to concepts: “labels” and “tags”. The first for geometrical objects, and the second for user defined aggregations of geometrical entities. 

I would change the notation to a more self explaining one. I would follow gmsh notation and change “label” to (geometrical) “entity” and “tag” to (physical) “group”. That is “label” -> “entity”, “tag”-> “group”. 

What do you mean @santiagobadia ?

Any other options?

**Comment by fverdugo** [comment]
What I dont like of the current notation is that label and tag are synomins in english, but they refer to two different things in the code...

**Comment by santiagobadia** [comment]
I agree that entity are group are better. Or entity and tag, it sounds good to me too, you put a tag to an entity.

**Comment by fverdugo** [comment]
Perfect! I would keep "group" like in GMSH. It explicitly denotes a group of entities.

I can do the changes.

**Comment by fverdugo** [comment]
After thinking it better, perhaps I also like more "tag" than "group". We use "diritags" a lot in the drivers, and I like it.

**Comment by fverdugo** [comment]
This has been addressed in v0.7.0. Closing issue.
