### ISSUE TITLE
Robin Boundary

### ISSUE THREAD

**Issue by HenningScheufler** [gridap/Gridap.jl#922]
Does Gridap support robin boundary conditions?

As I'm new to Gridap and FEM, it would be interesting how to apply them to the transient poisson example.

**Comment by ericneiva** [comment]
Hi @HenningScheufler, welcome!

Yes, Gridap supports Robin BCs.

Take a look at this [example](https://github.com/gridap/JourneeGridap2022/blob/main/notebooks/exercise_01_warmup/t01_commented_discrete_models_from_gmsh_and_bcs.ipynb).

For similar enquiries, please use our [gitter](https://app.gitter.im/#/room/#Gridap-jl_community:gitter.im). We would like to avoid cluttering the issue tracker and reserve it for bugs and/or detailed discussions.
