### ISSUE TITLE
DG for multi-field computations

### ISSUE THREAD

**Issue by fverdugo** [gridap/Gridap.jl#94]
Hi @santiagobadia,

DG machinery already works for single-field problems (at this moment in a branch of mine), see file: https://github.com/gridap/Gridap.jl/blob/adding_missing_devs_for_IDG_discretization/test/FESpacesTests/DGFEOperatorsTests.jl

The changes needed to the multi-field extension, should be minimal. This is not a problem. However, I need help to find a setup to test it. 

**Do you know, e.g., a DG formulation for the Stokes problem, which does not require to compute second order derivatives?**

**Comment by santiagobadia** [comment]
Excellent! Please take a look at this [article](https://link.springer.com/article/10.1007/s10915-008-9261-1). It is an equal-order Stokes DG solver that does not require second order derivatives.

**Comment by fverdugo** [comment]
The DG stokes formulation of the mentioned paper has been implemented in a test!

Via PR #99 

closing issue
