### ISSUE TITLE
Eigen-values and vectors of SymTensorValue

### ISSUE THREAD

**Issue by akumarp3** [gridap/Gridap.jl#953]
Hello,

I am new to Julia and also Gridap. I have understood the basic ides of Gridap and started to implement my problem. In my application, I have to evaluate the eigenvalues and eigenvectors of a variable which is of "SymTensorValue" type and I have used the functions available in LinearAlgebra package to do so. However, the code breaks wit the error 

_UndefVarError: eigvals not defined_

I tried to build second order tensor from the values of "SymTensorValue" variable and then evaluate the eigenvalues and eigenvectors. Even in this case, the code is failing with the same error. Can someone give some suggestions on evalauting the eigenvalues and eigenvectors of a variable of "SymTensorValue" type?

Thank you.

**Comment by amartinhuertas** [comment]
Can you send a MWE (minimum working example) where the issue can be reproduced?

In any case, I would `convert` SymTensorValue into an `Array`. I would guess that eigvals from LinearAlgebra requires an object of type `Array` as input.

**Comment by santiagobadia** [comment]
@akumarp3 The "issue" is that we have not implemented the method `eigvals` for `SymTensorValue`.

Here, you have two options. One is to import `eigvals` from `LinearAlgebra` and extend it to `SymTensorValue` type. As @amartinhuertas says, it is just to apply `eigvals` to the `array` inside `SymTensorValue`. I would be happy to accept this PR.

Or just extract the array and call `eigvals` in your code when you need it.

**Comment by akumarp3** [comment]
Thank you very much for your suggestions. Excuse me for late reply.

@amartinhuertas I am solving a coupled problem for solving fracture problem using phase-field. The governing equation for phase-field requires a part of strain energy density $\psi$ pertaining to tension part and to to evaluate this part, I need to evaluate the eigenvalues and eigenvectors of symmetric strain tensor (which is of type SymTensorValue). Practically, the EVP is solved at each integration point, to formulate the phase-field LES. I wasn't able to think of a MWE that can include this complexity. Sorry for the delay.

@santiagobadia Thanks for your suggestion. I
